#Requires -Version 5.1

function New-SetupContext {
    param(
        [string]$EntryScriptPath
    )

    $scriptRoot = Split-Path -Parent $EntryScriptPath
    $repoRoot = Split-Path -Parent $scriptRoot
    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)

    $copilotRoot = Join-Path $env:USERPROFILE '.copilot'
    $skillsTarget = Join-Path $copilotRoot 'skills'
    $codexRoot = Join-Path $env:USERPROFILE '.codex'
    $openCodeRoot = Join-Path $env:USERPROFILE '.config\opencode'
    $antigravityRoot = Join-Path $env:USERPROFILE '.gemini\antigravity-cli'
    $galStateRoot = Join-Path $env:USERPROFILE '.gal'
    $galConfigRoot = Join-Path $galStateRoot 'config'
    $galStateDirectory = Join-Path $galStateRoot 'state'
    $galStoreRoot = Join-Path $galStateRoot 'store'
    $galStorePluginsRoot = Join-Path $galStoreRoot 'plugins'
    $galGeneratedRoot = Join-Path $galStateRoot 'generated'
    $galGeneratedMcpRoot = Join-Path $galGeneratedRoot 'mcp'
    $galGeneratedXmachineRoot = Join-Path $galGeneratedRoot 'xmachine'
    $galDistRoot = Join-Path $galStateRoot 'dist'
    $galGeneratedProvidersRoot = Join-Path $galDistRoot 'providers'
    $galSourceRoot = Join-Path $galStateRoot 'source'

    $galSource = Join-Path $repoRoot 'commands\gal'
    $commandsSourceDir = Join-Path $repoRoot 'commands'
    $commandAliasNames = Get-ChildItem $commandsSourceDir -Directory |
        Where-Object {
            $_.Name -ne 'gal' -and (
                (Test-Path (Join-Path $_.FullName 'SKILL.template.md')) -or
                (Test-Path (Join-Path $_.FullName 'SKILL.md'))
            )
        } |
        Select-Object -ExpandProperty Name

    $commandSkillDirs = @(
        [pscustomobject]@{
            Name          = 'gal'
            Source        = $galSource
            Template      = Join-Path $galSource 'SKILL.template.md'
            CopilotTarget = Join-Path $skillsTarget 'gal'
            CodexTarget   = Join-Path $codexRoot 'skills\gal'
        }
    ) + ($commandAliasNames | ForEach-Object {
        $source = Join-Path $repoRoot ("commands\{0}" -f $_)
        [pscustomobject]@{
            Name          = $_
            Source        = $source
            Template      = Join-Path $source 'SKILL.template.md'
            CopilotTarget = Join-Path $skillsTarget $_
            CodexTarget   = Join-Path $codexRoot ("skills\{0}" -f $_)
        }
    })

    return [pscustomobject]@{
        ScriptRoot = $scriptRoot
        RepoRoot = $repoRoot
        Utf8NoBom = $utf8NoBom
        GalManagedFileHeader = '# Generated by GAL Setup-Machine. Do not edit manually.'

        GalStateRoot = $galStateRoot
        GalConfigRoot = $galConfigRoot
        GalStateDirectory = $galStateDirectory
        GalPluginsRoot = Join-Path $galStateRoot 'plugins'
        GalDataRoot = Join-Path $galStateRoot 'data'
        GalCacheRoot = Join-Path $galStateRoot 'cache'
        GalStoreRoot = $galStoreRoot
        GalStorePluginsRoot = $galStorePluginsRoot
        GalGeneratedRoot = $galGeneratedRoot
        GalDistRoot = $galDistRoot
        GalSourceRoot = $galSourceRoot
        GalGeneratedMcpRoot = $galGeneratedMcpRoot
        GalGeneratedXmachineRoot = $galGeneratedXmachineRoot
        GalGeneratedProvidersRoot = $galGeneratedProvidersRoot
        InstallStateFile = Join-Path $galStateRoot 'install-state.json'
        GalConfigFile = Join-Path $galConfigRoot 'config.json'
        GalPluginsLockFile = Join-Path $galStateDirectory 'plugins.lock.json'
        GalXmachineConfigFile = Join-Path $galConfigRoot 'xmachine.json'
        GalGeneratedMcpFile = Join-Path $galGeneratedMcpRoot 'managed.json'
        GalGeneratedXmachineFile = Join-Path $galGeneratedXmachineRoot 'managed.json'

        CopilotRoot = $copilotRoot
        CopilotPluginInstallTarget = Join-Path $copilotRoot 'installed-plugins\gal-copilot\gal'
        AgentsTarget = Join-Path $copilotRoot 'agents'
        SkillsTarget = $skillsTarget

        SharedAgentsRoot = Join-Path $env:USERPROFILE '.agents'
        SharedSkillsTarget = Join-Path $env:USERPROFILE '.agents\skills'

        WorkspaceAgentsRoot = Join-Path $repoRoot '.agents'
        WorkspaceSkillsTarget = Join-Path $repoRoot '.agents\skills'
        WorkspaceRulesTarget = Join-Path $repoRoot '.agents\rules'

        GeminiRoot = Join-Path $env:USERPROFILE '.gemini'
        GeminiSkillsTarget = Join-Path $env:USERPROFILE '.gemini\skills'
        GeminiCommandsTarget = Join-Path $env:USERPROFILE '.gemini\commands'
        GeminiContextFile = Join-Path $env:USERPROFILE '.gemini\gal-context.md'
        GeminiSettingsFile = Join-Path $env:USERPROFILE '.gemini\settings.json'

        VscodeSettingsFile = Join-Path $env:APPDATA 'Code\User\settings.json'
        VscodeMcpFile = Join-Path $env:APPDATA 'Code\User\mcp.json'
        CopilotCliMcpFile = Join-Path $copilotRoot 'mcp-config.json'

        CodexRoot = $codexRoot
        CodexSkillsTarget = Join-Path $codexRoot 'skills'
        CodexConfigFile = Join-Path $codexRoot 'config.toml'

        OpenCodeRoot = $openCodeRoot
        OpenCodeSkillsTarget = Join-Path $openCodeRoot 'skills'
        OpenCodeAgentsTarget = Join-Path $openCodeRoot 'agents'
        OpenCodeCommandsTarget = Join-Path $openCodeRoot 'commands'
        OpenCodeConfigFile = Join-Path $openCodeRoot 'opencode.json'

        ClaudeRoot = Join-Path $env:USERPROFILE '.claude'
        ClaudeSkillsRoot = Join-Path $env:USERPROFILE '.claude\skills'
        ClaudePluginsRoot = Join-Path $env:USERPROFILE '.claude\plugins'
        ClaudePluginInstallTarget = Join-Path $env:USERPROFILE '.claude\skills\gal'
        ClaudeLegacyPluginInstallTarget = Join-Path $env:USERPROFILE '.claude\plugins\gal'

        AntigravityRoot = $antigravityRoot
        AntigravitySkillsTarget = Join-Path $antigravityRoot 'skills'
        AntigravityMcpFile = Join-Path $antigravityRoot 'mcp_config.json'
        AgyPluginArtifactRoot = Join-Path $galDistRoot 'provider-plugins\agy\gal'
        AgyPluginInstallTarget = Join-Path $env:USERPROFILE '.gemini/antigravity-cli/plugins/gal'

        McpSourceFile = Join-Path $repoRoot 'mcp.json'
        McpLocalFile = Join-Path $galConfigRoot 'mcp.local.json'

        GalSource = $galSource
        GalRootCopilot = Join-Path $copilotRoot 'gal'
        GalRootGemini = Join-Path $env:USERPROFILE '.gemini\gal'
        GalRootAntigravity = Join-Path $antigravityRoot 'gal'
        CommandsSourceDir = $commandsSourceDir
        CommandSkillDirs = $commandSkillDirs
        ActiveCommandSkillNames = @($commandSkillDirs | ForEach-Object { $_.Name })
        RuntimeCatalog = @(
            [pscustomobject]@{ Key = 'copilot'; Label = 'GitHub Copilot'; Description = 'shared Copilot agents, skills, GAL commands, VS Code settings bridge, VS Code MCP bridge, Copilot CLI MCP bridge' },
            [pscustomobject]@{ Key = 'antigravity'; Label = 'Antigravity CLI'; Description = 'Antigravity global skills, Antigravity MCP bridge, and Antigravity GAL_ROOT link' },
            [pscustomobject]@{ Key = 'gemini'; Label = 'Gemini CLI'; Description = 'legacy native command files plus GAL context/settings compatibility bridge' },
            [pscustomobject]@{ Key = 'codex'; Label = 'Codex CLI'; Description = 'installed GAL command skills, shared skills, Codex MCP bridge' },
            [pscustomobject]@{ Key = 'opencode'; Label = 'OpenCode'; Description = 'OpenCode agents, commands, reusable skill discovery, OpenCode MCP bridge' },
            [pscustomobject]@{ Key = 'claude'; Label = 'Claude Code'; Description = 'Claude plugin lifecycle state, optional Claude CLI MCP bridge, repo-local CLAUDE.md adapter' }
        )
    }
}

function Get-GalUserHome {
    if (-not [string]::IsNullOrWhiteSpace($env:USERPROFILE)) {
        return $env:USERPROFILE
    }

    if (-not [string]::IsNullOrWhiteSpace($env:HOME)) {
        return $env:HOME
    }

    return [Environment]::GetFolderPath('UserProfile')
}

function Get-GalPluginsRoot {
    return Join-Path (Get-GalUserHome) '.gal\plugins'
}

function Get-GalPluginRoot {
    param(
        [string]$PluginId = 'gal'
    )

    return Join-Path (Get-GalPluginsRoot) $PluginId
}

function Get-GalDataRoot {
    return Join-Path (Get-GalUserHome) '.gal\data'
}

function Get-GalPluginDataRoot {
    param(
        [string]$PluginId = 'gal'
    )

    return Join-Path (Get-GalDataRoot) $PluginId
}

function Get-GalCacheRoot {
    return Join-Path (Get-GalUserHome) '.gal\cache'
}

function Resolve-XmachineConfigRecord {
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [switch]$WarnOnLegacyFallback
    )

    $canonicalPath = Join-Path (Get-GalUserHome) '.gal\config\xmachine.json'
    $legacyPath = Join-Path $RepoRoot 'xmachine.config.json'

    if (Test-Path $canonicalPath) {
        return [pscustomobject]@{
            Path = $canonicalPath
            UsedLegacyFallback = $false
        }
    }

    if (Test-Path $legacyPath) {
        if ($WarnOnLegacyFallback) {
            Write-Host "  [WARN] Using legacy repository-root xmachine config: $legacyPath" -ForegroundColor Yellow
        }

        return [pscustomobject]@{
            Path = $legacyPath
            UsedLegacyFallback = $true
        }
    }

    return [pscustomobject]@{
        Path = $canonicalPath
        UsedLegacyFallback = $false
    }
}

function Get-ClaudeLifecycleStatePath {
    param(
        [pscustomobject]$Context
    )

    return Join-Path $Context.GalGeneratedProvidersRoot 'claude\managed.json'
}

function Test-ClaudeLifecycleState {
    param(
        [pscustomobject]$Context
    )

    $statePath = Get-ClaudeLifecycleStatePath -Context $Context
    if (-not (Test-Path $statePath)) {
        return $false
    }

    $state = Read-JsonOrderedMap $statePath
    if ($state -isnot [System.Collections.IDictionary]) {
        return $false
    }

    if ($state.Contains('provider') -and [string]$state['provider'] -ne 'claude') {
        return $false
    }

    return $true
}

function Initialize-SetupSession {
    param(
        [string]$EntryScriptPath,
        [switch]$Uninstall,
        [switch]$Replace,
        [switch]$DryRun,
        [switch]$Reconfigure,
        [string[]]$SelectedRuntimes,
        [string]$PrimaryRuntime,
        [switch]$EnsureRipgrep
    )

    $script:SetupOptions = [pscustomobject]@{
        Uninstall = $Uninstall.IsPresent
        Replace = $Replace.IsPresent
        DryRun = $DryRun.IsPresent
        Reconfigure = $Reconfigure.IsPresent
    }
    $script:SetupContext = New-SetupContext -EntryScriptPath $EntryScriptPath

    if (-not $script:SetupOptions.Uninstall -and $EnsureRipgrep) {
        Ensure-Ripgrep
    }

    if ($script:SetupOptions.Uninstall) {
        $script:SetupContext | Add-Member -NotePropertyName SelectedRuntimes -NotePropertyValue @() -Force
        $script:SetupContext | Add-Member -NotePropertyName PrimaryRuntime -NotePropertyValue $null -Force
    }
    else {
        if ($SelectedRuntimes.Count -gt 0) {
            $resolvedPrimaryRuntime = if ([string]::IsNullOrWhiteSpace($PrimaryRuntime)) {
                Get-DefaultPrimaryRuntime -SelectedRuntimes $SelectedRuntimes
            }
            else {
                $PrimaryRuntime
            }

            $script:SetupContext | Add-Member -NotePropertyName SelectedRuntimes -NotePropertyValue @($SelectedRuntimes) -Force
            $script:SetupContext | Add-Member -NotePropertyName PrimaryRuntime -NotePropertyValue $resolvedPrimaryRuntime -Force
        }
        else {
            $installSelection = Get-InstallSelectionState
            $script:SetupContext | Add-Member -NotePropertyName SelectedRuntimes -NotePropertyValue @($installSelection.SelectedRuntimes) -Force
            $script:SetupContext | Add-Member -NotePropertyName PrimaryRuntime -NotePropertyValue $installSelection.PrimaryRuntime -Force
        }
    }

    $selectedRuntimes = @($script:SetupContext.SelectedRuntimes)
    $script:SetupContext | Add-Member -NotePropertyName InstallCopilot -NotePropertyValue ($selectedRuntimes -contains 'copilot') -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallGemini -NotePropertyValue ($selectedRuntimes -contains 'gemini') -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallAntigravity -NotePropertyValue ($selectedRuntimes -contains 'antigravity') -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallCodex -NotePropertyValue ($selectedRuntimes -contains 'codex') -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallOpenCode -NotePropertyValue ($selectedRuntimes -contains 'opencode') -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallClaude -NotePropertyValue ($selectedRuntimes -contains 'claude') -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallSharedSkills -NotePropertyValue (($selectedRuntimes -contains 'codex') -or ($selectedRuntimes -contains 'opencode')) -Force
    $script:SetupContext | Add-Member -NotePropertyName InstallGoogleWorkspaceSkills -NotePropertyValue (($selectedRuntimes -contains 'gemini') -or ($selectedRuntimes -contains 'antigravity')) -Force
    $script:SetupContext | Add-Member -NotePropertyName NeedsBakedCommandSkills -NotePropertyValue (
        ($selectedRuntimes -contains 'copilot') -or
        ($selectedRuntimes -contains 'gemini') -or
        ($selectedRuntimes -contains 'antigravity') -or
        ($selectedRuntimes -contains 'codex') -or
        ($selectedRuntimes -contains 'opencode') -or
        ($selectedRuntimes -contains 'claude')
    ) -Force

    return $script:SetupContext
}

function Get-GalActiveProviderTarget {
    param(
        [Parameter(Mandatory)]
        [string]$Provider
    )

    return Join-Path $env:USERPROFILE (".gal\active\{0}" -f $Provider)
}

function Test-GalRootReadable {
    # Readability probe with a short timeout so a dead UNC/network path fails fast
    # instead of blocking mode resolution. Local paths are probed inline.
    param([string]$Path)

    $probe = {
        param($p)
        try {
            $enumerator = [System.IO.Directory]::EnumerateFileSystemEntries($p).GetEnumerator()
            [void]$enumerator.MoveNext()
            'readable'
        }
        catch {
            'unreadable'
        }
    }

    # Only network paths (UNC) risk hanging; guard those with a timed job.
    if ($Path -notmatch '^\\\\') {
        return ((& $probe $Path) -eq 'readable')
    }

    $job = Start-Job -ScriptBlock $probe -ArgumentList $Path
    try {
        if ($null -eq (Wait-Job -Job $job -Timeout 2)) {
            Stop-Job -Job $job -ErrorAction SilentlyContinue
            return $false
        }
        return ((Receive-Job -Job $job) -eq 'readable')
    }
    finally {
        Remove-Job -Job $job -Force -ErrorAction SilentlyContinue
    }
}

function Get-GalRootUsableError {
    # Returns $null when galRoot is usable, otherwise a string naming the first
    # failed check. Predicate: non-empty + directory + readable + GAL source checkout.
    param([string]$GalRoot)

    if ([string]::IsNullOrWhiteSpace($GalRoot)) {
        return 'galRoot is empty'
    }
    if (-not (Test-Path -LiteralPath $GalRoot -PathType Container)) {
        return "galRoot path does not exist or is not a directory: $GalRoot"
    }
    if (-not (Test-GalRootReadable -Path $GalRoot)) {
        return "galRoot is not readable or timed out (e.g. dead network path): $GalRoot"
    }
    foreach ($relativePath in @('commands', 'agent', 'skills')) {
        if (-not (Test-Path -LiteralPath (Join-Path $GalRoot $relativePath) -PathType Container)) {
            return "galRoot is not a GAL source checkout (missing '$relativePath/'): $GalRoot"
        }
    }

    return $null
}

function Test-GalRootUsable {
    param([string]$GalRoot)

    return ($null -eq (Get-GalRootUsableError -GalRoot $GalRoot))
}

function Resolve-InstallMode {
    # Authoritative mode resolution from devMode + galRoot.
    #   devMode false/absent      -> 'install' (normal mode)
    #   devMode true + usable root -> 'source'  (dev mode)
    #   devMode true + unusable    -> THROW (no silent fallback; see OQ-003 / TP-003)
    param(
        [bool]$devMode,
        [string]$galRoot
    )

    if (-not $devMode) {
        return 'install'
    }

    $usableError = Get-GalRootUsableError -GalRoot $galRoot
    if ($usableError) {
        throw "Dev mode is enabled (devMode=true) but galRoot is not usable: $usableError. Refusing to silently fall back to normal mode. Fix galRoot or set devMode=false."
    }

    return 'source'
}

function Get-ConfiguredInstallModeFromContext {
    param(
        [pscustomobject]$Context
    )

    if ($null -eq $Context -or -not (Test-Path $Context.GalConfigFile)) {
        $bootstrapInstall = $false
        if ($null -ne $Context -and ($Context.PSObject.Properties.Name -contains 'BootstrapInstall')) {
            $bootstrapInstall = [bool]$Context.BootstrapInstall
        }
        elseif ($env:GAL_BOOTSTRAP_INSTALL -in @('1', 'true', 'TRUE', 'True')) {
            $bootstrapInstall = $true
        }

        if ($bootstrapInstall) {
            return 'install'
        }

        return 'source'
    }

    $config = Read-JsonOrderedMap $Context.GalConfigFile
    if ($config) {
        # Authority: devMode + galRoot decide the mode. installMode is no longer read here.
        if ($config.Contains('devMode')) {
            $devMode = [bool]$config['devMode']
            $galRoot = [string]$config['galRoot']
            return (Resolve-InstallMode -devMode $devMode -galRoot $galRoot)
        }

        # Migration: legacy config has installMode but no devMode. Derive devMode once,
        # warn, and stop trusting installMode as ongoing authority. Re-running
        # install/update rewrites the config with devMode + galRoot.
        if ($config.Contains('installMode')) {
            $legacy = [string]$config['installMode']
            Write-Warning "config 'installMode' is deprecated; deriving devMode from it. Re-run install/update to migrate the machine config to devMode + galRoot."
            $derivedDevMode = ($legacy -eq 'source')
            $galRoot = [string]$config['galRoot']
            if ($derivedDevMode -and [string]::IsNullOrWhiteSpace($galRoot) -and
                ($Context.PSObject.Properties.Name -contains 'RepoRoot')) {
                $galRoot = [string]$Context.RepoRoot
            }
            return (Resolve-InstallMode -devMode $derivedDevMode -galRoot $galRoot)
        }
    }

    return 'source'
}

function Test-InstallModeFromContext {
    param(
        [pscustomobject]$Context
    )

    return (Get-ConfiguredInstallModeFromContext -Context $Context) -eq 'install'
}

function Test-SymlinkOrJunction([string]$Path) {
    if (-not (Test-Path $Path)) { return $false }
    $item = Get-Item $Path -Force
    return ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0
}

function New-SafeSymlink([string]$LinkPath, [string]$TargetPath, [string]$Type) {
    if ($script:SetupOptions.DryRun) {
        Write-Host "  [DRY RUN] $Type link: $LinkPath -> $TargetPath"
        return $true
    }

    if (Test-SymlinkOrJunction $LinkPath) {
        $existing = Get-Item $LinkPath -Force
        if ($existing.Target -contains $TargetPath) {
            Write-Host "  [SKIP] Already linked: $LinkPath"
            return $true
        }

        Write-Host "  [UPDATE] Replacing existing link: $LinkPath"
        $existing.Delete()
    }
    elseif (Test-Path $LinkPath) {
        if ($script:SetupOptions.Replace) {
            $bakPath = "$LinkPath.bak"
            if (Test-Path $bakPath) {
                Write-Host "  [WARN] Backup already exists at $bakPath — skipping"
                return $false
            }

            Rename-Item $LinkPath $bakPath
            Write-Host "  [BACKUP] $LinkPath -> $bakPath"
        }
        else {
            Write-Host "  [WARN] Non-link item exists at $LinkPath — skipping (use -Replace to back up and link)"
            return $false
        }
    }

    try {
        if ($Type -eq 'File') {
            New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath -Force | Out-Null
        }
        else {
            try {
                New-Item -ItemType SymbolicLink -Path $LinkPath -Target $TargetPath -Force | Out-Null
            }
            catch {
                Write-Host "  [FALLBACK] Symlink failed, using junction: $LinkPath"
                New-Item -ItemType Junction -Path $LinkPath -Target $TargetPath -Force | Out-Null
            }
        }

        Write-Host "  [OK] $LinkPath -> $TargetPath"
        return $true
    }
    catch {
        Write-Host "  [ERROR] Failed to create link: $LinkPath — $_"
        return $false
    }
}

function Remove-SafeLink([string]$LinkPath) {
    if (-not (Test-SymlinkOrJunction $LinkPath)) { return }

    if ($script:SetupOptions.DryRun) {
        Write-Host "  [DRY RUN] Would remove: $LinkPath"
        return
    }

    (Get-Item $LinkPath -Force).Delete()
    Write-Host "  [REMOVED] $LinkPath"
}

function Test-GalManagedFile([string]$Path) {
    if (-not (Test-Path $Path)) { return $false }
    try {
        $firstLine = Get-Content $Path -Encoding UTF8 -TotalCount 1 -ErrorAction Stop
        return $firstLine -eq $script:SetupContext.GalManagedFileHeader
    }
    catch {
        return $false
    }
}

function Test-GalRepoLink([string]$Path, [string]$TargetFragment = $script:SetupContext.RepoRoot) {
    if (-not (Test-Path $Path)) { return $false }

    $item = Get-Item $Path -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) { return $false }

    $isReparsePoint = ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0
    if (-not $isReparsePoint) { return $false }

    foreach ($target in @($item.Target)) {
        if ([string]::IsNullOrWhiteSpace([string]$target)) { continue }
        if ([string]$target -like "*$TargetFragment*") {
            return $true
        }
    }

    return $false
}

function Test-GalCommandLink([string]$Path) {
    if (-not (Test-Path $Path)) { return $false }

    $item = Get-Item $Path -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) { return $false }

    $isReparsePoint = ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0
    if (-not $isReparsePoint) { return $false }

    foreach ($target in @($item.Target)) {
        if ([string]::IsNullOrWhiteSpace([string]$target)) { continue }
        if ([string]$target -like "*$($script:SetupContext.RepoRoot)*commands*") {
            return $true
        }
    }

    return $false
}

function Test-CommandAvailable([string]$Name) {
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-PathEntries([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) { return @() }
    return @($Value -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
}

function Refresh-ProcessPath {
    $entries = New-Object System.Collections.Generic.List[string]
    $seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($scope in @('Process', 'User', 'Machine')) {
        foreach ($entry in Get-PathEntries ([Environment]::GetEnvironmentVariable('Path', $scope))) {
            if ($seen.Add($entry)) {
                [void]$entries.Add($entry)
            }
        }
    }

    [Environment]::SetEnvironmentVariable('Path', ($entries -join ';'), 'Process')
}

function Test-WingetPackageInstalled([string]$PackageId) {
    if (-not (Test-CommandAvailable 'winget')) { return $false }

    $output = & winget list --id $PackageId -e --accept-source-agreements 2>$null | Out-String
    if ($LASTEXITCODE -ne 0) { return $false }
    return $output -match [regex]::Escape($PackageId)
}

function Ensure-Ripgrep {
    if ($script:SetupOptions.Uninstall) { return }

    Write-Host ''
    Write-Host '=== ripgrep (rg) ==='

    if (Test-CommandAvailable 'rg') {
        Write-Host '  [OK] rg available'
        return
    }

    Refresh-ProcessPath
    if (Test-CommandAvailable 'rg') {
        Write-Host '  [OK] rg available after PATH refresh'
        return
    }

    $packageId = 'BurntSushi.ripgrep.MSVC'
    if (Test-WingetPackageInstalled $packageId) {
        Write-Host '  [WARN] ripgrep appears installed, but the current shell still cannot resolve rg. Open a new terminal and rerun your command.' -ForegroundColor Yellow
        return
    }

    if (-not (Test-CommandAvailable 'winget')) {
        Write-Host '  [WARN] rg not found and winget is unavailable. Install ripgrep manually, then reopen the terminal.' -ForegroundColor Yellow
        return
    }

    if ($script:SetupOptions.DryRun) {
        Write-Host "  [DRY RUN] rg missing. Would ask to install $packageId via winget."
        return
    }

    $answer = Read-Host '  [PROMPT] ripgrep (rg) was not found. Install it now via winget? [Y/n]'
    if ($answer -match '^(n|no)$') {
        Write-Host '  [SKIP] ripgrep installation skipped'
        return
    }

    try {
        & winget install --id $packageId -e --accept-package-agreements --accept-source-agreements
    }
    catch {
        Write-Host "  [WARN] ripgrep installation failed: $_" -ForegroundColor Yellow
        return
    }

    Refresh-ProcessPath
    if (Test-CommandAvailable 'rg') {
        Write-Host '  [OK] ripgrep installed and available'
    }
    else {
        Write-Host '  [WARN] ripgrep was installed, but this shell still cannot resolve rg. Open a new terminal and rerun your command.' -ForegroundColor Yellow
    }
}

function ConvertTo-OrderedMap([object]$InputObject) {
    if ($null -eq $InputObject) { return $null }

    if ($InputObject -is [System.Collections.IDictionary]) {
        $map = [ordered]@{}
        foreach ($key in $InputObject.Keys) {
            $map[$key] = ConvertTo-OrderedMap $InputObject[$key]
        }
        return $map
    }

    if ($InputObject -is [System.Collections.IEnumerable] -and -not ($InputObject -is [string])) {
        $items = [System.Collections.Generic.List[object]]::new()
        foreach ($item in $InputObject) {
            $items.Add((ConvertTo-OrderedMap $item))
        }
        return ,([object[]]$items.ToArray())
    }

    if ($InputObject.PSObject -and $InputObject -isnot [string] -and $InputObject -isnot [ValueType]) {
        $map = [ordered]@{}
        foreach ($property in $InputObject.PSObject.Properties) {
            $map[$property.Name] = ConvertTo-OrderedMap $property.Value
        }
        return $map
    }

    return $InputObject
}

function Merge-OrderedMap([System.Collections.IDictionary]$Base, [System.Collections.IDictionary]$Overlay) {
    foreach ($key in $Overlay.Keys) {
        if (
            $Base.Contains($key) -and
            $Base[$key] -is [System.Collections.IDictionary] -and
            $Overlay[$key] -is [System.Collections.IDictionary]
        ) {
            $Base[$key] = Merge-OrderedMap $Base[$key] $Overlay[$key]
        }
        else {
            $Base[$key] = $Overlay[$key]
        }
    }

    return $Base
}

function Read-JsonOrderedMap([string]$Path) {
    if (-not (Test-Path $Path)) {
        return [ordered]@{}
    }

    $rawJson = Get-Content $Path -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($rawJson)) {
        return [ordered]@{}
    }

    try {
        return ConvertTo-OrderedMap ($rawJson | ConvertFrom-Json)
    }
    catch {
        Write-Host "  [WARN] Could not parse JSON file: $Path" -ForegroundColor Yellow
        return $null
    }
}

function Write-JsonOrderedMap([string]$Path, [System.Collections.IDictionary]$Data) {
    $directory = Split-Path $Path -Parent
    if (-not (Test-Path $directory)) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    $encoding = if ($script:SetupContext -and $script:SetupContext.PSObject.Properties['Utf8NoBom']) {
        $script:SetupContext.Utf8NoBom
    }
    else {
        [System.Text.UTF8Encoding]::new($false)
    }

    [System.IO.File]::WriteAllText($Path, ($Data | ConvertTo-Json -Depth 20), $encoding)
}

function Read-KeyValueEnvFile([string]$Path) {
    $values = [ordered]@{}
    if (-not (Test-Path $Path)) {
        return $values
    }

    foreach ($line in Get-Content $Path -Encoding UTF8) {
        if ($line -match '^\s*#' -or $line -notmatch '=') { continue }

        $parts = $line.Split('=', 2)
        $key = $parts[0].Trim()
        $value = $parts[1].Trim()
        if ([string]::IsNullOrWhiteSpace($key) -or [string]::IsNullOrWhiteSpace($value)) { continue }
        $values[$key] = $value
    }

    return $values
}

function Get-ConfiguredValue([System.Collections.IDictionary]$Values, [string]$Name) {
    if ($Values.Contains($Name) -and -not [string]::IsNullOrWhiteSpace([string]$Values[$Name])) {
        return [string]$Values[$Name]
    }

    $userValue = [Environment]::GetEnvironmentVariable($Name, 'User')
    if (-not [string]::IsNullOrWhiteSpace($userValue)) { return $userValue }

    $processValue = [Environment]::GetEnvironmentVariable($Name, 'Process')
    if (-not [string]::IsNullOrWhiteSpace($processValue)) { return $processValue }

    return $null
}

function Split-ConfigList([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) { return @() }
    return @($Value -split '\s*,\s*' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
}

function Get-DefaultPrimaryRuntime([string[]]$SelectedRuntimes) {
    foreach ($preferred in @('copilot', 'antigravity', 'codex', 'claude', 'opencode', 'gemini')) {
        if ($SelectedRuntimes -contains $preferred) {
            return $preferred
        }
    }

    return $null
}

function Convert-LegacyRuntimeSelection {
    param(
        [string[]]$SelectedRuntimes,
        [string]$PrimaryRuntime
    )

    $migrateGeminiToAntigravity = ($SelectedRuntimes -contains 'gemini') -and -not ($SelectedRuntimes -contains 'antigravity')
    $normalized = [System.Collections.Generic.List[string]]::new()

    foreach ($runtime in @($SelectedRuntimes)) {
        $resolvedRuntime = if ($migrateGeminiToAntigravity -and $runtime -eq 'gemini') { 'antigravity' } else { $runtime }
        if ($resolvedRuntime -notin $script:SetupContext.RuntimeCatalog.Key) { continue }
        if ($normalized -contains $resolvedRuntime) { continue }
        $normalized.Add($resolvedRuntime)
    }

    $resolvedPrimaryRuntime = if ($migrateGeminiToAntigravity -and $PrimaryRuntime -eq 'gemini') {
        'antigravity'
    }
    else {
        $PrimaryRuntime
    }

    if ($normalized -notcontains $resolvedPrimaryRuntime) {
        $resolvedPrimaryRuntime = Get-DefaultPrimaryRuntime -SelectedRuntimes $normalized
    }

    return [pscustomobject]@{
        SelectedRuntimes = @($normalized)
        PrimaryRuntime = $resolvedPrimaryRuntime
        Migrated = $migrateGeminiToAntigravity
    }
}

function ConvertFrom-MultiSelectAnswer([string]$Answer, [int]$MaxIndex) {
    $selected = [System.Collections.Generic.List[int]]::new()
    if ([string]::IsNullOrWhiteSpace($Answer)) {
        return @()
    }

    foreach ($segment in ($Answer -split ',')) {
        $trimmed = $segment.Trim()
        if ([string]::IsNullOrWhiteSpace($trimmed)) { continue }
        $number = 0
        if (-not [int]::TryParse($trimmed, [ref]$number)) {
            throw "Invalid selection '$trimmed'."
        }
        if ($number -lt 1 -or $number -gt $MaxIndex) {
            throw "Selection '$trimmed' is out of range."
        }
        if (-not $selected.Contains($number)) {
            [void]$selected.Add($number)
        }
    }

    return @($selected)
}

function Read-RuntimeSelection([object[]]$Catalog, [string[]]$DefaultSelection, [string]$PromptReason) {
    Write-Host '  [PROMPT] Select the AI runtimes where GAL should install machine-level integration.'
    if (-not [string]::IsNullOrWhiteSpace($PromptReason)) {
        Write-Host ('  [INFO] {0}' -f $PromptReason)
    }
    for ($index = 0; $index -lt $Catalog.Count; $index++) {
        $runtime = $Catalog[$index]
        Write-Host ('    {0}. {1} - {2}' -f ($index + 1), $runtime.Label, $runtime.Description)
    }

    $defaultNumbers = @()
    for ($index = 0; $index -lt $Catalog.Count; $index++) {
        if ($DefaultSelection -contains $Catalog[$index].Key) {
            $defaultNumbers += ($index + 1)
        }
    }

    while ($true) {
        $answer = Read-Host ('  [PROMPT] Enter selection numbers (for example: 1,3) [default: {0}]' -f ($defaultNumbers -join ','))
        if ([string]::IsNullOrWhiteSpace($answer)) {
            return @($DefaultSelection)
        }

        try {
            $selectedIndices = ConvertFrom-MultiSelectAnswer -Answer $answer -MaxIndex $Catalog.Count
            if ($selectedIndices.Count -eq 0) {
                Write-Host '  [WARN] Select at least one runtime.' -ForegroundColor Yellow
                continue
            }

            return @($selectedIndices | ForEach-Object { $Catalog[$_ - 1].Key })
        }
        catch {
            Write-Host ('  [WARN] {0}' -f $_.Exception.Message) -ForegroundColor Yellow
        }
    }
}

function Read-PrimaryRuntime([object[]]$Catalog, [string[]]$SelectedRuntimes, [string]$DefaultPrimaryRuntime) {
    $choices = @($Catalog | Where-Object { $SelectedRuntimes -contains $_.Key })
    Write-Host '  [PROMPT] Choose the primary runtime GAL should treat as your default entry point.'
    Write-Host '  [INFO] The repo remains the single source of truth for agents, skills, and commands; this choice affects defaults and summaries only.'
    for ($index = 0; $index -lt $choices.Count; $index++) {
        $runtime = $choices[$index]
        $marker = if ($runtime.Key -eq $DefaultPrimaryRuntime) { ' (default)' } else { '' }
        Write-Host ('    {0}. {1}{2}' -f ($index + 1), $runtime.Label, $marker)
    }

    $defaultIndex = @($choices.Key).IndexOf($DefaultPrimaryRuntime) + 1
    if ($defaultIndex -le 0) { $defaultIndex = 1 }

    while ($true) {
        $answer = Read-Host ('  [PROMPT] Enter one number [default: {0}]' -f $defaultIndex)
        if ([string]::IsNullOrWhiteSpace($answer)) {
            return $choices[$defaultIndex - 1].Key
        }

        $selectedIndex = 0
        if (-not [int]::TryParse($answer.Trim(), [ref]$selectedIndex)) {
            Write-Host '  [WARN] Enter a valid number.' -ForegroundColor Yellow
            continue
        }
        if ($selectedIndex -lt 1 -or $selectedIndex -gt $choices.Count) {
            Write-Host '  [WARN] Selection is out of range.' -ForegroundColor Yellow
            continue
        }

        return $choices[$selectedIndex - 1].Key
    }
}

function Get-DetectedRuntimeSelection {
    $context = $script:SetupContext
    $detected = [System.Collections.Generic.List[string]]::new()

    $copilotInstalled = (Test-Path $context.CopilotPluginInstallTarget) -or
        (Test-Path (Join-Path $context.CopilotPluginInstallTarget 'copilot-manifest.json')) -or
        (Test-Path $context.GalRootCopilot) -or
        (Get-ChildItem $context.AgentsTarget -Filter '*.agent.md' -File -ErrorAction SilentlyContinue | Where-Object { Test-GalRepoLink $_.FullName } | Select-Object -First 1) -or
        (Get-ChildItem $context.SkillsTarget -Directory -ErrorAction SilentlyContinue | Where-Object { Test-GalRepoLink $_.FullName } | Select-Object -First 1)
    if ($copilotInstalled) { $detected.Add('copilot') }

    $geminiInstalled = (Test-GalRepoLink $context.GalRootGemini) -or
        (Test-GalManagedFile $context.GeminiContextFile) -or
        (Get-ChildItem $context.GeminiCommandsTarget -Filter '*.toml' -File -ErrorAction SilentlyContinue | Where-Object { Test-GalManagedFile $_.FullName } | Select-Object -First 1)
    if ($geminiInstalled) { $detected.Add('gemini') }

    $antigravityInstalled = Test-GalRepoLink $context.GalRootAntigravity
    if ($antigravityInstalled) { $detected.Add('antigravity') }

    $codexInstalled = (Get-ChildItem $context.CodexSkillsTarget -Directory -ErrorAction SilentlyContinue | Where-Object { Test-GalRepoLink $_.FullName } | Select-Object -First 1)
    if ($codexInstalled) { $detected.Add('codex') }

    $openCodeInstalled =
        (Get-ChildItem $context.OpenCodeSkillsTarget -Directory -ErrorAction SilentlyContinue | Where-Object { Test-GalRepoLink $_.FullName } | Select-Object -First 1) -or
        (Get-ChildItem $context.OpenCodeAgentsTarget -Filter '*.md' -File -ErrorAction SilentlyContinue | Where-Object { Test-GalManagedFile $_.FullName } | Select-Object -First 1) -or
        (Get-ChildItem $context.OpenCodeCommandsTarget -Filter '*.md' -File -ErrorAction SilentlyContinue | Where-Object { Test-GalManagedFile $_.FullName } | Select-Object -First 1)
    if ($openCodeInstalled) { $detected.Add('opencode') }

    $claudeInstalled = Test-ClaudeLifecycleState -Context $context
    if ($claudeInstalled) { $detected.Add('claude') }

    return @($detected)
}

function Get-InstallSelectionState {
    $context = $script:SetupContext
    $state = if (Test-Path $context.InstallStateFile) { Read-JsonOrderedMap $context.InstallStateFile } else { $null }
    if ($state -is [System.Collections.IDictionary] -and -not $script:SetupOptions.Reconfigure) {
        $selected = @($state['selectedRuntimes']) | Where-Object { $_ -in $context.RuntimeCatalog.Key }
        $primary = [string]$state['primaryRuntime']
        $normalizedSelection = Convert-LegacyRuntimeSelection -SelectedRuntimes $selected -PrimaryRuntime $primary
        $selected = @($normalizedSelection.SelectedRuntimes)
        $primary = $normalizedSelection.PrimaryRuntime
        if ($selected.Count -gt 0 -and $selected -contains $primary) {
            Write-Host ''
            Write-Host '=== GAL runtime selection ==='
            Write-Host ('  [OK] Using saved install state from {0}' -f $context.InstallStateFile)
            if ($normalizedSelection.Migrated) {
                Write-Host '  [OK] Migrated saved runtime selection: gemini -> antigravity'
            }
            Write-Host ('  [OK] Selected runtimes: {0}' -f ($selected -join ', '))
            Write-Host ('  [OK] Primary runtime: {0}' -f $primary)
            if ($normalizedSelection.Migrated -and -not $script:SetupOptions.DryRun) {
                Write-JsonOrderedMap $context.InstallStateFile ([ordered]@{
                    schemaVersion = 1
                    selectedRuntimes = @($selected)
                    primaryRuntime = $primary
                    installedAt = if ($state.Contains('installedAt')) { $state['installedAt'] } else { (Get-Date -Format 'o') }
                    lastConfiguredAt = (Get-Date -Format 'o')
                })
                Write-Host ('  [OK] Updated install state: {0}' -f $context.InstallStateFile)
            }
            return [pscustomobject]@{
                SelectedRuntimes = $selected
                PrimaryRuntime = $primary
            }
        }
    }

    $detected = Get-DetectedRuntimeSelection
    $defaultSelection = if ($detected.Count -gt 0) { $detected } else { @($context.RuntimeCatalog.Key) }
    $promptReason = if ($detected.Count -gt 0) {
        'Detected a legacy GAL machine install without install-state. Confirm or change the runtime set before continuing.'
    }
    else {
        'First-time GAL install detected. Choose where GAL should install runtime integrations.'
    }

    Write-Host ''
    Write-Host '=== GAL runtime selection ==='
    $selectedRuntimes = Read-RuntimeSelection -Catalog $context.RuntimeCatalog -DefaultSelection $defaultSelection -PromptReason $promptReason
    $defaultPrimaryRuntime = if ($state -is [System.Collections.IDictionary] -and ($selectedRuntimes -contains [string]$state['primaryRuntime'])) {
        [string]$state['primaryRuntime']
    }
    else {
        Get-DefaultPrimaryRuntime -SelectedRuntimes $selectedRuntimes
    }
    $primaryRuntime = Read-PrimaryRuntime -Catalog $context.RuntimeCatalog -SelectedRuntimes $selectedRuntimes -DefaultPrimaryRuntime $defaultPrimaryRuntime

    if (-not $script:SetupOptions.DryRun) {
        Write-JsonOrderedMap $context.InstallStateFile ([ordered]@{
            schemaVersion = 1
            selectedRuntimes = @($selectedRuntimes)
            primaryRuntime = $primaryRuntime
            installedAt = if ($state -is [System.Collections.IDictionary] -and $state.Contains('installedAt')) { $state['installedAt'] } else { (Get-Date -Format 'o') }
            lastConfiguredAt = (Get-Date -Format 'o')
        })
        Write-Host ('  [OK] Saved install state: {0}' -f $context.InstallStateFile)
    }
    else {
        Write-Host ('  [DRY RUN] Would save install state: {0}' -f $context.InstallStateFile)
    }

    return [pscustomobject]@{
        SelectedRuntimes = @($selectedRuntimes)
        PrimaryRuntime = $primaryRuntime
    }
}

function Ensure-SetupDirectories([string[]]$Directories) {
    if ($script:SetupOptions.Uninstall) { return }

    foreach ($dir in ($Directories | Select-Object -Unique)) {
        if ([string]::IsNullOrWhiteSpace($dir) -or (Test-Path $dir)) { continue }

        if ($script:SetupOptions.DryRun) {
            Write-Host "[DRY RUN] Would create directory: $dir"
        }
        else {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
            Write-Host "[OK] Created directory: $dir"
        }
    }
}

function Read-ExecutorRouting {
    $canonicalPath = Join-Path (Get-GalUserHome) '.gal\config\executor-routing.json'
    if (-not (Test-Path $canonicalPath)) {
        return $null
    }

    try {
        $parsed = Get-Content $canonicalPath -Raw -Encoding UTF8 | ConvertFrom-Json
    }
    catch {
        return $null
    }

    $routing = @{}
    foreach ($prop in $parsed.PSObject.Properties) {
        if ($prop.Name.StartsWith('_')) { continue }
        $entry = $prop.Value
        $routing[$prop.Name] = @{
            executor = if ($entry.executor) { [string]$entry.executor } else { $null }
            model    = if ($null -ne $entry.model -and $entry.model -ne '') { [string]$entry.model } else { $null }
        }
    }

    return $routing
}

function Get-PipelinePhaseRole {
    param(
        [Parameter(Mandatory)][string]$Phase
    )

    $map = @{
        'implement' = 'CODER'
        'test'      = 'TESTER'
        'review'    = 'REVIEWER'
        'verify'    = 'VERIFIER'
    }

    return $map[$Phase.ToLower()]
}