#!/usr/bin/env bash

if [[ -n "${GAL_SETUP_COMMON_SH_LOADED:-}" ]]; then
    return 0 2>/dev/null || exit 0
fi
GAL_SETUP_COMMON_SH_LOADED=1

COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "$COMMON_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"

GAL_STATE_ROOT="$HOME/.gal"
GAL_CONFIG_ROOT="$GAL_STATE_ROOT/config"
GAL_STATE_DIRECTORY="$GAL_STATE_ROOT/state"
GAL_PLUGINS_ROOT="$GAL_STATE_ROOT/plugins"
GAL_DATA_ROOT="$GAL_STATE_ROOT/data"
GAL_CACHE_ROOT="$GAL_STATE_ROOT/cache"
GAL_STORE_ROOT="$GAL_STATE_ROOT/store"
GAL_STORE_PLUGINS_ROOT="$GAL_STORE_ROOT/plugins"
GAL_GENERATED_ROOT="$GAL_STATE_ROOT/generated"
GAL_DIST_ROOT="$GAL_STATE_ROOT/dist"
GAL_SOURCE_ROOT="$GAL_STATE_ROOT/source"
GAL_GENERATED_MCP_ROOT="$GAL_GENERATED_ROOT/mcp"
GAL_GENERATED_XMACHINE_ROOT="$GAL_GENERATED_ROOT/xmachine"
GAL_GENERATED_PROVIDERS_ROOT="$GAL_DIST_ROOT/providers"
INSTALL_STATE_FILE="$GAL_STATE_ROOT/install-state.json"
GAL_CONFIG_FILE="$GAL_CONFIG_ROOT/config.json"
GAL_PLUGINS_LOCK_FILE="$GAL_STATE_DIRECTORY/plugins.lock.json"
GAL_XMACHINE_CONFIG_FILE="$GAL_CONFIG_ROOT/xmachine.json"
GAL_GENERATED_MCP_FILE="$GAL_GENERATED_MCP_ROOT/managed.json"
GAL_GENERATED_XMACHINE_FILE="$GAL_GENERATED_XMACHINE_ROOT/managed.json"

COPILOT_ROOT="$HOME/.copilot"
COPILOT_PLUGIN_INSTALL_TARGET="$COPILOT_ROOT/installed-plugins/gal-copilot/gal"
AGENTS_TARGET="$COPILOT_ROOT/agents"
SKILLS_TARGET="$COPILOT_ROOT/skills"

SHARED_AGENTS_ROOT="$HOME/.agents"
SHARED_SKILLS_TARGET="$SHARED_AGENTS_ROOT/skills"

WORKSPACE_AGENTS_ROOT="$REPO_ROOT/.agents"
WORKSPACE_SKILLS_TARGET="$WORKSPACE_AGENTS_ROOT/skills"
WORKSPACE_RULES_TARGET="$WORKSPACE_AGENTS_ROOT/rules"

GEMINI_ROOT="$HOME/.gemini"
GEMINI_SKILLS_TARGET="$GEMINI_ROOT/skills"
GEMINI_COMMANDS_TARGET="$GEMINI_ROOT/commands"
GEMINI_CONTEXT_FILE="$GEMINI_ROOT/gal-context.md"
GEMINI_SETTINGS_FILE="$GEMINI_ROOT/settings.json"

ANTIGRAVITY_ROOT="$GEMINI_ROOT/antigravity-cli"
ANTIGRAVITY_SKILLS_TARGET="$ANTIGRAVITY_ROOT/skills"
ANTIGRAVITY_MCP_FILE="$ANTIGRAVITY_ROOT/mcp_config.json"
AGY_PLUGIN_ARTIFACT_ROOT="$GAL_DIST_ROOT/provider-plugins/agy/gal"
AGY_PLUGIN_INSTALL_TARGET="$HOME/.gemini/antigravity-cli/plugins/gal"

if [[ "${OSTYPE:-}" == darwin* ]]; then
    VSCODE_SETTINGS_FILE="$HOME/Library/Application Support/Code/User/settings.json"
    VSCODE_MCP_FILE="$HOME/Library/Application Support/Code/User/mcp.json"
else
    VSCODE_SETTINGS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/Code/User/settings.json"
    VSCODE_MCP_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/Code/User/mcp.json"
fi

COPILOT_CLI_MCP_FILE="$COPILOT_ROOT/mcp-config.json"

CODEX_ROOT="$HOME/.codex"
CODEX_SKILLS_TARGET="$CODEX_ROOT/skills"
CODEX_CONFIG_FILE="$HOME/.codex/config.toml"

CLAUDE_ROOT="$HOME/.claude"
CLAUDE_SKILLS_ROOT="$CLAUDE_ROOT/skills"
CLAUDE_PLUGINS_ROOT="$CLAUDE_ROOT/plugins"
CLAUDE_PLUGIN_INSTALL_TARGET="$CLAUDE_SKILLS_ROOT/gal"
CLAUDE_LEGACY_PLUGIN_INSTALL_TARGET="$CLAUDE_PLUGINS_ROOT/gal"

OPENCODE_ROOT="$HOME/.config/opencode"
OPENCODE_SKILLS_TARGET="$OPENCODE_ROOT/skills"
OPENCODE_AGENTS_TARGET="$OPENCODE_ROOT/agents"
OPENCODE_COMMANDS_TARGET="$OPENCODE_ROOT/commands"
OPENCODE_CONFIG_FILE="$OPENCODE_ROOT/opencode.json"

MCP_SOURCE_FILE="$REPO_ROOT/mcp.json"
MCP_LOCAL_FILE="$GAL_CONFIG_ROOT/mcp.local.json"

GAL_ROOT_COPILOT="$COPILOT_ROOT/gal"
GAL_ROOT_GEMINI="$GEMINI_ROOT/gal"
GAL_ROOT_ANTIGRAVITY="$ANTIGRAVITY_ROOT/gal"
GAL_MANAGED_FILE_HEADER='# Generated by GAL Setup-Machine. Do not edit manually.'

get_gal_plugin_root() {
    local plugin_id="${1:-gal}"
    printf '%s\n' "$GAL_PLUGINS_ROOT/$plugin_id"
}

get_gal_plugin_data_root() {
    local plugin_id="${1:-gal}"
    printf '%s\n' "$GAL_DATA_ROOT/$plugin_id"
}

XMACHINE_CONFIG_USED_LEGACY=0

resolve_xmachine_config_path() {
    local repo_root="$1"
    local warn_mode="${2:-}"
    local canonical_path="$GAL_XMACHINE_CONFIG_FILE"
    local legacy_path="$repo_root/xmachine.config.json"

    XMACHINE_CONFIG_USED_LEGACY=0
    if [[ -f "$canonical_path" ]]; then
        printf '%s\n' "$canonical_path"
        return 0
    fi

    if [[ -f "$legacy_path" ]]; then
        XMACHINE_CONFIG_USED_LEGACY=1
        if [[ "$warn_mode" == 'warn' ]]; then
            echo "  [WARN] Using legacy repository-root xmachine config: $legacy_path" >&2
        fi
        printf '%s\n' "$legacy_path"
        return 0
    fi

    printf '%s\n' "$canonical_path"
}

RUNTIME_KEYS=(copilot antigravity gemini codex opencode claude)
RUNTIME_LABELS=("GitHub Copilot" "Antigravity CLI" "Gemini CLI" "Codex CLI" "OpenCode" "Claude Code")
RUNTIME_DESCRIPTIONS=(
    "shared Copilot agents, skills, GAL commands, VS Code settings bridge, VS Code MCP bridge, Copilot CLI MCP bridge"
    "Antigravity global skills, Antigravity MCP bridge, and Antigravity GAL_ROOT link"
    "legacy native command files plus GAL context/settings compatibility bridge"
    "installed GAL command skills, shared skills, Codex MCP bridge"
    "OpenCode agents, commands, reusable skill discovery, OpenCode MCP bridge"
    "Claude plugin lifecycle state, optional Claude CLI MCP bridge, repo-local CLAUDE.md adapter"
)
get_claude_lifecycle_state_path() {
    printf '%s\n' "$GAL_GENERATED_PROVIDERS_ROOT/claude/managed.json"
}

has_claude_lifecycle_state() {
    local state_path
    state_path="$(get_claude_lifecycle_state_path)"
    [ -f "$state_path" ] || return 1

    if ! resolve_python_command; then
        return 0
    fi

    run_python - "$state_path" <<'PY'
import json
import sys

with open(sys.argv[1], encoding='utf-8') as handle:
    data = json.load(handle)

provider = str(data.get('provider') or '').strip()
if provider and provider != 'claude':
    raise SystemExit(1)

raise SystemExit(0)
PY
}


COMMAND_ALIAS_NAMES=()
COMMAND_SKILL_NAMES=()

UNINSTALL=false
PURGE=false
CONFIRM_PURGE=false
REPLACE=false
DRY_RUN=false
RECONFIGURE=false
SELECTED_RUNTIMES_CSV=""
PRIMARY_RUNTIME=""

INSTALL_COPILOT=false
INSTALL_GEMINI=false
INSTALL_ANTIGRAVITY=false
INSTALL_CODEX=false
INSTALL_OPENCODE=false
INSTALL_CLAUDE=false
INSTALL_SHARED_SKILLS=false
INSTALL_GOOGLE_WORKSPACE_SKILLS=false
NEEDS_BAKED_COMMAND_SKILLS=false

get_gal_active_provider_target() {
    local provider="$1"
    printf '%s\n' "$HOME/.gal/active/$provider"
}

gal_root_is_usable() {
    local root="$1"
    [ -n "$root" ] && [ -d "$root" ] && [ -d "$root/commands" ] && [ -d "$root/scripts" ] && [ -d "$root/skills" ] && [ -d "$root/agent" ] && [ -d "$root/templates" ]
}

resolve_install_mode() {
    local dev_mode="$1"
    local gal_root="$2"

    if [ "$dev_mode" = true ] && gal_root_is_usable "$gal_root"; then
        printf 'source\n'
    else
        printf 'install\n'
    fi
}

get_configured_install_mode() {
    if [ ! -f "$GAL_CONFIG_FILE" ]; then
        case "${GAL_BOOTSTRAP_INSTALL:-}" in
            1|true|TRUE|True)
                printf 'install\n'
                return 0
                ;;
        esac

        printf 'source\n'
        return 0
    fi

    run_python - "$GAL_CONFIG_FILE" <<'PY'
import json
import sys

with open(sys.argv[1], encoding='utf-8') as handle:
    data = json.load(handle)

if 'devMode' in data or 'galRoot' in data:
    dev_mode = bool(data.get('devMode', False))
    gal_root = str(data.get('galRoot') or '').strip()
    print('source' if dev_mode and gal_root and any([__import__('os').path.isdir(gal_root), __import__('os').path.isdir(gal_root + '/commands'), __import__('os').path.isdir(gal_root + '/scripts'), __import__('os').path.isdir(gal_root + '/skills'), __import__('os').path.isdir(gal_root + '/agent'), __import__('os').path.isdir(gal_root + '/templates')]) else 'install')
    raise SystemExit(0)

mode = str(data.get('installMode') or 'source').strip()
print(mode or 'source')
PY
}

is_install_mode() {
    [ "$(get_configured_install_mode)" = 'install' ]
}

join_by() {
    local delimiter="$1"
    shift || true

    local item
    local output=""
    local first=true
    for item in "$@"; do
        if $first; then
            output="$item"
            first=false
        else
            output+="$delimiter$item"
        fi
    done

    printf '%s' "$output"
}

format_runtime_csv() {
    local csv="$1"
    if [ -z "$csv" ]; then
        printf '%s' ''
        return 0
    fi

    printf '%s' "${csv//,/ , }"
}

contains_value() {
    local needle="$1"
    shift || true

    local item
    for item in "$@"; do
        [ "$item" = "$needle" ] && return 0
    done

    return 1
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

PYTHON_CMD=''
PYTHON_MODE=''

resolve_python_command() {
    if [ -n "$PYTHON_CMD" ]; then
        return 0
    fi

    if command_exists python3 && python3 -c 'import sys' >/dev/null 2>&1; then
        PYTHON_CMD='python3'
        PYTHON_MODE='direct'
        return 0
    fi

    if command_exists python && python -c 'import sys' >/dev/null 2>&1; then
        PYTHON_CMD='python'
        PYTHON_MODE='direct'
        return 0
    fi

    if command_exists py && py -3 -c 'import sys' >/dev/null 2>&1; then
        PYTHON_CMD='py'
        PYTHON_MODE='launcher'
        return 0
    fi

    PYTHON_CMD=''
    PYTHON_MODE=''
    return 1
}

run_python() {
    if ! resolve_python_command; then
        return 1
    fi

    if [ "$PYTHON_MODE" = 'launcher' ]; then
        "$PYTHON_CMD" -3 "$@"
        return $?
    fi

    "$PYTHON_CMD" "$@"
}

parse_setup_args() {
    BOOTSTRAP_INSTALL=false
    UNINSTALL=false
    PURGE=false
    CONFIRM_PURGE=false
    REPLACE=false
    DRY_RUN=false
    CHECK_ONLY=false
    RECONFIGURE=false
    SELECTED_RUNTIMES_CSV=""
    PRIMARY_RUNTIME=""

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --uninstall) UNINSTALL=true ;;
            --purge) PURGE=true ;;
            --confirm-purge) CONFIRM_PURGE=true ;;
            --bootstrap-install) BOOTSTRAP_INSTALL=true ;;
            --replace) REPLACE=true ;;
            --dry-run) DRY_RUN=true ;;
            --check|--doctor) CHECK_ONLY=true ;;
            --reconfigure) RECONFIGURE=true ;;
            --selected-runtimes)
                shift
                if [ "$#" -eq 0 ]; then
                    echo "Missing value for --selected-runtimes" >&2
                    exit 1
                fi
                SELECTED_RUNTIMES_CSV="$1"
                ;;
            --selected-runtimes=*)
                SELECTED_RUNTIMES_CSV="${1#*=}"
                ;;
            --primary-runtime)
                shift
                if [ "$#" -eq 0 ]; then
                    echo "Missing value for --primary-runtime" >&2
                    exit 1
                fi
                PRIMARY_RUNTIME="$1"
                ;;
            --primary-runtime=*)
                PRIMARY_RUNTIME="${1#*=}"
                ;;
            *)
                echo "Unknown argument: $1" >&2
                exit 1
                ;;
        esac
        shift
    done
}

initialize_command_skill_names() {
    COMMAND_ALIAS_NAMES=()
    while IFS= read -r command_dir; do
        [ -n "$command_dir" ] || continue
        local name
        name="$(basename "$command_dir")"
        [ "$name" = "gal" ] && continue
        [ -f "$command_dir/SKILL.template.md" ] || [ -f "$command_dir/SKILL.md" ] || continue
        COMMAND_ALIAS_NAMES+=("$name")
    done < <(find "$REPO_ROOT/commands" -mindepth 1 -maxdepth 1 -type d -print | LC_ALL=C sort)

    COMMAND_SKILL_NAMES=(gal)
    if [ "${#COMMAND_ALIAS_NAMES[@]}" -gt 0 ]; then
        COMMAND_SKILL_NAMES+=("${COMMAND_ALIAS_NAMES[@]}")
    fi
}

runtime_index() {
    local key="$1"
    local index
    for index in "${!RUNTIME_KEYS[@]}"; do
        if [ "${RUNTIME_KEYS[$index]}" = "$key" ]; then
            printf '%s\n' "$index"
            return 0
        fi
    done

    return 1
}

normalize_runtime_csv() {
    local raw="$1"
    local normalized=()
    local token

    for token in $(printf '%s' "$raw" | tr ',' ' '); do
        if ! contains_value "$token" "${RUNTIME_KEYS[@]}"; then
            continue
        fi
        if contains_value "$token" "${normalized[@]}"; then
            continue
        fi
        normalized+=("$token")
    done

    join_by , "${normalized[@]}"
}

upgrade_legacy_runtime_csv() {
    local raw="$1"
    local tokens=()
    local normalized=()
    local token
    local has_antigravity=false

    for token in $(printf '%s' "$raw" | tr ',' ' '); do
        [ -n "$token" ] || continue
        tokens+=("$token")
        if [ "$token" = 'antigravity' ]; then
            has_antigravity=true
        fi
    done

    for token in "${tokens[@]}"; do
        if [ "$token" = 'gemini' ] && ! $has_antigravity; then
            token='antigravity'
        fi
        if ! contains_value "$token" "${RUNTIME_KEYS[@]}"; then
            continue
        fi
        if contains_value "$token" "${normalized[@]}"; then
            continue
        fi
        normalized+=("$token")
    done

    join_by , "${normalized[@]}"
}

default_primary_runtime() {
    local selected=("$@")
    local preferred
    for preferred in copilot antigravity codex claude opencode gemini; do
        if contains_value "$preferred" "${selected[@]}"; then
            printf '%s\n' "$preferred"
            return 0
        fi
    done

    return 1
}

runtime_selected() {
    local key="$1"
    [[ ",${SELECTED_RUNTIMES_CSV}," == *",${key},"* ]]
}

refresh_install_flags() {
    INSTALL_COPILOT=false
    INSTALL_GEMINI=false
    INSTALL_ANTIGRAVITY=false
    INSTALL_CODEX=false
    INSTALL_OPENCODE=false
    INSTALL_CLAUDE=false
    INSTALL_SHARED_SKILLS=false
    INSTALL_GOOGLE_WORKSPACE_SKILLS=false
    NEEDS_BAKED_COMMAND_SKILLS=false

    if runtime_selected copilot; then INSTALL_COPILOT=true; fi
    if runtime_selected gemini; then INSTALL_GEMINI=true; fi
    if runtime_selected antigravity; then INSTALL_ANTIGRAVITY=true; fi
    if runtime_selected codex; then INSTALL_CODEX=true; fi
    if runtime_selected opencode; then INSTALL_OPENCODE=true; fi
    if runtime_selected claude; then INSTALL_CLAUDE=true; fi
    if $INSTALL_CODEX || $INSTALL_OPENCODE; then INSTALL_SHARED_SKILLS=true; fi
    if $INSTALL_GEMINI || $INSTALL_ANTIGRAVITY; then INSTALL_GOOGLE_WORKSPACE_SKILLS=true; fi
    if $INSTALL_COPILOT || $INSTALL_GEMINI || $INSTALL_ANTIGRAVITY || $INSTALL_CODEX || $INSTALL_OPENCODE || $INSTALL_CLAUDE; then NEEDS_BAKED_COMMAND_SKILLS=true; fi
}

ensure_setup_directories() {
    local dir
    for dir in "$@"; do
        [ -n "$dir" ] || continue
        if [ -d "$dir" ]; then
            continue
        fi
        if $DRY_RUN; then
            echo "[DRY RUN] Would create directory: $dir"
        else
            mkdir -p "$dir"
            echo "[OK] Created directory: $dir"
        fi
    done
}

is_symlink() {
    [ -L "$1" ]
}

safe_link() {
    local link_path="$1"
    local target_path="$2"

    if $DRY_RUN; then
        echo "  [DRY RUN] link: $link_path -> $target_path"
        return 0
    fi

    if is_symlink "$link_path"; then
        local existing
        existing="$(readlink "$link_path")"
        if [ "$existing" = "$target_path" ]; then
            echo "  [SKIP] Already linked: $link_path"
            return 0
        fi
        echo "  [UPDATE] Replacing existing link: $link_path"
        rm "$link_path"
    elif [ -e "$link_path" ]; then
        if $REPLACE; then
            local bak_path="${link_path}.bak"
            if [ -e "$bak_path" ]; then
                echo "  [WARN] Backup already exists at $bak_path — skipping"
                return 1
            fi
            mv "$link_path" "$bak_path"
            echo "  [BACKUP] $link_path -> $bak_path"
        else
            echo "  [WARN] Non-link item exists at $link_path — skipping (use --replace to back up and link)"
            return 1
        fi
    fi

    ln -s "$target_path" "$link_path"
    echo "  [OK] $link_path -> $target_path"
    return 0
}

safe_unlink() {
    local link_path="$1"
    if ! is_symlink "$link_path"; then
        return 0
    fi

    if $DRY_RUN; then
        echo "  [DRY RUN] Would remove: $link_path"
        return 0
    fi

    rm "$link_path"
    echo "  [REMOVED] $link_path"
}

is_gal_managed_file() {
    local path="$1"
    [ -f "$path" ] || return 1

    local first_line
    first_line="$(head -n 1 "$path" 2>/dev/null || true)"
    [ "$first_line" = "$GAL_MANAGED_FILE_HEADER" ]
}

is_gal_repo_link() {
    local path="$1"
    local target_fragment="${2:-$REPO_ROOT}"
    [ -L "$path" ] || return 1

    local target
    target="$(readlink "$path" 2>/dev/null || true)"
    [ -n "$target" ] || return 1

    [[ "$target" == *"$target_fragment"* ]]
}

is_gal_command_link() {
    local path="$1"
    [ -L "$path" ] || return 1

    local target
    target="$(readlink "$path" 2>/dev/null || true)"
    [ -n "$target" ] || return 1

    [[ "$target" == *"$REPO_ROOT"*"/commands/"* ]]
}

has_gal_repo_link_in_dir() {
    local dir="$1"
    [ -d "$dir" ] || return 1

    local path
    while IFS= read -r -d '' path; do
        if is_gal_repo_link "$path"; then
            return 0
        fi
    done < <(find "$dir" -maxdepth 1 -type l -print0 2>/dev/null)

    return 1
}

has_gal_managed_file_in_dir() {
    local dir="$1"
    local pattern="$2"
    [ -d "$dir" ] || return 1

    local path
    while IFS= read -r -d '' path; do
        if is_gal_managed_file "$path"; then
            return 0
        fi
    done < <(find "$dir" -maxdepth 1 -type f -name "$pattern" -print0 2>/dev/null)

    return 1
}

read_install_state_value() {
    local field="$1"
    [ -f "$INSTALL_STATE_FILE" ] || return 1
    resolve_python_command || return 1

    run_python - "$INSTALL_STATE_FILE" "$field" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
field = sys.argv[2]
data = json.loads(path.read_text(encoding='utf-8'))
value = data.get(field)
if isinstance(value, list):
    print(','.join(str(item) for item in value))
elif value is not None:
    print(value)
PY
}

write_install_state() {
    local selected_csv="$1"
    local primary_runtime="$2"
    local installed_at="$3"
    local configured_at="$4"

    if $DRY_RUN; then
        echo "  [DRY RUN] Would save install state: $INSTALL_STATE_FILE"
        return 0
    fi

    mkdir -p "$GAL_STATE_ROOT"
    if resolve_python_command; then
        run_python - "$INSTALL_STATE_FILE" "$selected_csv" "$primary_runtime" "$installed_at" "$configured_at" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
selected = [item for item in sys.argv[2].split(',') if item]
data = {
    'schemaVersion': 1,
    'selectedRuntimes': selected,
    'primaryRuntime': sys.argv[3],
    'installedAt': sys.argv[4],
    'lastConfiguredAt': sys.argv[5],
}
path.write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')
PY
    else
        printf '{\n  "schemaVersion": 1,\n  "selectedRuntimes": ["%s"],\n  "primaryRuntime": "%s",\n  "installedAt": "%s",\n  "lastConfiguredAt": "%s"\n}\n' "${selected_csv//,/\", \"}" "$primary_runtime" "$installed_at" "$configured_at" > "$INSTALL_STATE_FILE"
    fi

    echo "  [OK] Saved install state: $INSTALL_STATE_FILE"
}

detect_installed_runtimes() {
    local detected=()

    if [ -e "$COPILOT_PLUGIN_INSTALL_TARGET" ] || [ -f "$COPILOT_PLUGIN_INSTALL_TARGET/copilot-manifest.json" ] || [ -e "$GAL_ROOT_COPILOT" ] || has_gal_repo_link_in_dir "$AGENTS_TARGET" || has_gal_repo_link_in_dir "$SKILLS_TARGET"; then
        detected+=(copilot)
    fi

    if is_gal_repo_link "$GAL_ROOT_GEMINI" || is_gal_managed_file "$GEMINI_CONTEXT_FILE" || has_gal_managed_file_in_dir "$GEMINI_COMMANDS_TARGET" '*.toml'; then
        detected+=(gemini)
    fi

    if is_gal_repo_link "$GAL_ROOT_ANTIGRAVITY"; then
        detected+=(antigravity)
    fi

    if has_gal_repo_link_in_dir "$CODEX_SKILLS_TARGET"; then
        detected+=(codex)
    fi

    if has_gal_repo_link_in_dir "$OPENCODE_SKILLS_TARGET" || has_gal_managed_file_in_dir "$OPENCODE_AGENTS_TARGET" '*.md' || has_gal_managed_file_in_dir "$OPENCODE_COMMANDS_TARGET" '*.md'; then
        detected+=(opencode)
    fi

    if has_claude_lifecycle_state; then
        detected+=(claude)
    fi

    join_by , "${detected[@]}"
}

parse_selection() {
    local answer="$1"
    local max_index="$2"
    local selected=()

    [ -z "$(printf '%s' "$answer" | xargs || true)" ] && {
        printf '%s\n' ''
        return 0
    }

    local item
    IFS=',' read -r -a parts <<< "$answer"
    for item in "${parts[@]}"; do
        item="$(printf '%s' "$item" | xargs)"
        [ -z "$item" ] && continue
        case "$item" in
            *[!0-9]*)
                echo "Invalid selection '$item'." >&2
                return 1
                ;;
        esac
        if [ "$item" -lt 1 ] || [ "$item" -gt "$max_index" ]; then
            echo "Selection '$item' is out of range." >&2
            return 1
        fi
        if ! contains_value "$item" "${selected[@]}"; then
            selected+=("$item")
        fi
    done

    join_by ' ' "${selected[@]}"
}

read_runtime_selection() {
    local default_selection="$1"
    local prompt_reason="$2"

    echo "  [PROMPT] Select the AI runtimes where GAL should install machine-level integration." >&2
    if [ -n "$prompt_reason" ]; then
        echo "  [INFO] $prompt_reason" >&2
    fi

    local index
    for index in "${!RUNTIME_KEYS[@]}"; do
        printf '    %s. %s - %s\n' "$((index + 1))" "${RUNTIME_LABELS[$index]}" "${RUNTIME_DESCRIPTIONS[$index]}" >&2
    done

    local default_numbers=()
    local runtime
    for runtime in ${default_selection//,/ }; do
        local number
        number="$(runtime_index "$runtime" 2>/dev/null || true)"
        [ -n "$number" ] && default_numbers+=("$((number + 1))")
    done

    while true; do
        local answer parsed
        local result=()
        read -r -p "  [PROMPT] Enter selection numbers (for example: 1,3) [default: $(join_by , "${default_numbers[@]}")]: " answer
        if [ -z "$(printf '%s' "$answer" | xargs || true)" ]; then
            printf '%s\n' "$default_selection"
            return 0
        fi
        if parsed="$(parse_selection "$answer" "${#RUNTIME_KEYS[@]}")"; then
            [ -z "$parsed" ] && {
                echo "  [WARN] Select at least one runtime." >&2
                continue
            }
            for index in $parsed; do
                result+=("${RUNTIME_KEYS[$((index - 1))]}")
            done
            printf '%s\n' "$(normalize_runtime_csv "$(join_by ' ' "${result[@]}")")"
            return 0
        fi
        echo "  [WARN] Invalid selection. Please try again." >&2
    done
}

read_primary_runtime() {
    local selected_csv="$1"
    local default_primary="$2"
    local selected=( ${selected_csv//,/ } )
    local choice_keys=()
    local default_index=1
    local index=1
    local runtime

    echo "  [PROMPT] Choose the primary runtime GAL should treat as your default entry point." >&2
    echo "  [INFO] The repo remains the single source of truth for agents, skills, and commands; this choice affects defaults and summaries only." >&2

    for runtime in "${selected[@]}"; do
        local runtime_pos marker
        runtime_pos="$(runtime_index "$runtime")"
        marker=''
        if [ "$runtime" = "$default_primary" ]; then
            marker=' (default)'
            default_index="$index"
        fi
        printf '    %s. %s%s\n' "$index" "${RUNTIME_LABELS[$runtime_pos]}" "$marker" >&2
        choice_keys+=("$runtime")
        index=$((index + 1))
    done

    while true; do
        local answer
        read -r -p "  [PROMPT] Enter one number [default: $default_index]: " answer
        if [ -z "$(printf '%s' "$answer" | xargs || true)" ]; then
            printf '%s\n' "${choice_keys[$((default_index - 1))]}"
            return 0
        fi
        case "$answer" in
            *[!0-9]*)
                echo "  [WARN] Enter a valid number." >&2
                continue
                ;;
        esac
        if [ "$answer" -lt 1 ] || [ "$answer" -gt "${#choice_keys[@]}" ]; then
            echo "  [WARN] Selection is out of range." >&2
            continue
        fi
        printf '%s\n' "${choice_keys[$((answer - 1))]}"
        return 0
    done
}

resolve_install_selection() {
    if [ -n "$SELECTED_RUNTIMES_CSV" ] && [ -n "$PRIMARY_RUNTIME" ]; then
        SELECTED_RUNTIMES_CSV="$(normalize_runtime_csv "$SELECTED_RUNTIMES_CSV")"
        if [[ ",$SELECTED_RUNTIMES_CSV," != *",$PRIMARY_RUNTIME,"* ]]; then
            PRIMARY_RUNTIME="$(default_primary_runtime ${SELECTED_RUNTIMES_CSV//,/ })"
        fi
        return 0
    fi

    local saved_selected_raw=''
    local saved_selected=''
    local saved_primary=''
    local saved_installed_at=''

    if [ -f "$INSTALL_STATE_FILE" ] && ! $RECONFIGURE; then
        saved_selected_raw="$(read_install_state_value selectedRuntimes 2>/dev/null || true)"
        saved_selected="$(normalize_runtime_csv "$saved_selected_raw")"
        local migrated_selected
        migrated_selected="$(upgrade_legacy_runtime_csv "$saved_selected")"
        saved_primary="$(read_install_state_value primaryRuntime 2>/dev/null || true)"
        saved_installed_at="$(read_install_state_value installedAt 2>/dev/null || true)"
        if [ "$saved_primary" = 'gemini' ] && [[ ",$saved_selected," != *",antigravity,"* ]] && [[ ",$migrated_selected," == *",antigravity,"* ]]; then
            saved_primary='antigravity'
        fi
        if [ -n "$migrated_selected" ] && [ -n "$saved_primary" ]; then
            echo ''
            echo '=== GAL runtime selection ==='
            echo "  [OK] Using saved install state from $INSTALL_STATE_FILE"
            if [ "$migrated_selected" != "$saved_selected" ]; then
                echo '  [OK] Migrated saved runtime selection: gemini -> antigravity'
            fi
            echo "  [OK] Selected runtimes: $(format_runtime_csv "$migrated_selected")"
            echo "  [OK] Primary runtime: $saved_primary"
            SELECTED_RUNTIMES_CSV="$migrated_selected"
            PRIMARY_RUNTIME="$saved_primary"
            if [ "$migrated_selected" != "$saved_selected_raw" ] || [ "$saved_primary" != "$(read_install_state_value primaryRuntime 2>/dev/null || true)" ]; then
                local configured_at
                configured_at="$saved_installed_at"
                [ -z "$configured_at" ] && configured_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
                write_install_state "$migrated_selected" "$saved_primary" "$configured_at" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            fi
            return 0
        fi
    fi

    local detected_csv default_selection prompt_reason
    detected_csv="$(detect_installed_runtimes)"
    default_selection="$detected_csv"
    prompt_reason='Detected a legacy GAL machine install without install-state. Confirm or change the runtime set before continuing.'

    if [ -z "$default_selection" ]; then
        default_selection="$(join_by , "${RUNTIME_KEYS[@]}")"
        prompt_reason='First-time GAL install detected. Choose where GAL should install runtime integrations.'
    fi

    echo ''
    echo '=== GAL runtime selection ==='
    SELECTED_RUNTIMES_CSV="$(normalize_runtime_csv "$(read_runtime_selection "$default_selection" "$prompt_reason")")"

    local default_primary="$saved_primary"
    if [ -z "$default_primary" ] || [[ ",$SELECTED_RUNTIMES_CSV," != *",$default_primary,"* ]]; then
        default_primary="$(default_primary_runtime ${SELECTED_RUNTIMES_CSV//,/ })"
    fi
    PRIMARY_RUNTIME="$(read_primary_runtime "$SELECTED_RUNTIMES_CSV" "$default_primary")"

    local configured_at installed_at
    configured_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    installed_at="$saved_installed_at"
    [ -z "$installed_at" ] && installed_at="$configured_at"
    write_install_state "$SELECTED_RUNTIMES_CSV" "$PRIMARY_RUNTIME" "$installed_at" "$configured_at"
}

ensure_ripgrep() {
    $UNINSTALL && return 0

    echo ''
    echo '=== ripgrep (rg) ==='

    if command_exists rg; then
        echo '  [OK] rg available'
        return 0
    fi

    if $DRY_RUN; then
        echo '  [DRY RUN] rg missing. Would prompt to install ripgrep if a supported package manager is available.'
        return 0
    fi

    local answer=''
    if [[ "${OSTYPE:-}" == darwin* ]] && command_exists brew; then
        read -r -p '  [PROMPT] ripgrep (rg) was not found. Install it now via Homebrew? [Y/n] ' answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo '  [SKIP] ripgrep installation skipped'; return 0 ;;
        esac
        brew install ripgrep || { echo '  [WARN] ripgrep installation failed'; return 0; }
    elif command_exists apt-get; then
        read -r -p '  [PROMPT] ripgrep (rg) was not found. Install it now via apt-get? [Y/n] ' answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo '  [SKIP] ripgrep installation skipped'; return 0 ;;
        esac
        sudo apt-get update && sudo apt-get install -y ripgrep || { echo '  [WARN] ripgrep installation failed'; return 0; }
    elif command_exists dnf; then
        read -r -p '  [PROMPT] ripgrep (rg) was not found. Install it now via dnf? [Y/n] ' answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo '  [SKIP] ripgrep installation skipped'; return 0 ;;
        esac
        sudo dnf install -y ripgrep || { echo '  [WARN] ripgrep installation failed'; return 0; }
    elif command_exists pacman; then
        read -r -p '  [PROMPT] ripgrep (rg) was not found. Install it now via pacman? [Y/n] ' answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo '  [SKIP] ripgrep installation skipped'; return 0 ;;
        esac
        sudo pacman -Sy --noconfirm ripgrep || { echo '  [WARN] ripgrep installation failed'; return 0; }
    else
        echo '  [WARN] rg not found and no supported package manager was detected. Install ripgrep manually, then reopen the terminal.'
        return 0
    fi

    if command_exists rg; then
        echo '  [OK] ripgrep installed and available'
    else
        echo '  [WARN] ripgrep was installed, but this shell still cannot resolve rg. Open a new terminal and rerun your command.'
    fi
}

initialize_setup_session() {
    initialize_command_skill_names

    if ! $UNINSTALL; then
        resolve_install_selection
    fi

    refresh_install_flags
}