//! Naming gate: scans durable surfaces for naming-authority violations.
//!
//! The authority is `docs/naming.md`. This module enforces two of its rules
//! mechanically:
//!
//! * **Provenance discipline** — plan-task IDs (`T-NN`, `R-NN`, `TP-NN`,
//!   `FU-NN`, `BUG-N`) must not appear in durable artifacts. They are allowed
//!   only under `.dev/**`.
//! * **Retired terms** — phrases listed in the `RETIRED-TERMS` block of
//!   `docs/naming.md` (e.g. `MCP provider`) must not appear in durable artifacts.
//!
//! A *durable surface* is every tracked file except `.dev/**`. The two naming
//! **teaching surfaces** — `docs/naming.md` and `conventions/naming.md` — are
//! additionally excluded, because they legitimately name retired terms (and
//! quote plan-ID shapes) in order to define them.
//!
//! The plan-ID regex matches only *numeric* IDs (`[0-9]{2,3}`), so rule-text
//! placeholders such as `T-NN` or `BUG-X` never trip the gate.

use regex::Regex;
use std::fs;
use std::path::Path;
use std::process::Command;

/// Which authority rule a [`Violation`] breaks.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViolationKind {
    /// A plan-task ID (`T-NN`, `R-NN`, `TP-NN`, `FU-NN`, `BUG-N`) in a durable surface.
    PlanTaskId,
    /// A retired term from the `RETIRED-TERMS` block in a durable surface.
    RetiredTerm,
}

/// One naming-authority violation found by the gate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Violation {
    /// 1-based line number within the scanned content.
    pub line: usize,
    /// Which rule was broken.
    pub kind: ViolationKind,
    /// The exact text that matched.
    pub matched: String,
}

/// Compiled scanner. Build once with [`NamingGate::new`], reuse across files.
pub struct NamingGate {
    plan_id: Regex,
    bug_id: Regex,
    retired: Vec<(String, Regex)>,
}

impl NamingGate {
    /// Build a gate from the retired-term list (see [`parse_retired_terms`]).
    ///
    /// The two static regexes use longest-first alternation (`TP`/`FU` before
    /// `T`) so `TP-001` matches as a single `TP` ID.
    pub fn new(retired_terms: &[String]) -> Result<Self, regex::Error> {
        let plan_id = Regex::new(r"\b(?:TP|FU|T|R)-[0-9]{2,3}\b")?;
        let bug_id = Regex::new(r"\bBUG-[0-9]+\b")?;
        let mut retired = Vec::with_capacity(retired_terms.len());
        for term in retired_terms {
            let pattern = format!(r"(?i)\b{}\b", regex::escape(term));
            retired.push((term.clone(), Regex::new(&pattern)?));
        }
        Ok(Self {
            plan_id,
            bug_id,
            retired,
        })
    }

    /// True when `rel_path` is exempt from scanning.
    ///
    /// `rel_path` is interpreted repo-relative; both `/` and `\` separators are
    /// accepted. Exempt:
    ///
    /// * anything under `.dev/` (provenance home — plans, research, execution prompts);
    /// * the naming **definition sites**, which necessarily name the forbidden
    ///   tokens in order to define or detect them: `docs/naming.md` (authority),
    ///   its translations (`docs/i18n/<lang>/naming.<lang>.md`),
    ///   `conventions/naming.md` (agent digest), and `naming_gate.rs` (this
    ///   module — its regexes and tests embed sample IDs and retired terms);
    /// * derived carriers that cannot be hand-fixed: `*.private.md`, baked
    ///   `commands/<name>/SKILL.md`, and the generated repo adapters
    ///   (`CLAUDE.md`/`AGENTS.md`/`GEMINI.md`/`.github/copilot-instructions.md`/
    ///   `.agents/rules/gal.md`), which are regenerated from the excluded
    ///   `.dev/project.md`.
    pub fn is_excluded(rel_path: &str) -> bool {
        let norm = rel_path.replace('\\', "/");
        let trimmed = norm.trim_start_matches("./");
        // A naming-authority translation: docs/i18n/<lang>/naming.<lang>.md.
        let is_naming_translation = trimmed.contains("/i18n/")
            && trimmed
                .rsplit('/')
                .next()
                .map(|name| name.starts_with("naming."))
                .unwrap_or(false);
        // Gitignored, non-durable surfaces the tree walk would otherwise reach:
        //  * `*.private.md` — machine-local private notes (never a shared surface);
        //  * baked `commands/<name>/SKILL.md` — a derived product; its source is the
        //    sibling `SKILL.template.md` (which IS scanned), so gating the derived
        //    copy would double-flag and break on rebake drift.
        let is_private_note = trimmed.ends_with(".private.md");
        let is_baked_command_skill =
            trimmed.contains("/commands/") && trimmed.ends_with("/SKILL.md");
        //  * generated repo adapters (CLAUDE.md / AGENTS.md / GEMINI.md /
        //    .github/copilot-instructions.md / .agents/rules/gal.md) — derived
        //    carriers regenerated by `gal sync`/`gal init` from `.dev/project.md`
        //    (itself excluded and legitimately recording plan-task IDs in its
        //    Verified Facts). They cannot be hand-fixed, so gating them would be
        //    unenforceable; the source `.dev/` surface is the right place to scan.
        // Anchored to the repo-root paths `gal sync`/`gal init` actually writes —
        // not a bare basename match, so a hand-authored source doc that happens to
        // be named e.g. `AGENTS.md` in a subdirectory is still scanned.
        let is_generated_adapter = matches!(
            trimmed,
            "CLAUDE.md"
                | "AGENTS.md"
                | "GEMINI.md"
                | ".github/copilot-instructions.md"
                | ".agents/rules/gal.md"
        );
        trimmed == ".dev"
            || trimmed.starts_with(".dev/")
            || trimmed.contains("/.dev/")
            || trimmed.ends_with("docs/naming.md")
            || trimmed == "docs/naming.md"
            || trimmed.ends_with("conventions/naming.md")
            || trimmed.ends_with("naming_gate.rs")
            || is_naming_translation
            || is_private_note
            || is_baked_command_skill
            || is_generated_adapter
    }

    /// Scan raw `content`, returning every violation in line order.
    ///
    /// Pure: no path filtering. Use [`scan_file`](Self::scan_file) to honor
    /// exclusions.
    pub fn scan_content(&self, content: &str) -> Vec<Violation> {
        let mut out = Vec::new();
        for (idx, line) in content.lines().enumerate() {
            let line_no = idx + 1;
            // Collect this line's matches with their column so the report is
            // ordered by textual position, regardless of which regex found them.
            let mut hits: Vec<(usize, ViolationKind, String)> = Vec::new();
            for m in self.plan_id.find_iter(line) {
                hits.push((m.start(), ViolationKind::PlanTaskId, m.as_str().to_string()));
            }
            for m in self.bug_id.find_iter(line) {
                hits.push((m.start(), ViolationKind::PlanTaskId, m.as_str().to_string()));
            }
            for (_term, re) in &self.retired {
                for m in re.find_iter(line) {
                    hits.push((
                        m.start(),
                        ViolationKind::RetiredTerm,
                        m.as_str().to_string(),
                    ));
                }
            }
            hits.sort_by_key(|(start, _, _)| *start);
            for (_, kind, matched) in hits {
                out.push(Violation {
                    line: line_no,
                    kind,
                    matched,
                });
            }
        }
        out
    }

    /// Scan `content` for `rel_path`, returning no violations when the path is
    /// excluded.
    pub fn scan_file(&self, rel_path: &str, content: &str) -> Vec<Violation> {
        if Self::is_excluded(rel_path) {
            return Vec::new();
        }
        self.scan_content(content)
    }

    /// Scan every git-tracked file under `root`, skipping excluded paths.
    /// Returns only files with hits, each path repo-relative with `/`
    /// separators.
    ///
    /// The inventory is git-proven (`git -C <root> ls-files -z`), not a
    /// filesystem walk: a nested checkout's files are never tracked by this
    /// repo, so they never appear in the listing without any directory-skip
    /// logic. Fails closed — every inventory, path-decoding, and tracked-file
    /// read/decode error aborts the whole scan with `Err` instead of reporting
    /// a partial or empty "clean" result.
    pub fn scan_tree(&self, root: &Path) -> Result<Vec<FileViolations>, String> {
        let output = Command::new("git")
            .arg("-C")
            .arg(root)
            .arg("ls-files")
            .arg("-z")
            .output()
            .map_err(|e| format!("git ls-files failed to spawn: {e}"))?;
        if !output.status.success() {
            return Err(format!(
                "git ls-files exited with {}: {}",
                output.status,
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        let mut out = Vec::new();
        for rel_bytes in output.stdout.split(|&b| b == 0) {
            if rel_bytes.is_empty() {
                continue;
            }
            let rel_str = std::str::from_utf8(rel_bytes)
                .map_err(|e| format!("invalid UTF-8 path from git ls-files: {e}"))?;
            let rel_norm = rel_str.replace('\\', "/");
            if Self::is_excluded(&rel_norm) {
                continue;
            }
            let content = fs::read_to_string(root.join(rel_str))
                .map_err(|e| format!("tracked-file read failed for {rel_norm}: {e}"))?;
            let violations = self.scan_content(&content);
            if !violations.is_empty() {
                out.push(FileViolations {
                    path: rel_norm,
                    violations,
                });
            }
        }
        Ok(out)
    }
}

/// A scanned file and the violations found in it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileViolations {
    /// Repo-relative path with `/` separators.
    pub path: String,
    /// Violations in this file, in line/column order.
    pub violations: Vec<Violation>,
}

/// Load retired terms from `<root>/docs/naming.md`. Empty if the file is absent.
pub fn load_retired_terms(root: &Path) -> Vec<String> {
    match fs::read_to_string(root.join("docs").join("naming.md")) {
        Ok(content) => parse_retired_terms(&content),
        Err(_) => Vec::new(),
    }
}

/// Extract retired phrases from the `RETIRED-TERMS` block of `docs/naming.md`.
///
/// Reads only the lines between the `# RETIRED-TERMS:BEGIN` and
/// `# RETIRED-TERMS:END` fences; comment lines (`#`) and blanks are ignored.
/// A missing block yields an empty list.
pub fn parse_retired_terms(naming_md: &str) -> Vec<String> {
    let mut terms = Vec::new();
    let mut inside = false;
    for line in naming_md.lines() {
        let trimmed = line.trim();
        if trimmed == "# RETIRED-TERMS:BEGIN" {
            inside = true;
            continue;
        }
        if trimmed == "# RETIRED-TERMS:END" {
            break;
        }
        if inside && !trimmed.is_empty() && !trimmed.starts_with('#') {
            terms.push(trimmed.to_string());
        }
    }
    terms
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gate() -> NamingGate {
        NamingGate::new(&["MCP provider".to_string()]).expect("gate compiles")
    }

    #[test]
    fn parses_retired_terms_block() {
        let md = "intro\n\
                  ```text\n\
                  # RETIRED-TERMS v1 — header comment\n\
                  # RETIRED-TERMS:BEGIN\n\
                  MCP provider\n\
                  # RETIRED-TERMS:END\n\
                  ```\n\
                  trailing\n";
        assert_eq!(parse_retired_terms(md), vec!["MCP provider".to_string()]);
    }

    #[test]
    fn missing_block_yields_empty() {
        assert!(parse_retired_terms("no fences here\nMCP provider\n").is_empty());
    }

    #[test]
    fn flags_plan_ids_and_retired_terms() {
        let content = "fix per T-001 and R-12\n\
                       see the MCP provider config\n\
                       tracked as BUG-7 / TP-014\n";
        let v = gate().scan_content(content);
        let ids: Vec<&str> = v
            .iter()
            .filter(|x| x.kind == ViolationKind::PlanTaskId)
            .map(|x| x.matched.as_str())
            .collect();
        assert_eq!(ids, vec!["T-001", "R-12", "BUG-7", "TP-014"]);
        let retired: Vec<&str> = v
            .iter()
            .filter(|x| x.kind == ViolationKind::RetiredTerm)
            .map(|x| x.matched.as_str())
            .collect();
        assert_eq!(retired, vec!["MCP provider"]);
        // line numbers are 1-based and correct.
        assert_eq!(v[0].line, 1);
        assert_eq!(
            v.iter()
                .find(|x| x.kind == ViolationKind::RetiredTerm)
                .unwrap()
                .line,
            2
        );
    }

    #[test]
    fn retired_term_is_case_insensitive() {
        let v = gate().scan_content("the mcp PROVIDER role");
        assert_eq!(v.len(), 1);
        assert_eq!(v[0].kind, ViolationKind::RetiredTerm);
    }

    #[test]
    fn tp_matches_as_single_id() {
        let v = gate().scan_content("TP-001");
        let ids: Vec<&str> = v.iter().map(|x| x.matched.as_str()).collect();
        assert_eq!(ids, vec!["TP-001"]);
    }

    #[test]
    fn false_positive_corpus_is_clean() {
        let corpus = "a T-shirt and an x-ray, UTF-8 encoded, RFC 430, vitamin B-12\n\
                      placeholders T-NN R-NN TP-NN FU-NN BUG-X stay clean\n\
                      DEBUG-12 is not a bug id, year T-2024 is too long\n\
                      the MCP host consumes an MCP server\n";
        assert!(
            gate().scan_content(corpus).is_empty(),
            "unexpected violations: {:?}",
            gate().scan_content(corpus)
        );
    }

    #[test]
    fn excluded_paths_are_skipped() {
        let content = "leaked T-001 and MCP provider";
        assert!(gate().scan_file(".dev/plans/foo.md", content).is_empty());
        assert!(gate().scan_file(".dev/state.md", content).is_empty());
        assert!(gate()
            .scan_file(".dev/plans/x.prompt.md", content)
            .is_empty());
        assert!(gate().scan_file("docs/naming.md", content).is_empty());
        assert!(gate()
            .scan_file("plugins/gal-core/conventions/naming.md", content)
            .is_empty());
        // the gate's own source is a definition site (it embeds sample IDs/terms).
        assert!(gate()
            .scan_file("crates/gal-engine/src/naming_gate.rs", content)
            .is_empty());
        // naming-authority translations are definition sites too.
        assert!(gate()
            .scan_file("docs/i18n/zh-Hant/naming.zh-Hant.md", content)
            .is_empty());
        // backslash separators (Windows) are normalized.
        assert!(gate().scan_file(".dev\\plans\\foo.md", content).is_empty());
        // baked command skills are derived; the source SKILL.template.md is scanned.
        assert!(gate()
            .scan_file("plugins/gal-core/commands/gal/SKILL.md", content)
            .is_empty());
        // generated repo adapters are derived carriers (regenerated from .dev/project.md,
        // which legitimately records plan-task IDs) — not hand-fixable, so excluded.
        for adapter in [
            "CLAUDE.md",
            "AGENTS.md",
            "GEMINI.md",
            ".github/copilot-instructions.md",
            ".agents/rules/gal.md",
        ] {
            assert!(
                gate().scan_file(adapter, content).is_empty(),
                "generated adapter should be excluded: {adapter}"
            );
        }
        // but a real source doc with the same leak is still scanned.
        assert!(!gate().scan_file("docs/devguide.md", content).is_empty());
        // adapter exclusion is root-anchored: a same-named source doc in a subdir is NOT excluded.
        assert!(!gate().scan_file("docs/AGENTS.md", content).is_empty());
    }

    #[test]
    fn command_skill_template_and_skills_dir_stay_scanned() {
        let content = "leaked T-001 here";
        // The SKILL.template.md source IS a durable surface.
        assert_eq!(
            gate()
                .scan_file("plugins/gal-core/commands/gal/SKILL.template.md", content)
                .len(),
            1
        );
        // skills/<name>/SKILL.md are source contracts, not baked — still scanned.
        assert_eq!(
            gate()
                .scan_file("plugins/gal-core/skills/doc-sync/SKILL.md", content)
                .len(),
            1
        );
    }

    #[test]
    fn durable_surface_is_scanned() {
        let content = "leaked T-001 here";
        let v = gate().scan_file("crates/base/src/lib.rs", content);
        assert_eq!(v.len(), 1);
        assert_eq!(v[0].kind, ViolationKind::PlanTaskId);
    }

    /// A temp git repo (`git init`), with `write_tracked` staging files via
    /// `git add` so [`NamingGate::scan_tree`] sees them in `git ls-files`.
    struct TempRepo {
        dir: tempfile::TempDir,
    }

    impl TempRepo {
        fn new() -> Self {
            let dir = tempfile::tempdir().expect("tempdir");
            let status = Command::new("git")
                .arg("-C")
                .arg(dir.path())
                .arg("init")
                .arg("--quiet")
                .status()
                .expect("git init spawns");
            assert!(status.success(), "git init must succeed");
            Self { dir }
        }

        fn root(&self) -> &Path {
            self.dir.path()
        }

        /// Write `rel` and `git add` it (tracked/staged, visible to `ls-files`).
        fn write_tracked(&self, rel: &str, body: &str) {
            self.write_untracked(rel, body);
            let status = Command::new("git")
                .arg("-C")
                .arg(self.root())
                .arg("add")
                .arg(rel)
                .status()
                .expect("git add spawns");
            assert!(status.success(), "git add must succeed for {rel}");
        }

        /// Write `rel` to disk without staging it (untracked).
        fn write_untracked(&self, rel: &str, body: &str) {
            let p = self.root().join(rel);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, body).unwrap();
        }
    }

    #[test]
    fn scan_tree_reports_only_durable_hits() {
        let repo = TempRepo::new();
        repo.write_tracked("crates/base/src/lib.rs", "// see T-001\n");
        repo.write_tracked(".dev/plans/x.md", "T-002 here\n"); // excluded dir (.dev/)
        repo.write_tracked("docs/naming.md", "MCP provider definition\n"); // excluded definition site
        repo.write_tracked("README.md", "clean doc, no ids\n"); // durable, clean

        let hits = gate().scan_tree(repo.root()).expect("scan succeeds");
        assert_eq!(hits.len(), 1, "unexpected: {hits:?}");
        assert_eq!(hits[0].path, "crates/base/src/lib.rs");
        assert_eq!(hits[0].violations[0].matched, "T-001");
    }

    #[test]
    fn scan_tree_ignores_untracked_files() {
        // An untracked file naming a retired term must never be reported —
        // only git-proven (tracked/staged) content is in scope.
        let repo = TempRepo::new();
        repo.write_tracked("crates/base/src/lib.rs", "clean, no ids\n");
        repo.write_untracked("scratch/leak.md", "T-999 and MCP provider\n");

        let hits = gate().scan_tree(repo.root()).expect("scan succeeds");
        assert!(hits.is_empty(), "untracked file must be ignored: {hits:?}");
    }

    #[test]
    fn scan_tree_fails_closed_outside_git_repo() {
        // No `git init` here: not a git repository at all.
        let tmp = tempfile::tempdir().expect("tempdir");
        let result = gate().scan_tree(tmp.path());
        assert!(
            result.is_err(),
            "scan outside a git repo must fail closed, not report empty-clean"
        );
    }
}
