#!/usr/bin/env bash
# setup-machine.sh — Create symlinks from golem-agents-legion to Copilot, Gemini, Codex, and Claude runtimes
#
# Links:
#   agent/*.agent.md  -> ~/.copilot/agents/*.agent.md
#   skills/*/         -> ~/.copilot/skills/*/
#   skills/*/         -> ~/.agents/skills/*/ (shared reusable skills for Gemini CLI + Codex CLI)
#   skills/*/         -> ~/.claude/skills/*/
#   commands/*/       -> ~/.copilot/skills/*/ + ~/.codex/skills/*/ (baked command skills)
#   commands/*/       -> ~/.gemini/commands/*.toml + ~/.claude/commands/*.md
#   <repo root>       -> ~/.copilot/gal/ + ~/.gemini/gal/ (GAL_ROOT dir symlinks)
#   Generates commands/*/SKILL.md from SKILL.template.md (baked absolute paths) plus optional gitignored SKILL.local.md overlays
#   Generates ~/.gemini/commands/*.toml so Gemini CLI can expose GAL commands natively
#   Generates ~/.claude/commands/*.md so Claude Code can expose GAL commands natively
#   Generates ~/.gemini/gal-context.md (@file skill imports, paths reference .agents/skills)
#   Persists machine-local runtime selection in ~/.gal/install-state.json
#   Merges VS Code user settings so Copilot Chat ignores ~/.agents/skills and does not double-list skills
#   Merges MCP server config from mcp-servers.example.json + mcp-servers.local.json into VS Code, Gemini, and Codex user config files
#
# Usage:
#   ./scripts/setup-machine.sh              # Install symlinks
#   ./scripts/setup-machine.sh --replace    # Replace existing real dirs with symlinks
#   ./scripts/setup-machine.sh --reconfigure # Prompt again for runtimes and primary runtime
#   ./scripts/setup-machine.sh --uninstall   # Remove symlinks
#   ./scripts/setup-machine.sh --dry-run     # Preview only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GAL_STATE_ROOT="$HOME/.gal"
INSTALL_STATE_FILE="$GAL_STATE_ROOT/install-state.json"

COPILOT_ROOT="$HOME/.copilot"
AGENTS_TARGET="$COPILOT_ROOT/agents"
SKILLS_TARGET="$COPILOT_ROOT/skills"

GEMINI_ROOT="$HOME/.gemini"
GEMINI_SKILLS_TARGET="$GEMINI_ROOT/skills"
GEMINI_CONTEXT_FILE="$GEMINI_ROOT/gal-context.md"
GAL_MANAGED_GEMINI_COMMAND_HEADER='# Generated by GAL Setup-Machine. Do not edit manually.'

if [[ "${OSTYPE:-}" == darwin* ]]; then
    VSCODE_SETTINGS_FILE="$HOME/Library/Application Support/Code/User/settings.json"
    VSCODE_MCP_FILE="$HOME/Library/Application Support/Code/User/mcp.json"
else
    VSCODE_SETTINGS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/Code/User/settings.json"
    VSCODE_MCP_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/Code/User/mcp.json"
fi

SHARED_AGENTS_ROOT="$HOME/.agents"
SHARED_SKILLS_TARGET="$SHARED_AGENTS_ROOT/skills"

GEMINI_COMMANDS_TARGET="$GEMINI_ROOT/commands"

CODEX_ROOT="$HOME/.codex"
CODEX_SKILLS_TARGET="$CODEX_ROOT/skills"
CODEX_CONFIG_FILE="$HOME/.codex/config.toml"

CLAUDE_ROOT="$HOME/.claude"
CLAUDE_SKILLS_TARGET="$CLAUDE_ROOT/skills"
CLAUDE_COMMANDS_TARGET="$CLAUDE_ROOT/commands"

MCP_MANIFEST_EXAMPLE="$REPO_ROOT/mcp-servers.example.json"
MCP_MANIFEST_LOCAL="$REPO_ROOT/mcp-servers.local.json"

GAL_SOURCE="$REPO_ROOT/commands/gal"
GAL_ROOT_COPILOT="$COPILOT_ROOT/gal"
GAL_ROOT_GEMINI="$GEMINI_ROOT/gal"
GAL_SKILL_COPILOT="$SKILLS_TARGET/gal"
GAL_SKILL_CODEX="$CODEX_SKILLS_TARGET/gal"
SKILL_TEMPLATE="$GAL_SOURCE/SKILL.template.md"
RUNTIME_KEYS=(copilot gemini codex claude)
RUNTIME_LABELS=("VS Code Copilot" "Gemini CLI" "Codex CLI" "Claude Code")
RUNTIME_DESCRIPTIONS=(
    "agents, skills, GAL commands, VS Code settings bridge, VS Code MCP bridge"
    "native command files, GAL context, shared skills, Gemini MCP bridge"
    "installed GAL command skills, shared skills, Codex MCP bridge"
    "Claude skills, native command files, repo-local CLAUDE.md adapter"
)
COMMAND_ALIAS_NAMES=()
while IFS= read -r -d '' _d; do
    _name="$(basename "$_d")"
    [ "$_name" = "gal" ] && continue
    [ -f "$_d/SKILL.template.md" ] || [ -f "$_d/SKILL.md" ] || continue
    COMMAND_ALIAS_NAMES+=("$_name")
done < <(find "$REPO_ROOT/commands" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

COMMAND_SKILL_NAMES=(gal "${COMMAND_ALIAS_NAMES[@]}")

UNINSTALL=false
REPLACE=false
DRY_RUN=false
RECONFIGURE=false

for arg in "$@"; do
    case "$arg" in
        --uninstall) UNINSTALL=true ;;
        --replace)   REPLACE=true ;;
        --dry-run)   DRY_RUN=true ;;
        --reconfigure) RECONFIGURE=true ;;
        *)           echo "Unknown argument: $arg"; exit 1 ;;
    esac
done

# --- Helpers ---

is_symlink() { [ -L "$1" ]; }

safe_link() {
    local link_path="$1"
    local target_path="$2"

    if $DRY_RUN; then
        echo "  [DRY RUN] link: $link_path -> $target_path"
        return 0
    fi

    if is_symlink "$link_path"; then
        local existing
        existing="$(readlink "$link_path")"
        if [ "$existing" = "$target_path" ]; then
            echo "  [SKIP] Already linked: $link_path"
            return 0
        fi
        echo "  [UPDATE] Replacing existing link: $link_path"
        rm "$link_path"
    elif [ -e "$link_path" ]; then
        if $REPLACE; then
            local bak_path="${link_path}.bak"
            if [ -e "$bak_path" ]; then
                echo "  [WARN] Backup already exists at $bak_path — skipping"
                return 1
            fi
            if $DRY_RUN; then
                echo "  [DRY RUN] Would rename $link_path -> $bak_path, then link"
                return 0
            fi
            mv "$link_path" "$bak_path"
            echo "  [BACKUP] $link_path -> $bak_path"
        else
            echo "  [WARN] Non-link item exists at $link_path — skipping (use --replace to back up and link)"
            return 1
        fi
    fi

    ln -s "$target_path" "$link_path"
    echo "  [OK] $link_path -> $target_path"
    return 0
}

safe_unlink() {
    local link_path="$1"
    if ! is_symlink "$link_path"; then return; fi

    if $DRY_RUN; then
        echo "  [DRY RUN] Would remove: $link_path"
        return
    fi

    rm "$link_path"
    echo "  [REMOVED] $link_path"
}

is_gal_managed_file() {
    local path="$1"
    [ -f "$path" ] || return 1
    local first_line
    first_line="$(head -n 1 "$path" 2>/dev/null || true)"
    [ "$first_line" = "$GAL_MANAGED_GEMINI_COMMAND_HEADER" ]
}

is_gal_repo_link() {
    local path="$1"
    local target_fragment="${2:-$REPO_ROOT}"
    [ -L "$path" ] || return 1

    local target
    target="$(readlink "$path" 2>/dev/null || true)"
    [ -n "$target" ] || return 1

    [[ "$target" == *"$target_fragment"* ]]
}

is_gal_command_link() {
    local path="$1"
    [ -L "$path" ] || return 1

    local target
    target="$(readlink "$path" 2>/dev/null || true)"
    [ -n "$target" ] || return 1

    [[ "$target" == *"$REPO_ROOT"*"/commands/"* ]]
}

get_baked_command_skill_content() {
    local template_path="$1"
    local local_override_path="$2"
    local baked

    baked="$(sed "s|{{GAL_ROOT}}|$REPO_ROOT|g" "$template_path")"

    if [ ! -f "$local_override_path" ] || ! [ -s "$local_override_path" ]; then
        printf '%s\n' "$baked"
        return
    fi

    printf '%s\n\n' "$baked"
    printf '%s\n' '<!-- GAL LOCAL OVERRIDE START -->'
    printf '%s\n' '<!-- Source: SKILL.local.md (gitignored machine-local overlay) -->'
    cat "$local_override_path"
    printf '\n%s\n' '<!-- GAL LOCAL OVERRIDE END -->'
}

get_skill_frontmatter_description() {
    local skill_path="$1"
    local description

    description="$(awk '
        BEGIN { in_frontmatter = 0 }
        NR == 1 {
            if ($0 ~ /^---[[:space:]]*$/) {
                in_frontmatter = 1
                next
            }
        }
        in_frontmatter {
            if ($0 ~ /^---[[:space:]]*$/) {
                exit
            }
            if ($0 ~ /^description:[[:space:]]*/) {
                sub(/^description:[[:space:]]*/, "", $0)
                print $0
                exit
            }
            next
        }
    ' "$skill_path")"

    description="${description#\"}"
    description="${description%\"}"
    printf '%s' "$description"
}

get_skill_markdown_body() {
    local skill_path="$1"

    awk '
        BEGIN { in_frontmatter = 0 }
        NR == 1 {
            if ($0 ~ /^---[[:space:]]*$/) {
                in_frontmatter = 1
                next
            }
        }
        in_frontmatter {
            if ($0 ~ /^---[[:space:]]*$/) {
                in_frontmatter = 0
                next
            }
            next
        }
        { print }
    ' "$skill_path"
}

escape_toml_basic_string() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

toml_multiline_literal_string() {
    printf "'''\n"
    printf '%s' "$1"
    printf "\n'''"
}

new_gemini_command_file_content() {
    local skill_path="$1"
    local description
    local body
    local prompt

    description="$(get_skill_frontmatter_description "$skill_path")"
    if [ -z "$description" ]; then
        description="GAL command"
    fi

    body="$(get_skill_markdown_body "$skill_path")"
    prompt=$(printf 'User command arguments, if any: {{args}}\n\n%s' "$body")

    {
        printf '%s\n' "$GAL_MANAGED_GEMINI_COMMAND_HEADER"
        printf 'description = "%s"\n' "$(escape_toml_basic_string "$description")"
        printf 'prompt = '
        toml_multiline_literal_string "$prompt"
        printf '\n'
    }
}

new_claude_command_file_content() {
    local skill_path="$1"
    local command_name="$2"
    local description
    local body

    description="$(get_skill_frontmatter_description "$skill_path")"
    if [ -z "$description" ]; then
        description="GAL command"
    fi

    body="$(get_skill_markdown_body "$skill_path")"

    {
        printf '%s\n' "$GAL_MANAGED_GEMINI_COMMAND_HEADER"
        printf '%s\n' '---'
        printf '%s\n' 'description: |'
        while IFS= read -r line; do
            printf '  %s\n' "$line"
        done <<< "$description"
        printf '%s\n\n' '---'
        printf '# %s\n\n' "$command_name"
        printf '%s\n\n' 'User command arguments, if any: {{args}}'
        printf '%s\n' "$body"
    }
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

runtime_index() {
    local key="$1"
    local index
    for index in "${!RUNTIME_KEYS[@]}"; do
        if [ "${RUNTIME_KEYS[$index]}" = "$key" ]; then
            printf '%s\n' "$index"
            return 0
        fi
    done

    return 1
}

normalize_runtime_csv() {
    local raw="$1"
    local normalized=()
    local token

    for token in $(printf '%s' "$raw" | tr ',' ' '); do
        case " ${RUNTIME_KEYS[*]-} " in
            *" $token "*)
                case " ${normalized[*]-} " in
                    *" $token "*) ;;
                    *) normalized+=("$token") ;;
                esac
                ;;
        esac
    done

    local joined=""
    for token in "${normalized[@]-}"; do
        if [ -n "$joined" ]; then
            joined+=",$token"
        else
            joined="$token"
        fi
    done

    printf '%s\n' "$joined"
}

default_primary_runtime() {
    local selected=("$@")
    [ "$#" -eq 0 ] && return 1
    local preferred
    for preferred in copilot gemini codex claude; do
        if [[ " ${selected[*]-} " == *" $preferred "* ]]; then
            printf '%s\n' "$preferred"
            return 0
        fi
    done

    return 1
}

read_install_state_value() {
    local field="$1"
    [ -f "$INSTALL_STATE_FILE" ] || return 1
    if command_exists python3; then
        python3 - "$INSTALL_STATE_FILE" "$field" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
field = sys.argv[2]
data = json.loads(path.read_text(encoding='utf-8'))
value = data.get(field)
if isinstance(value, list):
    print(','.join(str(item) for item in value))
elif value is not None:
    print(value)
PY
        return $?
    fi
    return 1
}

write_install_state() {
    local selected_csv="$1"
    local primary_runtime="$2"
    local installed_at="$3"
    local configured_at="$4"

    if $DRY_RUN; then
        echo "  [DRY RUN] Would save install state: $INSTALL_STATE_FILE"
        return 0
    fi

    mkdir -p "$GAL_STATE_ROOT"
    if command_exists python3; then
        python3 - "$INSTALL_STATE_FILE" "$selected_csv" "$primary_runtime" "$installed_at" "$configured_at" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
selected = [item for item in sys.argv[2].split(',') if item]
data = {
    'schemaVersion': 1,
    'selectedRuntimes': selected,
    'primaryRuntime': sys.argv[3],
    'installedAt': sys.argv[4],
    'lastConfiguredAt': sys.argv[5],
}
path.write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')
PY
    else
        printf '{\n  "schemaVersion": 1,\n  "selectedRuntimes": ["%s"],\n  "primaryRuntime": "%s",\n  "installedAt": "%s",\n  "lastConfiguredAt": "%s"\n}\n' "${selected_csv//,/\", \"}" "$primary_runtime" "$installed_at" "$configured_at" > "$INSTALL_STATE_FILE"
    fi
    echo "  [OK] Saved install state: $INSTALL_STATE_FILE"
}

detect_installed_runtimes() {
    local detected=()

    if is_gal_repo_link "$GAL_ROOT_COPILOT" || find "$AGENTS_TARGET" -maxdepth 1 -type l 2>/dev/null | grep -q . || find "$SKILLS_TARGET" -maxdepth 1 -type l 2>/dev/null | grep -q .; then
        detected+=(copilot)
    fi

    if is_gal_repo_link "$GAL_ROOT_GEMINI" || is_gal_managed_file "$GEMINI_CONTEXT_FILE" || find "$GEMINI_COMMANDS_TARGET" -maxdepth 1 -name '*.toml' -type f 2>/dev/null | grep -q .; then
        detected+=(gemini)
    fi

    if find "$CODEX_SKILLS_TARGET" -maxdepth 1 -type l 2>/dev/null | grep -q .; then
        detected+=(codex)
    fi

    if find "$CLAUDE_SKILLS_TARGET" -maxdepth 1 -type l 2>/dev/null | grep -q . || find "$CLAUDE_COMMANDS_TARGET" -maxdepth 1 -name '*.md' -type f 2>/dev/null | grep -q .; then
        detected+=(claude)
    fi

    printf '%s\n' "${detected[*]-}"
}

parse_selection() {
  local answer="$1"
  local max_index="$2"
  local selected=()
  [ -z "$(printf '%s' "$answer" | xargs || true)" ] && { printf '%s\n' ""; return 0; }

  local item number
  IFS=',' read -r -a parts <<< "$answer"
  for item in "${parts[@]}"; do
    item="$(printf '%s' "$item" | xargs)"
    [ -z "$item" ] && continue
    case "$item" in
      *[!0-9]*)
        echo "Invalid selection '$item'." >&2
        return 1
        ;;
    esac
    number="$item"
    if [ "$number" -lt 1 ] || [ "$number" -gt "$max_index" ]; then
      echo "Selection '$item' is out of range." >&2
      return 1
    fi
        case " ${selected[*]-} " in
      *" $number "*) ;;
      *) selected+=("$number") ;;
    esac
  done

    printf '%s\n' "${selected[*]-}"
}

read_runtime_selection() {
    local default_selection="$1"
    local prompt_reason="$2"

    echo "  [PROMPT] Select the AI runtimes where GAL should install machine-level integration." >&2
    if [ -n "$prompt_reason" ]; then
        echo "  [INFO] $prompt_reason" >&2
    fi

    local index
    for index in "${!RUNTIME_KEYS[@]}"; do
        printf '    %s. %s - %s\n' "$((index + 1))" "${RUNTIME_LABELS[$index]}" "${RUNTIME_DESCRIPTIONS[$index]}" >&2
    done

    local default_numbers=()
    local runtime number
    for runtime in ${default_selection//,/ }; do
        number="$(runtime_index "$runtime" 2>/dev/null || true)"
        [ -n "$number" ] && default_numbers+=("$((number + 1))")
    done

    while true; do
        local answer parsed result=()
        read -r -p "  [PROMPT] Enter selection numbers (for example: 1,3) [default: $(IFS=,; echo "${default_numbers[*]-}")]: " answer
        if [ -z "$(printf '%s' "$answer" | xargs || true)" ]; then
            printf '%s\n' "$default_selection"
            return 0
        fi
        if parsed="$(parse_selection "$answer" "${#RUNTIME_KEYS[@]}")"; then
            [ -z "$parsed" ] && { echo "  [WARN] Select at least one runtime." >&2; continue; }
            for index in $parsed; do
                result+=("${RUNTIME_KEYS[$((index - 1))]}")
            done
            printf '%s\n' "$(normalize_runtime_csv "$(IFS=' '; echo "${result[*]-}")")"
            return 0
        fi
        echo "  [WARN] Invalid selection. Please try again." >&2
    done
}

read_primary_runtime() {
    local selected_csv="$1"
    local default_primary="$2"
    local selected=( ${selected_csv//,/ } )
    local choice_keys=()
    local runtime index marker default_index=1

    echo "  [PROMPT] Choose the primary runtime GAL should treat as your default entry point." >&2
    echo "  [INFO] The repo remains the single source of truth for agents, skills, and commands; this choice affects defaults and summaries only." >&2

    index=1
    for runtime in "${selected[@]}"; do
        local runtime_pos
        runtime_pos="$(runtime_index "$runtime")"
        marker=""
        if [ "$runtime" = "$default_primary" ]; then
            marker=" (default)"
            default_index="$index"
        fi
        printf '    %s. %s%s\n' "$index" "${RUNTIME_LABELS[$runtime_pos]}" "$marker" >&2
        choice_keys+=("$runtime")
        index=$((index + 1))
    done

    while true; do
        local answer selected_index
        read -r -p "  [PROMPT] Enter one number [default: $default_index]: " answer
        if [ -z "$(printf '%s' "$answer" | xargs || true)" ]; then
            printf '%s\n' "${choice_keys[$((default_index - 1))]}"
            return 0
        fi
        case "$answer" in
            *[!0-9]*) echo "  [WARN] Enter a valid number." >&2; continue ;;
        esac
        selected_index="$answer"
        if [ "$selected_index" -lt 1 ] || [ "$selected_index" -gt "${#choice_keys[@]}" ]; then
            echo "  [WARN] Selection is out of range." >&2
            continue
        fi
        printf '%s\n' "${choice_keys[$((selected_index - 1))]}"
        return 0
    done
}

resolve_install_selection() {
    local saved_selected_raw=""
    local saved_selected=""
    local saved_primary=""
    local saved_installed_at=""

    if [ -f "$INSTALL_STATE_FILE" ] && ! $RECONFIGURE; then
        saved_selected_raw="$(read_install_state_value selectedRuntimes 2>/dev/null || true)"
        saved_selected="$(normalize_runtime_csv "$saved_selected_raw")"
        saved_primary="$(read_install_state_value primaryRuntime 2>/dev/null || true)"
        saved_installed_at="$(read_install_state_value installedAt 2>/dev/null || true)"
        if [ -n "$saved_selected" ] && [ -n "$saved_primary" ]; then
            echo ""
            echo "=== GAL runtime selection ==="
            echo "  [OK] Using saved install state from $INSTALL_STATE_FILE"
            echo "  [OK] Selected runtimes: ${saved_selected//,/ , }"
            echo "  [OK] Primary runtime: $saved_primary"
            SELECTED_RUNTIMES_CSV="$saved_selected"
            PRIMARY_RUNTIME="$saved_primary"
            if [ "$saved_selected" != "$saved_selected_raw" ]; then
                local configured_at="$saved_installed_at"
                [ -z "$configured_at" ] && configured_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
                write_install_state "$saved_selected" "$saved_primary" "$configured_at" "$configured_at"
            fi
            return 0
        fi
    fi

    local detected_csv
    detected_csv="$(detect_installed_runtimes)"
    local default_selection="$detected_csv"
    local prompt_reason="Detected a legacy GAL machine install without install-state. Confirm or change the runtime set before continuing."

    if [ -z "$default_selection" ]; then
        default_selection="$(IFS=,; echo "${RUNTIME_KEYS[*]}")"
        prompt_reason="First-time GAL install detected. Choose where GAL should install runtime integrations."
    fi

    echo ""
    echo "=== GAL runtime selection ==="
    SELECTED_RUNTIMES_CSV="$(normalize_runtime_csv "$(read_runtime_selection "$default_selection" "$prompt_reason")")"

    local default_primary="$saved_primary"
    if [ -z "$default_primary" ] || [[ ",$SELECTED_RUNTIMES_CSV," != *",$default_primary,"* ]]; then
        default_primary="$(default_primary_runtime ${SELECTED_RUNTIMES_CSV//,/ })"
    fi
    PRIMARY_RUNTIME="$(read_primary_runtime "$SELECTED_RUNTIMES_CSV" "$default_primary")"

    local configured_at installed_at
    configured_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    installed_at="$saved_installed_at"
    [ -z "$installed_at" ] && installed_at="$configured_at"
    write_install_state "$SELECTED_RUNTIMES_CSV" "$PRIMARY_RUNTIME" "$installed_at" "$configured_at"
}

ensure_ripgrep() {
    $UNINSTALL && return 0

    echo ""
    echo "=== ripgrep (rg) ==="

    if command_exists rg; then
        echo "  [OK] rg available"
        return 0
    fi

    if $DRY_RUN; then
        echo "  [DRY RUN] rg missing. Would prompt to install ripgrep if a supported package manager is available."
        return 0
    fi

    local answer=""
    if [[ "${OSTYPE:-}" == darwin* ]] && command_exists brew; then
        read -r -p "  [PROMPT] ripgrep (rg) was not found. Install it now via Homebrew? [Y/n] " answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo "  [SKIP] ripgrep installation skipped"; return 0 ;;
        esac
        brew install ripgrep || { echo "  [WARN] ripgrep installation failed"; return 0; }
    elif command_exists apt-get; then
        read -r -p "  [PROMPT] ripgrep (rg) was not found. Install it now via apt-get? [Y/n] " answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo "  [SKIP] ripgrep installation skipped"; return 0 ;;
        esac
        sudo apt-get update && sudo apt-get install -y ripgrep || { echo "  [WARN] ripgrep installation failed"; return 0; }
    elif command_exists dnf; then
        read -r -p "  [PROMPT] ripgrep (rg) was not found. Install it now via dnf? [Y/n] " answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo "  [SKIP] ripgrep installation skipped"; return 0 ;;
        esac
        sudo dnf install -y ripgrep || { echo "  [WARN] ripgrep installation failed"; return 0; }
    elif command_exists pacman; then
        read -r -p "  [PROMPT] ripgrep (rg) was not found. Install it now via pacman? [Y/n] " answer
        case "$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')" in
            n|no) echo "  [SKIP] ripgrep installation skipped"; return 0 ;;
        esac
        sudo pacman -Sy --noconfirm ripgrep || { echo "  [WARN] ripgrep installation failed"; return 0; }
    else
        echo "  [WARN] rg not found and no supported package manager was detected. Install ripgrep manually, then reopen the terminal."
        return 0
    fi

    if command_exists rg; then
        echo "  [OK] ripgrep installed and available"
    else
        echo "  [WARN] ripgrep was installed, but this shell still cannot resolve rg. Open a new terminal and rerun your command."
    fi
}

if ! $UNINSTALL; then
    resolve_install_selection
    ensure_ripgrep
fi

SELECTED_RUNTIMES_CSV="${SELECTED_RUNTIMES_CSV:-}"
PRIMARY_RUNTIME="${PRIMARY_RUNTIME:-}"

runtime_selected() {
    local key="$1"
    [[ ",${SELECTED_RUNTIMES_CSV}," == *",${key},"* ]]
}

INSTALL_COPILOT=false
INSTALL_GEMINI=false
INSTALL_CODEX=false
INSTALL_CLAUDE=false
INSTALL_SHARED_SKILLS=false
NEEDS_BAKED_COMMAND_SKILLS=false

if runtime_selected copilot; then INSTALL_COPILOT=true; fi
if runtime_selected gemini; then INSTALL_GEMINI=true; fi
if runtime_selected codex; then INSTALL_CODEX=true; fi
if runtime_selected claude; then INSTALL_CLAUDE=true; fi
if $INSTALL_GEMINI || $INSTALL_CODEX; then INSTALL_SHARED_SKILLS=true; fi
if $INSTALL_COPILOT || $INSTALL_GEMINI || $INSTALL_CODEX || $INSTALL_CLAUDE; then NEEDS_BAKED_COMMAND_SKILLS=true; fi

# --- Ensure target directories ---

if ! $UNINSTALL; then
    dirs_to_ensure=("$GAL_STATE_ROOT")
    if $INSTALL_COPILOT; then
        dirs_to_ensure+=("$COPILOT_ROOT" "$AGENTS_TARGET" "$SKILLS_TARGET")
    fi
    if $INSTALL_SHARED_SKILLS; then
        dirs_to_ensure+=("$SHARED_AGENTS_ROOT" "$SHARED_SKILLS_TARGET")
    fi
    if $INSTALL_GEMINI; then
        dirs_to_ensure+=("$GEMINI_ROOT" "$GEMINI_SKILLS_TARGET" "$GEMINI_COMMANDS_TARGET")
    fi
    if $INSTALL_CODEX; then
        dirs_to_ensure+=("$CODEX_ROOT" "$CODEX_SKILLS_TARGET")
    fi
    if $INSTALL_CLAUDE; then
        dirs_to_ensure+=("$CLAUDE_ROOT" "$CLAUDE_SKILLS_TARGET" "$CLAUDE_COMMANDS_TARGET")
    fi

    for dir in "${dirs_to_ensure[@]}"; do
        if [ ! -d "$dir" ]; then
            if $DRY_RUN; then
                echo "[DRY RUN] Would create directory: $dir"
            else
                mkdir -p "$dir"
                echo "[OK] Created directory: $dir"
            fi
        fi
    done
fi

# --- Agent symlinks ---

agent_files=("$REPO_ROOT"/agent/*.agent.md)
agent_count=${#agent_files[@]}
agent_ok=0
agent_fail=0

echo ""
echo "=== Agents ($agent_count files) ==="

for f in "${agent_files[@]}"; do
    name="$(basename "$f")"
    link_path="$AGENTS_TARGET/$name"

    if $UNINSTALL || ! $INSTALL_COPILOT; then
        safe_unlink "$link_path"
    else
        if safe_link "$link_path" "$f"; then
            ((agent_ok++)) || true
        else
            ((agent_fail++)) || true
        fi
    fi
done

# --- Skill symlinks ---

skill_dirs=()
while IFS= read -r -d '' d; do
    skill_dirs+=("$d")
done < <(find "$REPO_ROOT/skills" -mindepth 1 -maxdepth 1 -type d -print0)

skill_count=${#skill_dirs[@]}
skill_ok=0
skill_fail=0

echo ""
echo "=== Skills ($skill_count directories) ==="

for d in "${skill_dirs[@]}"; do
    name="$(basename "$d")"
    link_path="$SKILLS_TARGET/$name"

    if $UNINSTALL || ! $INSTALL_COPILOT; then
        safe_unlink "$link_path"
    else
        if safe_link "$link_path" "$d"; then
            ((skill_ok++)) || true
        else
            ((skill_fail++)) || true
        fi
    fi
done

# --- Migration: remove .gemini/skills GAL symlinks (Gemini now uses custom commands + shared .agents skills) ---

echo ""
echo "=== Migration: .gemini/skills cleanup ==="

gemini_migrate_ok=0
all_gal_skill_names=("${COMMAND_SKILL_NAMES[@]}" "gal.bak")
for d in "${skill_dirs[@]}"; do
    all_gal_skill_names+=("$(basename "$d")")
done
for name in "${all_gal_skill_names[@]}"; do
    link_path="$GEMINI_SKILLS_TARGET/$name"
    [ -e "$link_path" ] || continue
    if is_symlink "$link_path"; then
        target="$(readlink "$link_path")"
        if [[ "$target" == *"$REPO_ROOT"* ]]; then
            if $DRY_RUN; then
                echo "  [DRY RUN] Would remove: $link_path"
            else
                rm -rf "$link_path"
                echo "  [REMOVED] $link_path"
                ((gemini_migrate_ok++)) || true
            fi
        fi
    elif [ "$name" = "gal.bak" ]; then
        if $DRY_RUN; then
            echo "  [DRY RUN] Would remove: $link_path"
        else
            rm -rf "$link_path"
            echo "  [REMOVED] $link_path (real dir)"
            ((gemini_migrate_ok++)) || true
        fi
    fi
done
if ! $DRY_RUN && [ "$gemini_migrate_ok" -eq 0 ]; then
    echo "  [OK] Nothing to migrate in .gemini/skills"
fi

# --- Shared reusable skill symlinks (.agents/skills for Gemini + Codex) ---

shared_skill_ok=0
shared_skill_fail=0

echo ""
echo "=== Shared Skills - Gemini + Codex ($skill_count reusable directories via .agents) ==="

for d in "${skill_dirs[@]}"; do
    name="$(basename "$d")"
    link_path="$SHARED_SKILLS_TARGET/$name"

    if $UNINSTALL || ! $INSTALL_SHARED_SKILLS; then
        safe_unlink "$link_path"
    else
        if safe_link "$link_path" "$d"; then
            ((shared_skill_ok++)) || true
        else
            ((shared_skill_fail++)) || true
        fi
    fi
done

# --- Claude reusable skill symlinks (.claude/skills) ---

claude_skill_ok=0
claude_skill_fail=0

echo ""
echo "=== Claude Skills ($skill_count reusable directories) ==="

for d in "${skill_dirs[@]}"; do
    name="$(basename "$d")"
    link_path="$CLAUDE_SKILLS_TARGET/$name"

    if $UNINSTALL || ! $INSTALL_CLAUDE; then
        safe_unlink "$link_path"
    else
        if safe_link "$link_path" "$d"; then
            ((claude_skill_ok++)) || true
        else
            ((claude_skill_fail++)) || true
        fi
    fi
done

# --- Gemini gal-context.md ---

echo ""
echo "=== Gemini gal-context.md ==="

if $UNINSTALL || ! $INSTALL_GEMINI; then
    if [ -f "$GEMINI_CONTEXT_FILE" ]; then
        if $DRY_RUN; then
            echo "  [DRY RUN] Would remove: $GEMINI_CONTEXT_FILE"
        else
            rm "$GEMINI_CONTEXT_FILE"
            echo "  [REMOVED] $GEMINI_CONTEXT_FILE"
        fi
    fi
else
    context_lines=""
    while IFS= read -r -d '' sd; do
        sname="$(basename "$sd")"
        context_lines+="@$SHARED_SKILLS_TARGET/$sname/SKILL.md"$'\n'
    done < <(find "$REPO_ROOT/skills" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

    if $DRY_RUN; then
        echo "  [DRY RUN] Would write: $GEMINI_CONTEXT_FILE ($skill_count skill imports)"
    else
        printf '%s' "$context_lines" > "$GEMINI_CONTEXT_FILE"
        echo "  [OK] $GEMINI_CONTEXT_FILE ($skill_count skill imports)"
    fi
fi

# --- Gemini settings.json: context.fileName bridge ---

GEMINI_SETTINGS_FILE="$GEMINI_ROOT/settings.json"

echo ""
echo "=== Gemini settings.json bridge ==="

if $UNINSTALL; then
    echo "  [SKIP] settings.json not modified during uninstall (user-owned file)"
elif ! $INSTALL_GEMINI; then
    echo "  [SKIP] Gemini runtime not selected; settings.json bridge not updated"
elif $DRY_RUN; then
    echo "  [DRY RUN] Would merge AGENTS.md into context.fileName in: $GEMINI_SETTINGS_FILE"
else
    if command -v jq &>/dev/null; then
        if [ -f "$GEMINI_SETTINGS_FILE" ]; then
            merged="$(jq '.context.fileName = ((.context.fileName // []) + ["AGENTS.md","GEMINI.md"] | unique)' "$GEMINI_SETTINGS_FILE")"
        else
            merged='{"context":{"fileName":["AGENTS.md","GEMINI.md"]}}'
        fi
        printf '%s\n' "$merged" > "$GEMINI_SETTINGS_FILE"
        echo "  [OK] $GEMINI_SETTINGS_FILE (context.fileName includes AGENTS.md and GEMINI.md)"
    elif [ ! -f "$GEMINI_SETTINGS_FILE" ]; then
        printf '{"context":{"fileName":["AGENTS.md","GEMINI.md"]}}\n' > "$GEMINI_SETTINGS_FILE"
        echo "  [OK] $GEMINI_SETTINGS_FILE (created; install jq for merge support on future runs)"
    else
        echo "  [WARN] jq not found and $GEMINI_SETTINGS_FILE already exists — skipping bridge (install jq and rerun)"
    fi
fi

# --- VS Code settings.json: disable duplicate .agents skill discovery ---

echo ""
echo "=== VS Code settings bridge ==="

if $UNINSTALL; then
    echo "  [SKIP] VS Code settings.json not modified during uninstall (user-owned file)"
elif ! $INSTALL_COPILOT; then
    echo "  [SKIP] Copilot runtime not selected; VS Code settings bridge not updated"
elif $DRY_RUN; then
    echo "  [DRY RUN] Would set chat.agentSkillsLocations[\"~/.agents/skills\"]=false in: $VSCODE_SETTINGS_FILE"
else
    vscode_settings_dir="$(dirname "$VSCODE_SETTINGS_FILE")"
    mkdir -p "$vscode_settings_dir"

    if command -v python3 &>/dev/null; then
        if python3 - "$VSCODE_SETTINGS_FILE" <<'PY'
import json
import os
import sys

path = sys.argv[1]
if os.path.exists(path):
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
else:
    data = {}

locations = data.get("chat.agentSkillsLocations")
if locations is None:
    locations = {}
    data["chat.agentSkillsLocations"] = locations
elif not isinstance(locations, dict):
    raise TypeError("chat.agentSkillsLocations is not an object")

locations["~/.agents/skills"] = False

with open(path, "w", encoding="utf-8") as fh:
    json.dump(data, fh, indent=2)
    fh.write("\n")
PY
        then
            echo "  [OK] $VSCODE_SETTINGS_FILE (chat.agentSkillsLocations disables ~/.agents/skills for VS Code)"
        else
            echo "  [WARN] Could not merge $VSCODE_SETTINGS_FILE — add chat.agentSkillsLocations manually"
        fi
    elif [ ! -f "$VSCODE_SETTINGS_FILE" ]; then
        printf '{\n  "chat.agentSkillsLocations": {\n    "~/.agents/skills": false\n  }\n}\n' > "$VSCODE_SETTINGS_FILE"
        echo "  [OK] $VSCODE_SETTINGS_FILE (created; chat.agentSkillsLocations disables ~/.agents/skills for VS Code)"
    else
        echo "  [WARN] python3 not found and $VSCODE_SETTINGS_FILE already exists — add chat.agentSkillsLocations manually"
    fi
fi

# --- MCP config bridge ---

echo ""
echo "=== MCP config bridge ==="

if $UNINSTALL; then
    echo "  [SKIP] MCP config files not modified during uninstall (user-owned files)"
elif $DRY_RUN; then
    $INSTALL_COPILOT && echo "  [DRY RUN] Would merge MCP servers into: $VSCODE_MCP_FILE"
    $INSTALL_GEMINI && echo "  [DRY RUN] Would merge MCP servers into: $GEMINI_SETTINGS_FILE"
    $INSTALL_CODEX && echo "  [DRY RUN] Would merge MCP servers into: $CODEX_CONFIG_FILE"
    $INSTALL_CLAUDE && echo "  [SKIP] Claude Code MCP merge remains deferred in this installer"
else
    if [ ! -f "$MCP_MANIFEST_LOCAL" ]; then
        printf '{\n  "servers": {}\n}\n' > "$MCP_MANIFEST_LOCAL"
        echo "  [OK] Created local MCP override file: $MCP_MANIFEST_LOCAL"
    fi

    if command -v python3 &>/dev/null; then
        if python3 - "$REPO_ROOT" "$MCP_MANIFEST_EXAMPLE" "$MCP_MANIFEST_LOCAL" "$VSCODE_MCP_FILE" "$GEMINI_SETTINGS_FILE" "$CODEX_CONFIG_FILE" "$INSTALL_COPILOT" "$INSTALL_GEMINI" "$INSTALL_CODEX" <<'PY'
import json
import os
import re
import sys
from pathlib import Path

repo_root = Path(sys.argv[1])
manifest_example = Path(sys.argv[2])
manifest_local = Path(sys.argv[3])
vscode_mcp = Path(sys.argv[4])
gemini_settings = Path(sys.argv[5])
codex_config = Path(sys.argv[6])
install_vscode = sys.argv[7].lower() == 'true'
install_gemini = sys.argv[8].lower() == 'true'
install_codex = sys.argv[9].lower() == 'true'


def read_json(path: Path):
    if not path.exists():
        return {}
    raw = path.read_text(encoding="utf-8").strip()
    if not raw:
        return {}
    return json.loads(raw)


def deep_merge(base, overlay):
    if isinstance(base, dict) and isinstance(overlay, dict):
        merged = dict(base)
        for key, value in overlay.items():
            if key in merged:
                merged[key] = deep_merge(merged[key], value)
            else:
                merged[key] = value
        return merged
    return overlay


def read_env_file(path: Path):
    values = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key and value:
            values[key] = value
    return values


def get_value(values, name):
    return values.get(name) or os.environ.get(name)


def split_config_list(value):
    if not value:
        return []
    return [item for item in re.split(r"\s*,\s*", value) if item]


def resolve_string(value, values):
    match = re.fullmatch(r"\$\{([A-Z0-9_]+)\}", value)
    if match:
        resolved = get_value(values, match.group(1))
        if resolved is not None:
            return resolved
    return re.sub(r"\$\{([A-Z0-9_]+)\}", lambda m: get_value(values, m.group(1)) or m.group(0), value)


def resolve_node(node, values, expand_args=False):
    if isinstance(node, str):
        match = re.fullmatch(r"\$\{([A-Z0-9_]+)\[\]\}", node)
        if expand_args and match:
            return split_config_list(get_value(values, match.group(1)))
        return resolve_string(node, values)
    if isinstance(node, list):
        items = []
        for item in node:
            resolved = resolve_node(item, values, expand_args=expand_args)
            if expand_args and isinstance(resolved, list):
                items.extend(resolved)
            else:
                items.append(resolved)
        return items
    if isinstance(node, dict):
        return {key: resolve_node(value, values, expand_args=(key == "args")) for key, value in node.items()}
    return node


def provider_ready(provider, values):
    for key in provider.get("requiredEnv", []):
        if not get_value(values, key):
            return False
    return True


def toml_string(value):
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def toml_array(values):
    return "[" + ", ".join(toml_string(value) for value in values) + "]"


def codex_section(name, config):
    lines = [f"[mcp_servers.{name}]"]
    if "url" in config:
        lines.append(f"url = {toml_string(config['url'])}")
    else:
        lines.append(f"command = {toml_string(config['command'])}")
        if config.get("args"):
            lines.append(f"args = {toml_array(config['args'])}")
    if config.get("env"):
        lines.append("")
        lines.append(f"[mcp_servers.{name}.env]")
        for env_key in sorted(config["env"]):
            lines.append(f"{env_key} = {toml_string(config['env'][env_key])}")
    return "\n".join(lines)


manifest = read_json(manifest_example)
manifest = deep_merge(manifest, read_json(manifest_local))
servers = manifest.get("servers", {})

local_env = read_env_file(repo_root / "config.local.env")
if "MCP_MEMORY_FILE_PATH" not in local_env:
    local_env["MCP_MEMORY_FILE_PATH"] = str(Path.home() / "mcp-memory.json")
if "MCP_FILESYSTEM_PATHS" not in local_env:
    defaults = [str(repo_root.parent)]
    if local_env.get("OBSIDIAN_VAULT"):
        defaults.append(local_env["OBSIDIAN_VAULT"])
    local_env["MCP_FILESYSTEM_PATHS"] = ",".join(dict.fromkeys(defaults))

if install_vscode:
    vscode_data = read_json(vscode_mcp)
    vscode_data.setdefault("servers", {})
    vscode_changed = False
    for server_name, server in servers.items():
        provider = server.get("providers", {}).get("vscode")
        if not provider or not provider.get("enabled"):
            continue
        if not provider_ready(provider, local_env):
            print(f"  [WARN] Skipping VS Code MCP server '{server_name}' because required env is missing")
            continue
        key = provider.get("key", server_name)
        if key in vscode_data["servers"]:
            continue
        vscode_data["servers"][key] = resolve_node(provider["config"], local_env)
        vscode_changed = True
        print(f"  [ADD] VS Code MCP server: {key}")
    if vscode_changed:
        vscode_mcp.parent.mkdir(parents=True, exist_ok=True)
        vscode_mcp.write_text(json.dumps(vscode_data, indent=2) + "\n", encoding="utf-8")
        print(f"  [OK] {vscode_mcp}")

if install_gemini:
    gemini_data = read_json(gemini_settings)
    gemini_data.setdefault("mcpServers", {})
    gemini_changed = False
    for server_name, server in servers.items():
        provider = server.get("providers", {}).get("gemini")
        if not provider or not provider.get("enabled"):
            continue
        if not provider_ready(provider, local_env):
            print(f"  [WARN] Skipping Gemini MCP server '{server_name}' because required env is missing")
            continue
        key = provider.get("key", server_name)
        if key in gemini_data["mcpServers"]:
            continue
        gemini_data["mcpServers"][key] = resolve_node(provider["config"], local_env)
        gemini_changed = True
        print(f"  [ADD] Gemini MCP server: {key}")
    if gemini_changed:
        gemini_settings.parent.mkdir(parents=True, exist_ok=True)
        gemini_settings.write_text(json.dumps(gemini_data, indent=2) + "\n", encoding="utf-8")
        print(f"  [OK] {gemini_settings}")

if install_codex:
    codex_raw = codex_config.read_text(encoding="utf-8") if codex_config.exists() else ""
    codex_sections = []
    for server_name, server in servers.items():
        provider = server.get("providers", {}).get("codex")
        if not provider or not provider.get("enabled"):
            continue
        if not provider_ready(provider, local_env):
            print(f"  [WARN] Skipping Codex MCP server '{server_name}' because required env is missing")
            continue
        key = provider.get("key", server_name)
        if re.search(rf"(?m)^\[mcp_servers\.{re.escape(key)}\]\s*$", codex_raw):
            continue
        codex_sections.append(codex_section(key, resolve_node(provider["config"], local_env)))
        print(f"  [ADD] Codex MCP server: {key}")
    if codex_sections:
        codex_config.parent.mkdir(parents=True, exist_ok=True)
        prefix = codex_raw.rstrip()
        if prefix:
            prefix += "\n\n"
        codex_config.write_text(prefix + "\n\n".join(codex_sections) + "\n", encoding="utf-8")
        print(f"  [OK] {codex_config}")
PY
        then
            :
        else
            echo "  [WARN] Could not merge MCP config files"
        fi
    else
        echo "  [WARN] python3 not found — skipping MCP config merge"
    fi
    $INSTALL_CLAUDE && echo "  [SKIP] Claude Code MCP merge remains deferred in this installer"
fi

# --- GAL_ROOT symlinks ---

gal_root_ok=0
echo ""
echo "=== GAL_ROOT symlinks ==="

if $UNINSTALL; then
    safe_unlink "$GAL_ROOT_COPILOT"
    safe_unlink "$GAL_ROOT_GEMINI"
else
    if $INSTALL_COPILOT; then
        if safe_link "$GAL_ROOT_COPILOT" "$REPO_ROOT"; then ((gal_root_ok++)) || true; fi
    else
        safe_unlink "$GAL_ROOT_COPILOT"
    fi
    if $INSTALL_GEMINI; then
        if safe_link "$GAL_ROOT_GEMINI"  "$REPO_ROOT"; then ((gal_root_ok++)) || true; fi
    else
        safe_unlink "$GAL_ROOT_GEMINI"
    fi
fi

# --- Generated GAL command skills (bake templates -> commands/gal*/SKILL.md) ---

echo ""
echo "=== Generated GAL command skills ==="

if $UNINSTALL || ! $NEEDS_BAKED_COMMAND_SKILLS; then
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        baked_skill="$REPO_ROOT/commands/$command_skill_name/SKILL.md"
        if [ -f "$baked_skill" ]; then
            if $DRY_RUN; then echo "  [DRY RUN] Would remove baked: $baked_skill"
            else rm "$baked_skill"; echo "  [REMOVED] $baked_skill"; fi
        fi
    done
else
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        command_skill_source="$REPO_ROOT/commands/$command_skill_name"
        command_skill_template="$command_skill_source/SKILL.template.md"
        local_override_path="$command_skill_source/SKILL.local.md"
        if [ ! -f "$command_skill_template" ]; then
            echo "  [WARN] Template not found: $command_skill_template"
        else
            baked_skill="$command_skill_source/SKILL.md"
            if $DRY_RUN; then
                if [ -f "$local_override_path" ]; then
                    echo "  [DRY RUN] Would write baked with local overlay: $baked_skill"
                else
                    echo "  [DRY RUN] Would write baked: $baked_skill"
                fi
            else
                baked="$(get_baked_command_skill_content "$command_skill_template" "$local_override_path")"
                printf '%s\n' "$baked" > "$baked_skill"
                if [ -f "$local_override_path" ]; then
                    echo "  [OK] $baked_skill (with local overlay)"
                else
                    echo "  [OK] $baked_skill"
                fi
            fi
        fi
    done
fi

# --- GAL command skill symlinks (commands/gal*/ -> ~/.copilot/skills/gal*/ + ~/.codex/skills/gal*/) ---

echo ""
echo "=== GAL command skill symlinks ==="

if $UNINSTALL; then
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        safe_unlink "$SKILLS_TARGET/$command_skill_name"
        safe_unlink "$CODEX_SKILLS_TARGET/$command_skill_name"
    done
else
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        command_skill_source="$REPO_ROOT/commands/$command_skill_name"
        if $INSTALL_COPILOT; then
            safe_link "$SKILLS_TARGET/$command_skill_name" "$command_skill_source"
        else
            safe_unlink "$SKILLS_TARGET/$command_skill_name"
        fi
        if $INSTALL_CODEX; then
            safe_link "$CODEX_SKILLS_TARGET/$command_skill_name" "$command_skill_source"
        else
            safe_unlink "$CODEX_SKILLS_TARGET/$command_skill_name"
        fi
    done
fi

# --- Migration: remove GAL command skill symlinks from shared .agents/skills ---

echo ""
echo "=== Migration: .agents command cleanup ==="

for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
    shared_command_path="$SHARED_SKILLS_TARGET/$command_skill_name"
    [ -e "$shared_command_path" ] || continue
    if ! is_gal_repo_link "$shared_command_path"; then
        echo "  [SKIP] User-owned shared skill preserved: $shared_command_path"
        continue
    fi

    if $DRY_RUN; then
        echo "  [DRY RUN] Would remove: $shared_command_path"
    else
        rm "$shared_command_path"
        echo "  [REMOVED] $shared_command_path"
    fi
done

# --- Gemini custom commands ---

echo ""
echo "=== Gemini custom commands ==="

if $UNINSTALL || ! $INSTALL_GEMINI; then
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        command_file="$GEMINI_COMMANDS_TARGET/$command_skill_name.toml"
        [ -f "$command_file" ] || continue
        if ! is_gal_managed_file "$command_file"; then
            echo "  [SKIP] User-owned Gemini command preserved: $command_file"
            continue
        fi
        if $DRY_RUN; then
            echo "  [DRY RUN] Would remove: $command_file"
        else
            rm "$command_file"
            echo "  [REMOVED] $command_file"
        fi
    done
else
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        command_file="$GEMINI_COMMANDS_TARGET/$command_skill_name.toml"
        skill_path="$REPO_ROOT/commands/$command_skill_name/SKILL.md"
        if $DRY_RUN; then
            echo "  [DRY RUN] Would write: $command_file"
        else
            new_gemini_command_file_content "$skill_path" > "$command_file"
            echo "  [OK] $command_file"
        fi
    done

    echo "  [NOTE] Reload active Gemini sessions with /commands reload or restart Gemini CLI to pick up updated GAL commands."
fi

# --- Claude custom commands ---

echo ""
echo "=== Claude custom commands ==="

if $UNINSTALL || ! $INSTALL_CLAUDE; then
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        command_file="$CLAUDE_COMMANDS_TARGET/$command_skill_name.md"
        [ -f "$command_file" ] || continue
        if ! is_gal_managed_file "$command_file"; then
            echo "  [SKIP] User-owned Claude command preserved: $command_file"
            continue
        fi
        if $DRY_RUN; then
            echo "  [DRY RUN] Would remove: $command_file"
        else
            rm "$command_file"
            echo "  [REMOVED] $command_file"
        fi
    done
else
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        command_file="$CLAUDE_COMMANDS_TARGET/$command_skill_name.md"
        skill_path="$REPO_ROOT/commands/$command_skill_name/SKILL.md"
        if $DRY_RUN; then
            echo "  [DRY RUN] Would write: $command_file"
        else
            new_claude_command_file_content "$skill_path" "$command_skill_name" > "$command_file"
            echo "  [OK] $command_file"
        fi
    done

    echo "  [NOTE] Restart Claude Code or reload its command surface to pick up updated GAL commands."
fi

# --- Migration: remove obsolete command files from installed locations ---

echo ""
echo "=== Migration: obsolete command cleanup ==="

for skills_dir in "$SKILLS_TARGET" "$GEMINI_SKILLS_TARGET" "$SHARED_SKILLS_TARGET" "$CODEX_SKILLS_TARGET"; do
    for d in "$skills_dir"/*; do
        [ -e "$d" ] || continue
        [ -d "$d" ] || continue
        d_name="$(basename "$d")"

        keep_dir=false
        for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
            if [ "$d_name" = "$command_skill_name" ]; then
                keep_dir=true
                break
            fi
        done
        if $keep_dir; then
            continue
        fi
        if ! is_gal_command_link "$d"; then
            continue
        fi

        if $DRY_RUN; then
            echo "  [DRY RUN] Would remove obsolete command link: $d"
        else
            rm -rf "$d"
            echo "  [REMOVED] Obsolete command link: $d"
        fi
    done
done

for command_file in "$CLAUDE_COMMANDS_TARGET"/*.md; do
    [ -e "$command_file" ] || continue
    command_name="$(basename "$command_file" .md)"

    keep_file=false
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        if [ "$command_name" = "$command_skill_name" ]; then
            keep_file=true
            break
        fi
    done
    if $keep_file; then
        continue
    fi
    if ! is_gal_managed_file "$command_file"; then
        continue
    fi

    if $DRY_RUN; then
        echo "  [DRY RUN] Would remove obsolete Claude command: $command_file"
    else
        rm "$command_file"
        echo "  [REMOVED] Obsolete Claude command: $command_file"
    fi
done

for command_file in "$GEMINI_COMMANDS_TARGET"/*.toml; do
    [ -e "$command_file" ] || continue
    command_name="$(basename "$command_file" .toml)"

    keep_file=false
    for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
        if [ "$command_name" = "$command_skill_name" ]; then
            keep_file=true
            break
        fi
    done
    if $keep_file; then
        continue
    fi
    if ! is_gal_managed_file "$command_file"; then
        continue
    fi

    if $DRY_RUN; then
        echo "  [DRY RUN] Would remove obsolete Gemini command: $command_file"
    else
        rm "$command_file"
        echo "  [REMOVED] Obsolete Gemini command: $command_file"
    fi
done

# --- Migration: remove legacy gal-* dirs from installed locations ---

echo ""
echo "=== Migration: gal-* cleanup ==="

for skills_dir in "$SKILLS_TARGET" "$GEMINI_SKILLS_TARGET" "$SHARED_SKILLS_TARGET" "$CODEX_SKILLS_TARGET"; do
    for d in "$skills_dir"/gal-*/; do
        [ -e "$d" ] || continue
        d_name="$(basename "$d")"
        keep_dir=false
        for command_skill_name in "${COMMAND_SKILL_NAMES[@]}"; do
            if [ "$d_name" = "$command_skill_name" ]; then
                keep_dir=true
                break
            fi
        done
        if $keep_dir; then
            continue
        fi
        if $DRY_RUN; then
            echo "  [DRY RUN] Would remove: $d"
        else
            rm -rf "$d"
            echo "  [REMOVED] $d"
        fi
    done
done

# --- Summary ---

echo ""
if $UNINSTALL; then
    echo "Uninstall complete."
elif $DRY_RUN; then
    echo "Dry run complete. No changes made."
    echo "Selected runtimes: ${SELECTED_RUNTIMES_CSV//,/ , }"
    echo "Primary runtime: $PRIMARY_RUNTIME"
else
    echo "Setup complete: runtimes=${SELECTED_RUNTIMES_CSV//,/ , }; primary=$PRIMARY_RUNTIME; agents=$agent_ok/$agent_count; skills(copilot)=$skill_ok/$skill_count; skills(shared)=$shared_skill_ok/$skill_count; skills(claude)=$claude_skill_ok/$skill_count; gal-root=$gal_root_ok/2"
    echo "Note: If SKILL.template.md or SKILL.local.md changes, re-run setup-machine.sh --replace to regenerate."
    if [ "$agent_fail" -gt 0 ] || [ "$skill_fail" -gt 0 ] || [ "$shared_skill_fail" -gt 0 ] || [ "$claude_skill_fail" -gt 0 ]; then
        echo "Some links failed. Check warnings above."
    fi
fi

# --- Personalization: config.local.env + smudge/clean filter ---

if ! $UNINSTALL && ! $DRY_RUN; then
    echo ""
    echo "=== Personalization ==="

    EXAMPLE_ENV="$REPO_ROOT/config.example.env"
    LOCAL_ENV="$REPO_ROOT/config.local.env"

    # 1. Copy config.example.env → config.local.env if missing
    if [ ! -f "$LOCAL_ENV" ]; then
        if [ -f "$EXAMPLE_ENV" ]; then
            cp "$EXAMPLE_ENV" "$LOCAL_ENV"
            echo "  [OK] Created config.local.env from config.example.env"
            echo "  [ACTION REQUIRED] Edit config.local.env with your paths"
        else
            echo "  [WARN] config.example.env not found — skipping"
        fi
    else
        echo "  [SKIP] config.local.env already exists"
    fi

    # 2. Copy model-roles.example.md → model-roles.local.md if missing
    EXAMPLE_ROLES="$REPO_ROOT/model-roles.example.md"
    LOCAL_ROLES="$REPO_ROOT/model-roles.local.md"

    if [ ! -f "$LOCAL_ROLES" ]; then
        if [ -f "$EXAMPLE_ROLES" ]; then
            cp "$EXAMPLE_ROLES" "$LOCAL_ROLES"
            echo "  [OK] Created model-roles.local.md from model-roles.example.md"
        fi
    else
        echo "  [SKIP] model-roles.local.md already exists"
    fi

    # 3. Register git smudge/clean filter
    cd "$REPO_ROOT"
    git config filter.gal-config.smudge "bash scripts/gal-smudge.sh"
    git config filter.gal-config.clean  "bash scripts/gal-clean.sh"
    git config filter.gal-config.required true
    echo "  [OK] Registered git filter 'gal-config' (smudge/clean)"

    # 4. Set custom hooks path
    git config core.hooksPath .githooks
    echo "  [OK] Set core.hooksPath to .githooks"

    # 5. Re-checkout ONLY the smudge-filtered files (not all tracked files)
    if [ -f "$LOCAL_ENV" ]; then
        has_values=$(grep -v '^\s*#' "$LOCAL_ENV" | grep -c '=.' || true)
        if [ "$has_values" -gt 0 ]; then
            tracked_filter_files=()
            for filter_file in config.local.env model-roles.local.md; do
                if git ls-files --error-unmatch "$filter_file" >/dev/null 2>&1; then
                    tracked_filter_files+=("$filter_file")
                fi
            done

            if [ "${#tracked_filter_files[@]}" -gt 0 ]; then
                git checkout -- "${tracked_filter_files[@]}"
                echo "  [OK] Re-checked out tracked filtered files (smudge filter applied)"
            else
                echo "  [INFO] Filtered files are not tracked yet — skipping git checkout"
            fi
        else
            echo "  [INFO] config.local.env has no values yet — fill it in, then run: git checkout -- config.local.env model-roles.local.md"
        fi
    fi
fi
