#!/usr/bin/env bash

set -euo pipefail

target_path="${1:-$PWD}"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

if [[ ! -d "$target_path" ]]; then
  echo "Target path does not exist: $target_path" >&2
  exit 1
fi

target_path="$(cd "$target_path" && pwd)"
project_path="$target_path/.dev/project.md"
copilot_dir="$target_path/.github"
copilot_path="$copilot_dir/copilot-instructions.md"
gemini_path="$target_path/GEMINI.md"
claude_path="$target_path/CLAUDE.md"
agents_path="$target_path/AGENTS.md"
antigravity_rules_dir="$target_path/.agents/rules"
antigravity_rule_path="$antigravity_rules_dir/gal.md"
conventions_dir="$repo_root/conventions"
workflow_path="$repo_root/workflows/coding.md"
model_roles_path="$repo_root/model-roles.md"
skills_root="$repo_root/skills"

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing required source file: $path" >&2
    exit 1
  fi
}

append_source_block() {
  local output_path="$1"
  local label="$2"
  local source_path="$3"
  printf '<!-- Source: %s -->\n' "$label" >> "$output_path"
  awk '
    { sub(/\r$/, ""); lines[NR] = $0 }
    END {
      last = NR
      while (last > 0 && lines[last] == "") {
        last--
      }
      for (i = 1; i <= last; i++) {
        print lines[i]
      }
    }
  ' "$source_path" >> "$output_path"
  printf '\n\n' >> "$output_path"
}

append_skill_index() {
  local output_path="$1"
  printf '## Repo Skills\n\n' >> "$output_path"
  printf 'The following repo-local skills are available by name. Read the corresponding `skills/<name>/SKILL.md` file when full instructions are needed.\n\n' >> "$output_path"

  local skill_dir skill_name
  for skill_dir in "${skill_dirs[@]}"; do
    skill_name="$(basename "$skill_dir")"
    printf -- '- `%s` - `skills/%s/SKILL.md`\n' "$skill_name" "$skill_name" >> "$output_path"
  done

  printf '\n' >> "$output_path"
}

build_adapter() {
  local output_path="$1"
  local title="$2"
  local include_skill_index="$3"
  shift 3
  local preamble=("$@")

  : > "$output_path"
  printf '# %s\n\n' "$title" >> "$output_path"
  printf '> Generated by `/gal init`. Do not edit manually.\n' >> "$output_path"
  printf '> Update `.dev/project.md` or the GAL source docs, then rerun `/gal init`.\n\n' >> "$output_path"
  printf '## Adapter Rules\n\n' >> "$output_path"
  local entry
  for entry in "${preamble[@]}"; do
    printf -- '- %s\n' "$entry" >> "$output_path"
  done
  printf '\n' >> "$output_path"

  append_source_block "$output_path" ".dev/project.md" "$project_path"

  local source_file
  for source_file in "${convention_files[@]}"; do
    append_source_block "$output_path" "conventions/$(basename "$source_file")" "$source_file"
  done

  append_source_block "$output_path" "workflows/coding.md" "$workflow_path"
  append_source_block "$output_path" "model-roles.md" "$model_roles_path"

  if [[ "$include_skill_index" == "true" ]]; then
    append_skill_index "$output_path"
  fi
}

build_antigravity_rule() {
  local output_path="$1"

  cat > "$output_path" <<'EOF'
# GAL Workspace Rule

Use the repo-local GAL adapter as the operating contract for planning, implementation, testing, review, and research work in this workspace.

@../../AGENTS.md

Apply this rule when the task touches GAL commands, agents, workflows, setup scripts, plans, or other repo-owned workflow state.
EOF
}

require_file "$project_path"
require_file "$workflow_path"
require_file "$model_roles_path"

# Auto-discover all skills from the skills/ directory
declare -a skill_dirs=()
if [[ -d "$skills_root" ]]; then
  while IFS= read -r -d '' skill_dir; do
    if [[ -f "$skill_dir/SKILL.md" ]]; then
      skill_dirs+=("$skill_dir")
    fi
  done < <(find "$skills_root" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
fi

declare -a convention_files=()
while IFS= read -r convention_file; do
  [[ -n "$convention_file" ]] && convention_files+=("$convention_file")
done < <(find "$conventions_dir" -maxdepth 1 -type f -name '*.md' | sort)
mkdir -p "$copilot_dir"
mkdir -p "$antigravity_rules_dir"

build_adapter \
  "$copilot_path" \
  "Copilot Instructions" \
  false \
  "This is the repo-local adapter for GitHub Copilot." \
  "Skills in this repo's \`skills/\` directory are listed by name only — Copilot discovers GAL commands from the global runtime install." \
  "This generator never modifies \`~/.copilot/skills/\` or any other machine-level configuration."

build_adapter \
  "$gemini_path" \
  "GEMINI Context" \
  true \
  "This is the repo-local adapter for Gemini CLI." \
  "Repo-local skills are indexed below by name so Gemini can discover them without duplicating every skill body in the adapter." \
  "This generator does not mutate \`~/.gemini/gal-context.md\` or any other machine-level configuration."

build_adapter \
  "$claude_path" \
  "CLAUDE Context" \
  true \
  "This is the repo-local adapter for Claude Code." \
  "Repo-local skills are indexed below by name so Claude Code can find the right skill file without duplicating every skill body in the adapter." \
  "This generator only writes repo-local adapters such as \`CLAUDE.md\`; machine-level Claude setup belongs to \`Setup-Machine\`."

build_adapter \
  "$agents_path" \
  "GAL Agent Instructions" \
  true \
  "This is the shared cross-CLI contract generated from repo sources for Copilot CLI, Codex CLI, Gemini CLI (via settings bridge), Antigravity workspace rules, and Claude Code CLI." \
  "Repo-local skills are indexed below by name so runtimes can discover the right skill file without duplicating every skill body in this shared adapter." \
  "This file is generated by \`/gal init\`. Do not edit manually."

build_antigravity_rule "$antigravity_rule_path"

echo "Sync-DevContext completed for: $target_path"
echo "- Generated: .github/copilot-instructions.md"
echo "- Generated: GEMINI.md"
echo "- Generated: CLAUDE.md"
echo "- Generated: AGENTS.md"
echo "- Generated: .agents/rules/gal.md"
if [[ ${#skill_dirs[@]} -gt 0 ]]; then
  local_skills=()
  for d in "${skill_dirs[@]}"; do local_skills+=("$(basename "$d")"); done
  echo "- Indexed skills: ${local_skills[*]}"
else
  echo "- No skills/ directory found; no skills indexed."
fi