param(
    [string]$TargetPath = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot
$resolvedTarget = (Resolve-Path $TargetPath).Path

$projectPath = Join-Path $resolvedTarget ".dev\project.md"
$copilotDir = Join-Path $resolvedTarget ".github"
$copilotPath = Join-Path $copilotDir "copilot-instructions.md"
$geminiPath = Join-Path $resolvedTarget "GEMINI.md"
$agentsPath = Join-Path $resolvedTarget "AGENTS.md"

$conventionsDir = Join-Path $repoRoot "conventions"
$workflowPath = Join-Path $repoRoot "workflows\coding.md"
$modelRolesPath = Join-Path $repoRoot "model-roles.md"
$skillsRoot = Join-Path $repoRoot "skills"

function Read-NormalizedFile([string]$Path) {
    if (-not (Test-Path $Path)) {
        throw "Missing required source file: $Path"
    }

    $content = Get-Content -Path $Path -Raw
    return ($content -replace "`r`n", "`n") -replace "`r", "`n"
}

function Get-MarkdownSection([string]$Content, [string]$Heading) {
    $pattern = "(?ms)^##\s+{0}\s*$\n(?<body>.*?)(?=^##\s+|\z)" -f [regex]::Escape($Heading)
    $match = [regex]::Match($Content, $pattern)
    if (-not $match.Success) {
        return $null
    }

    return $match.Groups['body'].Value.Trim()
}

function Get-ActiveSkills([string]$ProjectContent) {
    $section = Get-MarkdownSection -Content $ProjectContent -Heading 'Active Skills'
    if ([string]::IsNullOrWhiteSpace($section)) {
        throw "Missing required '## Active Skills' section in .dev/project.md. Review the file, list exact GAL skill folder names, then rerun /gal sync."
    }

    $skills = [System.Collections.Generic.List[string]]::new()
    foreach ($line in ($section -split "`n")) {
        if ($line -match '^\s*-\s+(.+?)\s*$') {
            $skillName = $matches[1].Trim().Trim('`').Trim()
            if (-not [string]::IsNullOrWhiteSpace($skillName)) {
                $skills.Add($skillName)
            }
        }
    }

    if ($skills.Count -eq 0) {
        throw "The '## Active Skills' section in .dev/project.md is empty. Add one exact skill folder name per bullet before running /gal sync."
    }

    $duplicates = $skills |
        Group-Object |
        Where-Object { $_.Count -gt 1 } |
        Select-Object -ExpandProperty Name
    if ($duplicates) {
        throw "Duplicate Active Skills entries found in .dev/project.md: $($duplicates -join ', '). Keep each skill only once."
    }

    return @($skills)
}

function Resolve-SkillSources([string[]]$SkillNames) {
    $resolved = [System.Collections.Generic.List[object]]::new()
    foreach ($skillName in $SkillNames) {
        $skillDir = Join-Path $skillsRoot $skillName
        $skillFile = Join-Path $skillDir "SKILL.md"
        if (-not (Test-Path $skillDir)) {
            throw "Active skill '$skillName' does not exist under $skillsRoot. Use exact folder names from the GAL skills directory."
        }

        if (-not (Test-Path $skillFile)) {
            throw "Active skill '$skillName' is missing SKILL.md at $skillFile."
        }

        $resolved.Add([pscustomobject]@{
            Name    = $skillName
            Path    = $skillFile
            Content = Read-NormalizedFile -Path $skillFile
        })
    }

    return @($resolved)
}

function Get-ConventionSources() {
    return Get-ChildItem -Path $conventionsDir -File -Filter '*.md' |
        Sort-Object Name |
        ForEach-Object {
            [pscustomobject]@{
                Label   = "conventions/$($_.Name)"
                Content = Read-NormalizedFile -Path $_.FullName
            }
        }
}

function Add-SourceBlock([System.Collections.Generic.List[string]]$Lines, [string]$Label, [string]$Content) {
    $Lines.Add("<!-- Source: $Label -->")
    $Lines.Add($Content.Trim())
    $Lines.Add("")
}

function Build-AdapterContent(
    [string]$Title,
    [string[]]$Preamble,
    [string]$ProjectContent,
    [object[]]$ConventionSources,
    [string]$WorkflowContent,
    [string]$ModelRolesContent,
    [object[]]$SkillSources,
    [switch]$IncludeSkillBodies
) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# $Title")
    $lines.Add("")
    $lines.Add('> Generated by `gal sync`. Do not edit manually.')
    $lines.Add('> Update `.dev/project.md` or the GAL source docs, then rerun `/gal sync`.')
    $lines.Add("")
    $lines.Add("## Adapter Rules")
    $lines.Add("")
    foreach ($entry in $Preamble) {
        $lines.Add("- $entry")
    }
    $lines.Add("")
    $lines.Add("## Selected Active Skills")
    $lines.Add("")
    foreach ($skill in $SkillSources) {
        $lines.Add(('- `{0}`' -f $skill.Name))
    }
    $lines.Add("")

    Add-SourceBlock -Lines $lines -Label '.dev/project.md' -Content $ProjectContent
    foreach ($convention in $ConventionSources) {
        Add-SourceBlock -Lines $lines -Label $convention.Label -Content $convention.Content
    }
    Add-SourceBlock -Lines $lines -Label 'workflows/coding.md' -Content $WorkflowContent
    Add-SourceBlock -Lines $lines -Label 'model-roles.md' -Content $ModelRolesContent

    if ($IncludeSkillBodies) {
        foreach ($skill in $SkillSources) {
            Add-SourceBlock -Lines $lines -Label ("skills/{0}/SKILL.md" -f $skill.Name) -Content $skill.Content
        }
    }

    return (($lines -join "`n").TrimEnd() + "`n")
}

$projectContent = Read-NormalizedFile -Path $projectPath
$activeSkills = Get-ActiveSkills -ProjectContent $projectContent
$skillSources = Resolve-SkillSources -SkillNames $activeSkills
$conventionSources = Get-ConventionSources
$workflowContent = Read-NormalizedFile -Path $workflowPath
$modelRolesContent = Read-NormalizedFile -Path $modelRolesPath

[System.IO.Directory]::CreateDirectory($copilotDir) | Out-Null

$copilotContent = Build-AdapterContent `
    -Title 'Copilot Instructions' `
    -Preamble @(
        'This is the repo-local adapter for GitHub Copilot.',
        'Active skills are validated from `.dev/project.md` but not inlined here because Copilot discovers GAL skills from the global runtime install.',
        'This generator never modifies `~/.copilot/skills/` or any other machine-level configuration.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -ModelRolesContent $modelRolesContent `
    -SkillSources $skillSources

$geminiContent = Build-AdapterContent `
    -Title 'GEMINI Context' `
    -Preamble @(
        'This is the repo-local adapter for Gemini CLI.',
        'Active skills from `.dev/project.md` are inlined below so this repo can override the broader global GAL context without editing `~/.gemini/GEMINI.md`.',
        'This generator only inlines the exact listed skills and does not mutate `~/.gemini/gal-context.md` or any other machine-level configuration.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -ModelRolesContent $modelRolesContent `
    -SkillSources $skillSources `
    -IncludeSkillBodies

$agentsContent = Build-AdapterContent `
    -Title 'GAL Agent Instructions' `
    -Preamble @(
        'This is the canonical cross-CLI shared contract for Copilot CLI, Codex CLI, Gemini CLI (via settings bridge), and Claude Code CLI.',
        'Active skills from `.dev/project.md` are inlined below because Codex and Claude Code have no machine-level skill install.',
        'This file is generated by `gal sync`. Do not edit manually.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -ModelRolesContent $modelRolesContent `
    -SkillSources $skillSources `
    -IncludeSkillBodies

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($copilotPath, $copilotContent, $utf8NoBom)
[System.IO.File]::WriteAllText($geminiPath, $geminiContent, $utf8NoBom)
[System.IO.File]::WriteAllText($agentsPath, $agentsContent, $utf8NoBom)

Write-Host "Sync-DevContext completed for: $resolvedTarget"
Write-Host "- Generated: .github/copilot-instructions.md"
Write-Host "- Generated: GEMINI.md"
Write-Host "- Generated: AGENTS.md"
Write-Host "- Active Skills: $($activeSkills -join ', ')"