param(
    [string]$TargetPath = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot
$resolvedTarget = (Resolve-Path $TargetPath).Path

$projectPath = Join-Path $resolvedTarget ".dev\project.md"
$copilotDir = Join-Path $resolvedTarget ".github"
$copilotPath = Join-Path $copilotDir "copilot-instructions.md"
$geminiPath = Join-Path $resolvedTarget "GEMINI.md"
$claudePath = Join-Path $resolvedTarget "CLAUDE.md"
$agentsPath = Join-Path $resolvedTarget "AGENTS.md"

$pluginRoot = Join-Path $repoRoot "plugins\gal-core"
$conventionsDir = Join-Path $pluginRoot "conventions"
$workflowPath = Join-Path $pluginRoot "workflows\coding.md"
$skillsRoot = Join-Path $pluginRoot "skills"

function Read-NormalizedFile([string]$Path) {
    if (-not (Test-Path $Path)) {
        throw "Missing required source file: $Path"
    }

    $content = Get-Content -Path $Path -Raw
    return ($content -replace "`r`n", "`n") -replace "`r", "`n"
}

function Get-AllSkillSources() {
    if (-not (Test-Path $skillsRoot)) {
        return @()
    }
    $resolved = [System.Collections.Generic.List[object]]::new()
    foreach ($skillDir in (Get-ChildItem -Path $skillsRoot -Directory | Sort-Object Name)) {
        $skillFile = Join-Path $skillDir.FullName "SKILL.md"
        if (Test-Path $skillFile) {
            $resolved.Add([pscustomobject]@{
                Name = $skillDir.Name
            })
        }
    }
    return @($resolved)
}

function Get-ProjectConventionFileNames {
    $defaultNames = @('conventions.md','token-budget.md','working-hours.md')
    if (-not (Test-Path $projectPath)) {
        return $defaultNames
    }

    $languageLine = Get-Content $projectPath | Where-Object { $_ -match '^\|\s*Language\s*\|' } | Select-Object -First 1
    if ([string]::IsNullOrWhiteSpace($languageLine)) {
        return @('conventions.md','csharp.md','go.md','rust.md','token-budget.md','typescript.md','working-hours.md')
    }

    $fileNames = [System.Collections.Generic.List[string]]::new()
    foreach ($name in $defaultNames) {
        $fileNames.Add($name)
    }

    $languageText = $languageLine.ToLowerInvariant()
    $languageMap = [ordered]@{
        'c#' = 'csharp.md'
        '.net' = 'csharp.md'
        'typescript' = 'typescript.md'
        'javascript' = 'typescript.md'
        'go' = 'go.md'
        'golang' = 'go.md'
        'rust' = 'rust.md'
    }

    foreach ($key in $languageMap.Keys) {
        if ($languageText.Contains($key)) {
            $name = $languageMap[$key]
            if ($fileNames -notcontains $name) {
                $fileNames.Add($name)
            }
        }
    }

    return @($fileNames)
}

function Get-ConventionSources() {
    $selectedConventionNames = Get-ProjectConventionFileNames
    return Get-ChildItem -Path $conventionsDir -File -Filter '*.md' |
        Sort-Object Name |
        Where-Object { $selectedConventionNames -contains $_.Name } |
        ForEach-Object {
            [pscustomobject]@{
                Label   = "conventions/$($_.Name)"
                Content = Read-NormalizedFile -Path $_.FullName
            }
        }
}

function Add-SourceBlock([System.Collections.Generic.List[string]]$Lines, [string]$Label, [string]$Content) {
    $Lines.Add("<!-- Source: $Label -->")
    $Lines.Add($Content.Trim())
    $Lines.Add("")
}

function Add-SkillIndex([System.Collections.Generic.List[string]]$Lines, [object[]]$SkillSources) {
    if ($null -eq $SkillSources -or $SkillSources.Count -eq 0) {
        return
    }

    $Lines.Add('## Repo Skills')
    $Lines.Add('')
    $Lines.Add('The following repo-local skills are available by name. Read the corresponding `skills/<name>/SKILL.md` file when full instructions are needed.')
    $Lines.Add('')
    foreach ($skill in $SkillSources) {
        $Lines.Add(('- `{0}` - `skills/{0}/SKILL.md`' -f $skill.Name))
    }
    $Lines.Add('')
}

function Build-AdapterContent(
    [string]$Title,
    [string[]]$Preamble,
    [string]$ProjectContent,
    [object[]]$ConventionSources,
    [string]$WorkflowContent,
    [object[]]$SkillSources,
    [switch]$IncludeSkillIndex
) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# $Title")
    $lines.Add("")
    $lines.Add('> Generated by `/gal init`. Do not edit manually.')
    $lines.Add('> Update `.dev/project.md` or the GAL source docs, then rerun `/gal init`.')
    $lines.Add("")
    $lines.Add("## Adapter Rules")
    $lines.Add("")
    foreach ($entry in $Preamble) {
        $lines.Add("- $entry")
    }
    $lines.Add("")

    Add-SourceBlock -Lines $lines -Label '.dev/project.md' -Content $ProjectContent
    foreach ($convention in $ConventionSources) {
        Add-SourceBlock -Lines $lines -Label $convention.Label -Content $convention.Content
    }
    Add-SourceBlock -Lines $lines -Label 'workflows/coding.md' -Content $WorkflowContent

    if ($IncludeSkillIndex) {
        Add-SkillIndex -Lines $lines -SkillSources $SkillSources
    }

    return (($lines -join "`n").TrimEnd() + "`n")
}

$projectContent = Read-NormalizedFile -Path $projectPath
$skillSources = Get-AllSkillSources
$conventionSources = Get-ConventionSources
$workflowContent = Read-NormalizedFile -Path $workflowPath

[System.IO.Directory]::CreateDirectory($copilotDir) | Out-Null

$copilotContent = Build-AdapterContent `
    -Title 'Copilot Instructions' `
    -Preamble @(
        'This is the repo-local adapter for GitHub Copilot.',
        'Skills in this repo''s `skills/` directory are listed by name only — Copilot discovers GAL commands from the global runtime install.',
        'This generator never modifies `~/.copilot/skills/` or any other machine-level configuration.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -SkillSources $skillSources

$geminiContent = Build-AdapterContent `
    -Title 'GEMINI Context' `
    -Preamble @(
        'This is the repo-local Google CLI adapter consumed by Antigravity CLI and retained under the `GEMINI.md` filename for Google-runtime compatibility.',
        'Repo-local skills are indexed below by name so Antigravity CLI and remaining Google CLI surfaces can discover them without duplicating every skill body in the adapter.',
        'This generator does not mutate `~/.gemini/gal-context.md` or other machine-level Google CLI configuration.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -SkillSources $skillSources `
    -IncludeSkillIndex

$claudeContent = Build-AdapterContent `
    -Title 'CLAUDE Context' `
    -Preamble @(
        'This is the repo-local adapter for Claude Code.',
        'Repo-local skills are indexed below by name so Claude Code can find the right skill file without duplicating every skill body in the adapter.',
        'This generator only writes repo-local adapters such as `CLAUDE.md`; machine-level Claude setup belongs to `Setup-Machine`.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -SkillSources $skillSources `
    -IncludeSkillIndex

$agentsContent = Build-AdapterContent `
    -Title 'GAL Agent Instructions' `
    -Preamble @(
        'This is the shared cross-CLI contract generated from repo sources for Copilot CLI, Codex CLI, Antigravity workspace rules, remaining Google CLI bridges, and Claude Code CLI.',
        'Repo-local skills are indexed below by name so runtimes can discover the right skill file without duplicating every skill body in this shared adapter.',
        'This file is generated by `/gal init`. Do not edit manually.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -SkillSources $skillSources `
    -IncludeSkillIndex

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($copilotPath, $copilotContent, $utf8NoBom)
[System.IO.File]::WriteAllText($geminiPath, $geminiContent, $utf8NoBom)
[System.IO.File]::WriteAllText($claudePath, $claudeContent, $utf8NoBom)
[System.IO.File]::WriteAllText($agentsPath, $agentsContent, $utf8NoBom)

Write-Host "Sync-DevContext completed for: $resolvedTarget"
Write-Host "- Generated: .github/copilot-instructions.md"
Write-Host "- Generated: GEMINI.md"
Write-Host "- Generated: CLAUDE.md"
Write-Host "- Generated: AGENTS.md"
if ($skillSources.Count -gt 0) {
    Write-Host "- Indexed skills: $(($skillSources | ForEach-Object { $_.Name }) -join ', ')"
}
else {
    Write-Host "- No skills/ directory found; no skills indexed."
}