param(
    [string]$TargetPath = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot
$resolvedTarget = (Resolve-Path $TargetPath).Path

$projectPath = Join-Path $resolvedTarget ".dev\project.md"
$copilotDir = Join-Path $resolvedTarget ".github"
$copilotPath = Join-Path $copilotDir "copilot-instructions.md"
$geminiPath = Join-Path $resolvedTarget "GEMINI.md"
$agentsPath = Join-Path $resolvedTarget "AGENTS.md"

$conventionsDir = Join-Path $repoRoot "conventions"
$workflowPath = Join-Path $repoRoot "workflows\coding.md"
$modelRolesPath = Join-Path $repoRoot "model-roles.md"
$skillsRoot = Join-Path $repoRoot "skills"

function Read-NormalizedFile([string]$Path) {
    if (-not (Test-Path $Path)) {
        throw "Missing required source file: $Path"
    }

    $content = Get-Content -Path $Path -Raw
    return ($content -replace "`r`n", "`n") -replace "`r", "`n"
}

function Get-MarkdownSection([string]$Content, [string]$Heading) {
    $pattern = "(?ms)^##\s+{0}\s*$\n(?<body>.*?)(?=^##\s+|\z)" -f [regex]::Escape($Heading)
    $match = [regex]::Match($Content, $pattern)
    if (-not $match.Success) {
        return $null
    }

    return $match.Groups['body'].Value.Trim()
}

function Get-AllSkillSources() {
    if (-not (Test-Path $skillsRoot)) {
        return @()
    }
    $resolved = [System.Collections.Generic.List[object]]::new()
    foreach ($skillDir in (Get-ChildItem -Path $skillsRoot -Directory | Sort-Object Name)) {
        $skillFile = Join-Path $skillDir.FullName "SKILL.md"
        if (Test-Path $skillFile) {
            $resolved.Add([pscustomobject]@{
                Name    = $skillDir.Name
                Path    = $skillFile
                Content = Read-NormalizedFile -Path $skillFile
            })
        }
    }
    return @($resolved)
}

function Get-ConventionSources() {
    return Get-ChildItem -Path $conventionsDir -File -Filter '*.md' |
        Sort-Object Name |
        ForEach-Object {
            [pscustomobject]@{
                Label   = "conventions/$($_.Name)"
                Content = Read-NormalizedFile -Path $_.FullName
            }
        }
}

function Add-SourceBlock([System.Collections.Generic.List[string]]$Lines, [string]$Label, [string]$Content) {
    $Lines.Add("<!-- Source: $Label -->")
    $Lines.Add($Content.Trim())
    $Lines.Add("")
}

function Build-AdapterContent(
    [string]$Title,
    [string[]]$Preamble,
    [string]$ProjectContent,
    [object[]]$ConventionSources,
    [string]$WorkflowContent,
    [string]$ModelRolesContent,
    [object[]]$SkillSources,
    [switch]$IncludeSkillBodies
) {
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# $Title")
    $lines.Add("")
    $lines.Add('> Generated by `/gal init`. Do not edit manually.')
    $lines.Add('> Update `.dev/project.md` or the GAL source docs, then rerun `/gal init`.')
    $lines.Add("")
    $lines.Add("## Adapter Rules")
    $lines.Add("")
    foreach ($entry in $Preamble) {
        $lines.Add("- $entry")
    }
    $lines.Add("")

    Add-SourceBlock -Lines $lines -Label '.dev/project.md' -Content $ProjectContent
    foreach ($convention in $ConventionSources) {
        Add-SourceBlock -Lines $lines -Label $convention.Label -Content $convention.Content
    }
    Add-SourceBlock -Lines $lines -Label 'workflows/coding.md' -Content $WorkflowContent
    Add-SourceBlock -Lines $lines -Label 'model-roles.md' -Content $ModelRolesContent

    if ($IncludeSkillBodies) {
        foreach ($skill in $SkillSources) {
            Add-SourceBlock -Lines $lines -Label ("skills/{0}/SKILL.md" -f $skill.Name) -Content $skill.Content
        }
    }

    return (($lines -join "`n").TrimEnd() + "`n")
}

$projectContent = Read-NormalizedFile -Path $projectPath
$skillSources = Get-AllSkillSources
$conventionSources = Get-ConventionSources
$workflowContent = Read-NormalizedFile -Path $workflowPath
$modelRolesContent = Read-NormalizedFile -Path $modelRolesPath

[System.IO.Directory]::CreateDirectory($copilotDir) | Out-Null

$copilotContent = Build-AdapterContent `
    -Title 'Copilot Instructions' `
    -Preamble @(
        'This is the repo-local adapter for GitHub Copilot.',
        'Skills in this repo''s `skills/` directory are listed by name only — Copilot discovers GAL commands from the global runtime install.',
        'This generator never modifies `~/.copilot/skills/` or any other machine-level configuration.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -ModelRolesContent $modelRolesContent `
    -SkillSources $skillSources

$geminiContent = Build-AdapterContent `
    -Title 'GEMINI Context' `
    -Preamble @(
        'This is the repo-local adapter for Gemini CLI.',
        'All skills in this repo''s `skills/` directory are inlined below so Gemini has full skill context without a machine-level install.',
        'This generator only inlines repo-local skills and does not mutate `~/.gemini/gal-context.md` or any other machine-level configuration.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -ModelRolesContent $modelRolesContent `
    -SkillSources $skillSources `
    -IncludeSkillBodies

$agentsContent = Build-AdapterContent `
    -Title 'GAL Agent Instructions' `
    -Preamble @(
        'This is the shared cross-CLI contract generated from repo sources for Copilot CLI, Codex CLI, Gemini CLI (via settings bridge), and Claude Code CLI.',
        'All skills in this repo''s `skills/` directory are inlined below because Codex and Claude Code have no machine-level skill install.',
        'This file is generated by `/gal init`. Do not edit manually.'
    ) `
    -ProjectContent $projectContent `
    -ConventionSources $conventionSources `
    -WorkflowContent $workflowContent `
    -ModelRolesContent $modelRolesContent `
    -SkillSources $skillSources `
    -IncludeSkillBodies

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($copilotPath, $copilotContent, $utf8NoBom)
[System.IO.File]::WriteAllText($geminiPath, $geminiContent, $utf8NoBom)
[System.IO.File]::WriteAllText($agentsPath, $agentsContent, $utf8NoBom)

Write-Host "Sync-DevContext completed for: $resolvedTarget"
Write-Host "- Generated: .github/copilot-instructions.md"
Write-Host "- Generated: GEMINI.md"
Write-Host "- Generated: AGENTS.md"
Write-Host "- Inlined skills: $(($skillSources | ForEach-Object { $_.Name }) -join ', ')"