#!/usr/bin/env bash

set -euo pipefail

target_path="${1:-$PWD}"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

if [[ ! -d "$target_path" ]]; then
  echo "Target path does not exist: $target_path" >&2
  exit 1
fi

target_path="$(cd "$target_path" && pwd)"
project_path="$target_path/.dev/project.md"
copilot_dir="$target_path/.github"
copilot_path="$copilot_dir/copilot-instructions.md"
gemini_path="$target_path/GEMINI.md"
conventions_dir="$repo_root/conventions"
workflow_path="$repo_root/workflows/coding.md"
model_roles_path="$repo_root/model-roles.md"
skills_root="$repo_root/skills"

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing required source file: $path" >&2
    exit 1
  fi
}

trim() {
  local value="$1"
  value="${value#${value%%[![:space:]]*}}"
  value="${value%${value##*[![:space:]]}}"
  printf '%s' "$value"
}

extract_section() {
  local heading="$1"
  local path="$2"
  awk -v heading="$heading" '
    $0 ~ "^##[[:space:]]+" heading "[[:space:]]*$" { in_section=1; next }
    in_section && $0 ~ "^##[[:space:]]+" { exit }
    in_section { print }
  ' "$path"
}

append_source_block() {
  local output_path="$1"
  local label="$2"
  local source_path="$3"
  printf '<!-- Source: %s -->\n' "$label" >> "$output_path"
  cat "$source_path" >> "$output_path"
  printf '\n\n' >> "$output_path"
}

build_adapter() {
  local output_path="$1"
  local title="$2"
  local include_skill_bodies="$3"
  shift 3
  local preamble=("$@")

  : > "$output_path"
  printf '# %s\n\n' "$title" >> "$output_path"
  printf '> Generated by `gal sync`. Do not edit manually.\n' >> "$output_path"
  printf '> Update `.dev/project.md` or the GAL source docs, then rerun `/gal sync`.\n\n' >> "$output_path"
  printf '## Adapter Rules\n\n' >> "$output_path"
  local entry
  for entry in "${preamble[@]}"; do
    printf -- '- %s\n' "$entry" >> "$output_path"
  done
  printf '\n## Selected Active Skills\n\n' >> "$output_path"
  local skill
  for skill in "${active_skills[@]}"; do
    printf -- '- `%s`\n' "$skill" >> "$output_path"
  done
  printf '\n' >> "$output_path"

  append_source_block "$output_path" ".dev/project.md" "$project_path"

  local source_file
  for source_file in "${convention_files[@]}"; do
    append_source_block "$output_path" "conventions/$(basename "$source_file")" "$source_file"
  done

  append_source_block "$output_path" "workflows/coding.md" "$workflow_path"
  append_source_block "$output_path" "model-roles.md" "$model_roles_path"

  if [[ "$include_skill_bodies" == "true" ]]; then
    for skill in "${active_skills[@]}"; do
      append_source_block "$output_path" "skills/$skill/SKILL.md" "$skills_root/$skill/SKILL.md"
    done
  fi
}

require_file "$project_path"
require_file "$workflow_path"
require_file "$model_roles_path"

section_content="$(extract_section "Active Skills" "$project_path")"
if [[ -z "$(trim "$section_content")" ]]; then
  echo "Missing required '## Active Skills' section in .dev/project.md. Review the file, list exact GAL skill folder names, then rerun /gal sync." >&2
  exit 1
fi

active_skills=()
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*-[[:space:]]+(.+)$ ]]; then
    skill_name="$(trim "${BASH_REMATCH[1]}")"
    skill_name="${skill_name//\`/}"
    if [[ -n "$skill_name" ]]; then
      active_skills+=("$skill_name")
    fi
  fi
done <<< "$section_content"

if [[ ${#active_skills[@]} -eq 0 ]]; then
  echo "The '## Active Skills' section in .dev/project.md is empty. Add one exact skill folder name per bullet before running /gal sync." >&2
  exit 1
fi

declare -A seen_skills=()
for skill_name in "${active_skills[@]}"; do
  if [[ -n "${seen_skills[$skill_name]:-}" ]]; then
    echo "Duplicate Active Skills entries found in .dev/project.md: $skill_name. Keep each skill only once." >&2
    exit 1
  fi
  seen_skills[$skill_name]=1

  if [[ ! -d "$skills_root/$skill_name" ]]; then
    echo "Active skill '$skill_name' does not exist under $skills_root. Use exact folder names from the GAL skills directory." >&2
    exit 1
  fi

  require_file "$skills_root/$skill_name/SKILL.md"
done

mapfile -t convention_files < <(find "$conventions_dir" -maxdepth 1 -type f -name '*.md' | sort)
mkdir -p "$copilot_dir"

build_adapter \
  "$copilot_path" \
  "Copilot Instructions" \
  false \
  "This is the repo-local adapter for GitHub Copilot." \
  "Active skills are validated from .dev/project.md but not inlined here because Copilot discovers GAL skills from the global runtime install." \
  "This generator never modifies ~/.copilot/skills/ or any other machine-level configuration."

build_adapter \
  "$gemini_path" \
  "GEMINI Context" \
  true \
  "This is the repo-local adapter for Gemini CLI." \
  "Active skills from .dev/project.md are inlined below so this repo can override the broader global GAL context without editing ~/.gemini/GEMINI.md." \
  "This generator only inlines the exact listed skills and does not mutate ~/.gemini/gal-context.md or any other machine-level configuration."

echo "Sync-DevContext completed for: $target_path"
echo "- Generated: .github/copilot-instructions.md"
echo "- Generated: GEMINI.md"
echo "- Active Skills: ${active_skills[*]}"