<#
.SYNOPSIS
        Removes GAL-managed links and generated artifacts installed by `gal setup`.

.DESCRIPTION
        Thin wrapper around the `gal setup --uninstall` flow.

        Removes GAL-managed artifacts such as:
      - ~/.copilot/agents/*.agent.md symlinks
      - ~/.copilot/skills/*/ symlinks
            - <repo>/.agents/skills/*/ symlinks (workspace reusable skills for Antigravity/Gemini compatibility)
            - ~/.agents/skills/*/ symlinks (shared reusable skills for Codex/OpenCode compatibility)
            - ~/.copilot/skills/gal*/ symlinks (GAL command skills)
            - ~/.codex/skills/gal*/ symlinks (GAL command skills)
            - ~/.gemini/commands/*.toml generated by GAL
            - ~/.gal/generated/providers/claude/managed.json lifecycle metadata
            - legacy ~/.claude/skills/*/ and ~/.claude/commands/*.md GAL-owned leftovers, when present
      - ~/.copilot/gal/ symlink (GAL_ROOT)
      - ~/.gemini/gal/ symlink (GAL_ROOT)
      - commands/*/SKILL.md (baked from template)
      - ~/.gemini/gal-context.md

        User-owned runtime settings and MCP config files are preserved during uninstall.

        Use `-Purge` only for an explicit destructive reset of preserved machine-local
        state under `~/.gal/`.

.PARAMETER DryRun
    Show what would be removed without making changes.

.PARAMETER Purge
    Also remove preserved machine-local state under `~/.gal/`.

.PARAMETER ConfirmPurge
    Required together with `-Purge` for destructive execution. Not needed with `-DryRun`.

.EXAMPLE
    .\scripts\Uninstall-Machine.ps1
    .\scripts\Uninstall-Machine.ps1 -DryRun
    .\scripts\Uninstall-Machine.ps1 -Purge -DryRun
    .\scripts\Uninstall-Machine.ps1 -Purge -ConfirmPurge
#>
param(
    [switch]$DryRun,
    [switch]$Purge,
    [switch]$ConfirmPurge
)

$galExe = (Get-Command 'gal.exe' -ErrorAction SilentlyContinue | Select-Object -First 1).Source
if ([string]::IsNullOrWhiteSpace($galExe)) {
    throw 'gal.exe not found on PATH.'
}

$galArgs = @('setup', '--uninstall')
if ($DryRun) { $galArgs += '--dry-run' }
if ($Purge) { $galArgs += '--purge' }
if ($ConfirmPurge) { $galArgs += '--confirm-purge' }
& $galExe @galArgs
exit $LASTEXITCODE
