<#
.SYNOPSIS
        Removes GAL-managed links and generated artifacts installed by Setup-Machine.ps1.

.DESCRIPTION
        Thin wrapper around the concern-based `Setup-Machine.ps1 -Uninstall` flow.

        Removes GAL-managed artifacts such as:
      - ~/.copilot/agents/*.agent.md symlinks
      - ~/.copilot/skills/*/ symlinks
            - <repo>/.agents/skills/*/ symlinks (workspace reusable skills for Antigravity/Gemini compatibility)
            - ~/.agents/skills/*/ symlinks (shared reusable skills for Codex/OpenCode compatibility)
            - ~/.claude/skills/*/ symlinks
            - ~/.copilot/skills/gal*/ symlinks (GAL command skills)
            - ~/.codex/skills/gal*/ symlinks (GAL command skills)
            - ~/.gemini/commands/*.toml generated by GAL
            - ~/.claude/commands/*.md generated by GAL
      - ~/.copilot/gal/ symlink (GAL_ROOT)
      - ~/.gemini/gal/ symlink (GAL_ROOT)
      - commands/*/SKILL.md (baked from template)
      - ~/.gemini/gal-context.md

        User-owned runtime settings and MCP config files are preserved during uninstall.

.PARAMETER DryRun
    Show what would be removed without making changes.

.EXAMPLE
    .\scripts\Uninstall-Machine.ps1
    .\scripts\Uninstall-Machine.ps1 -DryRun
#>
param(
    [switch]$DryRun
)

& "$PSScriptRoot\Setup-Machine.ps1" -Uninstall @PSBoundParameters
