//! (file) projection backend — turns skills/commands into runtime surface files.
//!
//! Owns the AGY + Claude skill/file projection backends.

pub mod agy;
pub mod codex_agent;
pub mod tool_map;

mod support;
#[cfg(test)]
mod tests;

// SkillsProjectionHealthCheck and CodexSkillsConfigCheck are cross-crate consumer
// surfaces (cli doctor); the rest are crate-internal helpers used by the
// update_* drivers below.
pub use support::{CodexSkillsConfigCheck, SkillsProjectionHealthCheck};
use support::*;

use codex_agent::{generate_discuss_skill_md, parse_agent_meta, CONSULT_GOLEM_NAMES};
use gal_foundation::json_util::read_json_map;
use gal_foundation::platform::atomic_swap;
use gal_foundation::render::create_temp_render_dir;
use gal_foundation::runtime::VALID_RUNTIMES;
use serde_json::Value;
use std::ffi::OsStr;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub(crate) const GAL_MANAGED_FILE_HEADER: &str =
    "# Generated by GAL Setup-Machine. Do not edit manually.";

/// Golem roles that are orchestration-only and must not be exposed as native subagents.
/// These remain in KNOWN_GOLEMS so pipeline can resolve them; only native-subagent projection
/// (Claude `agents/` and Codex `~/.codex/agents/`) excludes them.
const ORCHESTRATED_ONLY_GOLEM_NAMES: &[&str] = &[
    "golem-implementer",
    "golem-tester",
    "golem-auditor",
    "golem-researcher",
];

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionWarning {
    pub message: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionReport {
    pub written_files: Vec<PathBuf>,
    pub removed_paths: Vec<PathBuf>,
    pub created_links: Vec<PathBuf>,
    pub warnings: Vec<ProjectionWarning>,
}

/// A single skill/agent source directory registered for projection.
///
/// `id` uniquely identifies the source (e.g. `"gal-core"`, `"my-bundle"`).
/// `persistent` marks sources whose projected artifacts must not be pruned
/// when the source is temporarily absent from the active invocation set.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionSource {
    pub root: PathBuf,
    pub id: String,
    pub persistent: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillUpdateOptions {
    pub repo_root: PathBuf,
    /// Ordered source list; gal-core must always be first (baseline).
    /// Single-source callers pass a 1-element `Vec`.
    pub sources: Vec<ProjectionSource>,
    pub user_home: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub dry_run: bool,
    pub replace: bool,
}

pub type CommandUpdateOptions = SkillUpdateOptions;

#[derive(Debug, Error)]
pub enum AdapterError {
    #[error("{0}")]
    Message(String),
    #[error("{0}")]
    Io(#[from] io::Error),
}

/// Assemble the ordered projection source list for a machine update or sync.
///
/// gal-core (the canonical plugin root) is always first and persistent.
/// Additional installed sources (bundles, personal layer) are appended
/// when registered — reserved for extension in the bundle-installation layer.
pub fn collect_projection_sources(source_root: &Path) -> Vec<ProjectionSource> {
    vec![ProjectionSource {
        root: source_root.to_path_buf(),
        id: "gal-core".to_string(),
        persistent: true,
    }]
}

/// Assemble a `SkillUpdateOptions` for machine-level refresh.
///
/// Combines `collect_projection_sources` (gal-core single source) and
/// `load_selected_runtimes` (falls back to all 5 runtimes when no
/// `install-state.json` exists — the only current behavior post-fix-cli).
///
/// This is the slim options builder introduced for `gal refresh`; it does
/// not change any existing projection fn behavior.
pub fn machine_skill_options(
    source_root: &Path,
    user_home: &Path,
) -> Result<SkillUpdateOptions, AdapterError> {
    let sources = collect_projection_sources(source_root);
    let selected_runtimes = load_selected_runtimes(user_home)?;
    Ok(SkillUpdateOptions {
        repo_root: source_root.to_path_buf(),
        sources,
        user_home: user_home.to_path_buf(),
        selected_runtimes,
        dry_run: false,
        replace: true,
    })
}

pub fn load_selected_runtimes(user_home: &Path) -> Result<Vec<String>, AdapterError> {
    let install_state = user_home.join(".gal").join("install-state.json");
    let raw = read_json_map(&install_state)?;
    let mut selected = raw
        .get("selectedRuntimes")
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .map(|value| value.trim().to_ascii_lowercase())
                .filter(|value| VALID_RUNTIMES.contains(&value.as_str()))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    if selected.is_empty() {
        selected = VALID_RUNTIMES
            .iter()
            .map(|value| (*value).to_string())
            .collect();
    }
    selected.sort();
    selected.dedup();
    Ok(selected)
}

#[derive(Debug, Clone)]
struct SkillContext {
    opts: SkillUpdateOptions,
}

impl SkillContext {
    fn new(opts: SkillUpdateOptions) -> Self {
        Self { opts }
    }

    fn primary_source_root(&self) -> &Path {
        &self.opts.sources[0].root
    }

    fn copilot_root(&self) -> PathBuf {
        self.opts.user_home.join(".copilot")
    }

    fn gemini_root(&self) -> PathBuf {
        self.opts.user_home.join(".gemini")
    }

    fn codex_root(&self) -> PathBuf {
        self.opts.user_home.join(".codex")
    }

    fn codex_agents_target(&self) -> PathBuf {
        self.codex_root().join("agents")
    }

    fn antigravity_root(&self) -> PathBuf {
        self.gemini_root().join("antigravity-cli")
    }

    fn gal_home(&self) -> PathBuf {
        self.opts.user_home.join(".gal")
    }

    fn lockfile_path(&self) -> PathBuf {
        self.gal_home().join("state").join("plugins.lock.json")
    }

    fn gal_source_root(&self) -> PathBuf {
        self.gal_home().join("source")
    }

    fn canonical_plugin_root(&self) -> PathBuf {
        self.gal_home().join("plugins").join("gal")
    }

    fn canonical_commands_root(&self) -> PathBuf {
        self.canonical_plugin_root().join("commands")
    }

    fn agents_target(&self) -> PathBuf {
        self.copilot_root().join("agents")
    }

    fn copilot_skills_target(&self) -> PathBuf {
        self.copilot_root().join("skills")
    }

    fn codex_skills_target(&self) -> PathBuf {
        self.codex_root().join("skills")
    }

    fn gemini_commands_target(&self) -> PathBuf {
        self.gemini_root().join("commands")
    }

    fn gemini_skills_target(&self) -> PathBuf {
        self.gemini_root().join("skills")
    }

    fn claude_commands_target(&self) -> PathBuf {
        self.opts.user_home.join(".claude").join("commands")
    }

    fn workspace_skills_target(&self) -> PathBuf {
        self.opts.repo_root.join(".agents").join("skills")
    }

    fn shared_skills_target(&self) -> PathBuf {
        self.opts.user_home.join(".agents").join("skills")
    }

    fn opencode_root(&self) -> PathBuf {
        self.opts.user_home.join(".config").join("opencode")
    }

    fn opencode_commands_target(&self) -> PathBuf {
        self.opencode_root().join("commands")
    }

    fn gal_config_root(&self) -> PathBuf {
        self.gal_home().join("config")
    }

    fn config_file(&self) -> PathBuf {
        self.gal_config_root().join("config.json")
    }

    fn has_runtime(&self, runtime: &str) -> bool {
        self.opts.selected_runtimes.iter().any(|rt| rt == runtime)
    }
}

pub fn run_update_skills(opts: &SkillUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_skills(&ctx, &mut report)?;
    Ok(report)
}

pub fn run_update_commands(opts: &CommandUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_commands(&ctx, &mut report)?;
    Ok(report)
}

fn update_skills(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    use std::collections::BTreeMap;

    // Collect skills and agents from all sources in order (gal-core first = baseline).
    // Single-source (1-element Vec) degrades to the same result as before — byte-identical.
    // Collision warnings are added in the next implementation step.
    let mut skill_names: Vec<String> = Vec::new();
    let mut skill_source_id: BTreeMap<String, String> = BTreeMap::new();
    let mut agent_paths: Vec<PathBuf> = Vec::new();
    let mut agent_fname_source_id: BTreeMap<String, String> = BTreeMap::new();

    for src in &ctx.opts.sources {
        for name in list_named_children(&src.root.join("skills"))? {
            if let Some(owner) = skill_source_id.get(&name) {
                // Collision: core-wins + additive-only. Non-core sources may only add
                // new names; a clash with any prior source is skipped with a warning.
                report.warnings.push(ProjectionWarning {
                    message: format!(
                        "skill '{}' from source '{}' skipped: name already claimed by source '{}'",
                        name, src.id, owner
                    ),
                });
                continue;
            }
            skill_names.push(name.clone());
            skill_source_id.insert(name, src.id.clone());
        }
        for path in list_files_with_extension(&src.root.join("agents"), "agent.md")? {
            let fname = path
                .file_name()
                .and_then(OsStr::to_str)
                .unwrap_or("")
                .to_string();
            if let Some(owner) = agent_fname_source_id.get(&fname) {
                // Collision: core-wins + additive-only. Non-core sources may only add
                // new agent files; a clash with any prior source is skipped with a warning.
                report.warnings.push(ProjectionWarning {
                    message: format!(
                        "agent '{}' from source '{}' skipped: name already claimed by source '{}'",
                        fname, src.id, owner
                    ),
                });
                continue;
            }
            agent_paths.push(path);
            agent_fname_source_id.insert(fname, src.id.clone());
        }
    }

    let mut registry = ManagedArtifactRegistry::load(&ctx.lockfile_path(), report);
    registry.replace_category(MANAGED_AGENT_PATHS);
    registry.replace_category(MANAGED_CODEX_AGENT_PATHS);
    registry.replace_category(MANAGED_DISCUSS_SKILL_PATHS);
    registry.replace_category(MANAGED_LEGACY_PATHS);
    registry.replace_category(MANAGED_SKILL_PATHS);

    let shared_skills = ctx.opts.user_home.join(".agents").join("skills");
    let should_project_shared_skills = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "codex" || rt == "opencode");
    if should_project_shared_skills {
        ensure_dir(&shared_skills, ctx.opts.dry_run)?;
        for skill_name in &skill_names {
            let source_id = skill_source_id
                .get(skill_name)
                .map(String::as_str)
                .unwrap_or("gal-core");
            let source_root = ctx
                .opts
                .sources
                .iter()
                .find(|s| s.id == source_id)
                .map(|s| s.root.as_path())
                .unwrap_or_else(|| ctx.primary_source_root());
            let source = source_root.join("skills").join(skill_name);
            let link = shared_skills.join(skill_name);
            // Materialized copy (not a junction) so external deletion of the shared
            // namespace can only go stale, never wipe the whole projection in one shot.
            // A pre-existing real directory that is neither lockfile-attributed nor
            // GAL-content-marked is a genuine user collision and is left untouched.
            let is_link = gal_foundation::platform::is_symlink_or_junction(&link);
            if link.exists()
                && !is_link
                && !registry.is_managed(&link)
                && !is_gal_owned_real_path(&link)
            {
                report.warnings.push(ProjectionWarning {
                    message: format!("preserved user-owned path: {}", link.display()),
                });
                continue;
            }
            materialize_skill_dir(&source, &link, ctx.opts.dry_run, report)?;
            registry.mark_with_source(MANAGED_SKILL_PATHS, &link, source_id);
        }
        let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
        // Include discuss-<role> dir names when codex is selected so the shared-skills prune
        // does not evict discuss-skill directories (they live in the same root).
        let discuss_dir_names: Vec<String> = if ctx.has_runtime("codex") {
            CONSULT_GOLEM_NAMES
                .iter()
                .map(|n| format!("discuss-{n}"))
                .collect()
        } else {
            Vec::new()
        };
        prune_stale_links(
            &shared_skills,
            skill_names
                .iter()
                .map(String::as_str)
                .chain(discuss_dir_names.iter().map(String::as_str)),
            ctx.opts.dry_run,
            report,
            &registry,
            &installed_ids,
        )?;
    } else {
        let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
        prune_stale_links(
            &shared_skills,
            std::iter::empty(),
            ctx.opts.dry_run,
            report,
            &registry,
            &installed_ids,
        )?;
    }

    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "copilot") {
        let gal_root = ctx.copilot_root().join("gal");
        ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
        ensure_dir_link(
            &ctx.gal_home(),
            &gal_root,
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }
    let should_keep_source_link = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "gemini" || rt == "antigravity");
    if should_keep_source_link {
        ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
        ensure_dir_link(
            &ctx.opts.repo_root,
            &ctx.gal_source_root(),
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }
    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "gemini") {
        let gal_root = ctx.gemini_root().join("gal");
        ensure_dir_link(
            &ctx.gal_source_root(),
            &gal_root,
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }
    if ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "antigravity")
    {
        let gal_root = ctx.antigravity_root().join("gal");
        ensure_dir_link(
            &ctx.gal_source_root(),
            &gal_root,
            ctx.opts.replace,
            ctx.opts.dry_run,
            report,
        )?;
    }

    let agents_target = ctx.agents_target();
    ensure_dir(&agents_target, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let fname = agent_path
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| AdapterError::Message("invalid agent file name".into()))?;
        // Orchestrated-only roles must not be exposed as native Claude subagents.
        let golem_name = fname.trim_end_matches(".agent.md");
        if ORCHESTRATED_ONLY_GOLEM_NAMES.contains(&golem_name) {
            continue;
        }
        let target = agents_target.join(fname);
        // Write format-converted content (abstract tools → Claude tool names) rather
        // than a verbatim symlink so consult subagents receive valid tool grants.
        let raw = fs::read_to_string(agent_path)?;
        let converted = tool_map::rewrite_agent_tools_for_claude(&raw);
        write_text(&target, &converted, ctx.opts.dry_run)?;
        let source_id = agent_fname_source_id
            .get(fname)
            .map(String::as_str)
            .unwrap_or("gal-core");
        registry.mark_with_source(MANAGED_AGENT_PATHS, &target, source_id);
    }
    let installed_ids: Vec<&str> = ctx.opts.sources.iter().map(|s| s.id.as_str()).collect();
    prune_stale_links(
        &agents_target,
        agent_paths
            .iter()
            .filter_map(|path| path.file_name().and_then(OsStr::to_str))
            .filter(|fname| {
                let golem_name = fname.trim_end_matches(".agent.md");
                !ORCHESTRATED_ONLY_GOLEM_NAMES.contains(&golem_name)
            }),
        ctx.opts.dry_run,
        report,
        &registry,
        &installed_ids,
    )?;

    // --- Codex TOML subagent projection ---
    // Write `~/.codex/agents/<name>.toml` for each agent when codex runtime is selected.
    // Exclusion of orchestrated-only roles is layered in by the next task.
    if ctx.has_runtime("codex") {
        let codex_agents = ctx.codex_agents_target();
        ensure_dir(&codex_agents, ctx.opts.dry_run)?;

        // Load routing config for model/effort lookup (fail-safe: use defaults on parse error).
        let routing_cfg: Option<serde_json::Value> = fs::read_to_string(ctx.config_file())
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok());

        // Surface a retired-flat diagnostic once (never per-role) when consult roles are
        // still in the flat shape and would silently fall back to the default model.
        if !agent_paths.is_empty() {
            if let Some(msg) = retired_flat_planning_warning(&routing_cfg) {
                report.warnings.push(ProjectionWarning { message: msg });
            }
        }

        let mut codex_toml_names: Vec<String> = Vec::new();
        for agent_path in &agent_paths {
            let raw = fs::read_to_string(agent_path)?;
            if let Some(meta) = codex_agent::parse_agent_meta(&raw) {
                // Orchestrated-only roles must not be exposed as native Codex subagents.
                if ORCHESTRATED_ONLY_GOLEM_NAMES.contains(&meta.name.as_str()) {
                    continue;
                }
                let role = meta
                    .name
                    .strip_prefix("golem-")
                    .unwrap_or(&meta.name)
                    .to_ascii_uppercase();
                let (model, effort) = resolve_codex_routing(&routing_cfg, &role);
                let toml = codex_agent::serialize_codex_toml(
                    &meta,
                    &model,
                    effort.as_deref(),
                    tool_map::invocation_mode_to_codex_sandbox(tool_map::InvocationMode::Consult),
                );
                let toml_fname = format!("{}.toml", meta.name);
                let target = codex_agents.join(&toml_fname);
                write_text(&target, &toml, ctx.opts.dry_run)?;
                let fname_key = agent_path.file_name().and_then(OsStr::to_str).unwrap_or("");
                let source_id = agent_fname_source_id
                    .get(fname_key)
                    .map(String::as_str)
                    .unwrap_or("gal-core");
                registry.mark_with_source(MANAGED_CODEX_AGENT_PATHS, &target, source_id);
                codex_toml_names.push(toml_fname);
            }
        }
        prune_stale_links(
            &codex_agents,
            codex_toml_names.iter().map(String::as_str),
            ctx.opts.dry_run,
            report,
            &registry,
            &installed_ids,
        )?;

        // Project `discuss-<role>` skills for consult-3 golems to the shared official
        // `~/.agents/skills/` path (same path Codex reads command-skills from).
        // These provide the in-context consult path (no subagent spawn); the isolated path
        // is unchanged (`/agent golem-<role>` via the TOML agents above).
        let discuss_skills_root = ctx.opts.user_home.join(".agents").join("skills");
        ensure_dir(&discuss_skills_root, ctx.opts.dry_run)?;
        let mut discuss_skill_names: Vec<String> = Vec::new();
        for agent_path in &agent_paths {
            let raw = fs::read_to_string(agent_path)?;
            if let Some(meta) = parse_agent_meta(&raw) {
                if !CONSULT_GOLEM_NAMES.contains(&meta.name.as_str()) {
                    continue;
                }
                let dir_name = format!("discuss-{}", meta.name);
                let skill_dir = discuss_skills_root.join(&dir_name);
                ensure_dir(&skill_dir, ctx.opts.dry_run)?;
                let skill_path = skill_dir.join("SKILL.md");
                let content = generate_discuss_skill_md(&meta);
                write_text(&skill_path, &content, ctx.opts.dry_run)?;
                let source_id = agent_path
                    .file_name()
                    .and_then(OsStr::to_str)
                    .and_then(|f| agent_fname_source_id.get(f).map(String::as_str))
                    .unwrap_or("gal-core");
                registry.mark_with_source(MANAGED_DISCUSS_SKILL_PATHS, &skill_path, source_id);
                discuss_skill_names.push(dir_name);
            }
        }
        // No separate prune here — the shared-skills prune (above) already keeps discuss-<role>
        // directories via the `discuss_dir_names` additions to its keep set. A second prune on
        // the same root would evict unrelated command-skill entries.
    }

    if !ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
        registry.persist(ctx.opts.dry_run, report)?;
        return Ok(());
    }

    let opencode_agents = ctx.opencode_root().join("agents");
    let staged_agents = if ctx.opts.dry_run {
        None
    } else {
        let parent = opencode_agents
            .parent()
            .ok_or_else(|| AdapterError::Message("OpenCode agent root has no parent".into()))?;
        Some(create_temp_render_dir(parent)?)
    };
    let opencode_target_root = staged_agents
        .as_deref()
        .unwrap_or(opencode_agents.as_path());
    ensure_dir(opencode_target_root, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let raw = fs::read_to_string(agent_path)?;
        let frontmatter = parse_frontmatter(&raw);
        let name = agent_path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or("agent")
            .trim_end_matches(".agent");
        let target = opencode_target_root.join(format!("{name}.md"));
        let content = render_opencode_agent(name, &frontmatter, &strip_frontmatter(&raw));
        write_text(&target, &content, ctx.opts.dry_run)?;
    }
    if let Some(staged_agents) = staged_agents {
        atomic_swap(&staged_agents, &opencode_agents)
            .map_err(|e| AdapterError::Message(format!("OpenCode agent swap failed: {e}")))?;
        report.written_files.push(opencode_agents.clone());
    }

    let legacy_paths = [
        ctx.copilot_root().join("skills"),
        ctx.gemini_root().join("skills"),
        ctx.codex_root().join("skills"),
        ctx.antigravity_root().join("skills"),
    ];
    for path in legacy_paths {
        remove_if_gal_owned_dir(&path, ctx.opts.dry_run, report, &registry)?;
    }

    registry.persist(ctx.opts.dry_run, report)?;
    Ok(())
}

fn update_commands(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    use std::collections::BTreeSet;

    let commands_root = ctx.primary_source_root().join("commands");
    let canonical_commands_root = ctx.canonical_commands_root();
    let command_dirs = list_command_dirs(&commands_root)?;
    if command_dirs.is_empty() {
        return Ok(());
    }
    let mut registry = ManagedArtifactRegistry::load(&ctx.lockfile_path(), report);
    registry.replace_category(MANAGED_COMMAND_PATHS);

    ensure_dir(&canonical_commands_root, ctx.opts.dry_run)?;
    ensure_dir(&ctx.gemini_commands_target(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.opencode_commands_target(), ctx.opts.dry_run)?;

    let active_names = command_dirs
        .iter()
        .filter_map(|dir| dir.file_name().and_then(OsStr::to_str))
        .collect::<Vec<_>>();

    for command_dir in &command_dirs {
        let name = command_dir
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| AdapterError::Message("invalid command directory name".into()))?;
        let canonical_command_dir = canonical_commands_root.join(name);
        ensure_dir(&canonical_command_dir, ctx.opts.dry_run)?;

        let template_path = command_dir.join("SKILL.template.md");
        let rendered_source = bake_command_content(command_dir, &ctx.opts.repo_root)?;
        let baked_skill = canonical_command_dir.join("SKILL.md");
        if write_text(&baked_skill, &rendered_source, ctx.opts.dry_run)? {
            report.written_files.push(baked_skill.clone());
        }
        registry.mark(MANAGED_COMMAND_PATHS, &baked_skill);

        if template_path.is_file() {
            let stale_worktree_bake = command_dir.join("SKILL.md");
            if stale_worktree_bake.is_file() {
                if !ctx.opts.dry_run {
                    fs::remove_file(&stale_worktree_bake)?;
                }
                report.removed_paths.push(stale_worktree_bake);
            }
        }

        // Copilot has no slash-command concept; expose each command as a skill
        // (`~/.copilot/skills/<name>/SKILL.md`, triggered `/gal-status`). When
        // copilot is not selected, clean any command-skill GAL wrote before.
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "copilot") {
            if let Some(skill_file) = write_command_skill(
                &ctx.copilot_skills_target(),
                name,
                &rendered_source,
                ctx.opts.dry_run,
                report,
                &registry,
            )? {
                registry.mark(MANAGED_COMMAND_PATHS, &skill_file);
            }
        } else {
            remove_gal_command_skill(
                &ctx.copilot_skills_target(),
                name,
                &ctx.opts.repo_root,
                &registry,
                ctx.opts.dry_run,
                report,
            )?;
        }

        // Codex's capability unit is a skill at the shared ~/.agents/skills
        // (official path), invoked $gal-status. Always drop the legacy wrong-target
        // ~/.codex/skills link. Gate the shared command-skill on codex being
        // selected so an opencode-only install (opencode also reads ~/.agents/skills
        // but has its own native command projection) does not get a command-skill
        // on top of its native command — the double-load guard.
        remove_link_if_present(
            &ctx.codex_skills_target().join(name),
            ctx.opts.dry_run,
            report,
        )?;

        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "codex") {
            if let Some(skill_file) = write_command_skill(
                &ctx.shared_skills_target(),
                name,
                &rendered_source,
                ctx.opts.dry_run,
                report,
                &registry,
            )? {
                registry.mark(MANAGED_COMMAND_PATHS, &skill_file);
            }
        } else {
            // codex not selected: clean any GAL-written command-skill so it does
            // not linger in the shared dir (read by opencode/copilot) and cause a
            // double-load; user dirs and unrelated links are left untouched.
            remove_gal_command_skill(
                &ctx.shared_skills_target(),
                name,
                &ctx.opts.repo_root,
                &registry,
                ctx.opts.dry_run,
                report,
            )?;
        }

        // Antigravity does not natively read a plugin `commands/` folder
        // (gemini-cli#27325); its custom-command unit is an Agent Skill discovered
        // under `~/.gemini/antigravity-cli/skills/<name>/SKILL.md` (triggered
        // `/gal-status`). Project each command there when antigravity is selected,
        // else clean any command-skill GAL wrote before. Mirrors the copilot branch.
        if ctx
            .opts
            .selected_runtimes
            .iter()
            .any(|rt| rt == "antigravity")
        {
            if let Some(skill_file) = write_command_skill(
                &ctx.antigravity_root().join("skills"),
                name,
                &rendered_source,
                ctx.opts.dry_run,
                report,
                &registry,
            )? {
                registry.mark(MANAGED_COMMAND_PATHS, &skill_file);
            }
        } else {
            remove_gal_command_skill(
                &ctx.antigravity_root().join("skills"),
                name,
                &ctx.opts.repo_root,
                &registry,
                ctx.opts.dry_run,
                report,
            )?;
        }
        remove_link_if_present(
            &ctx.workspace_skills_target().join(name),
            ctx.opts.dry_run,
            report,
        )?;
        let frontmatter = parse_frontmatter(&rendered_source);
        let body = strip_frontmatter(&rendered_source);

        let gemini_target = ctx.gemini_commands_target().join(format!("{name}.toml"));
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "gemini") {
            if write_text(
                &gemini_target,
                &render_gemini_command(name, &frontmatter, &body),
                ctx.opts.dry_run,
            )? {
                report.written_files.push(gemini_target.clone());
            }
            registry.mark(MANAGED_COMMAND_PATHS, &gemini_target);
        } else {
            remove_managed_file_if_present(&gemini_target, ctx.opts.dry_run, report, &registry)?;
        }

        let claude_target = ctx.claude_commands_target().join(format!("{name}.md"));
        remove_managed_file_if_present(&claude_target, ctx.opts.dry_run, report, &registry)?;

        let opencode_target = ctx.opencode_commands_target().join(format!("{name}.md"));
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
            if write_text(
                &opencode_target,
                &render_opencode_command(name, &frontmatter, &body),
                ctx.opts.dry_run,
            )? {
                report.written_files.push(opencode_target.clone());
            }
            registry.mark(MANAGED_COMMAND_PATHS, &opencode_target);
        } else {
            remove_managed_file_if_present(&opencode_target, ctx.opts.dry_run, report, &registry)?;
        }
    }

    let link_cleanup_roots = [
        ctx.copilot_skills_target(),
        ctx.gemini_skills_target(),
        ctx.antigravity_root().join("skills"),
        ctx.shared_skills_target(),
        ctx.codex_skills_target(),
    ];
    for root in link_cleanup_roots {
        prune_stale_command_links(&root, &active_names, ctx.opts.dry_run, report, &registry)?;
        prune_legacy_gal_prefixed_dirs(&root, &active_names, ctx.opts.dry_run, report, &registry)?;
    }
    prune_stale_managed_files(
        &ctx.gemini_commands_target(),
        "toml",
        &active_names,
        ctx.opts.dry_run,
        report,
        &registry,
    )?;
    prune_stale_managed_files(
        &ctx.claude_commands_target(),
        "md",
        &active_names,
        ctx.opts.dry_run,
        report,
        &registry,
    )?;
    prune_stale_managed_files(
        &ctx.opencode_commands_target(),
        "md",
        &active_names,
        ctx.opts.dry_run,
        report,
        &registry,
    )?;

    // Zombie cleanup: a shared-root entry that is GAL-owned (per the lockfile
    // this same invocation just read — update_skills persists before
    // update_commands runs) but corresponds to neither an active command nor an
    // active skill nor a discuss-skill has no create/delete counterpart of its
    // own (e.g. a command or skill retired from source with nothing left to
    // prune it). remove_gal_command_skill only ever removes a GAL-owned repo
    // link or a lockfile-attributed real directory — a user-owned or unmarked
    // entry at the same name is always left untouched (a2 fail-safe).
    let shared_skills = ctx.shared_skills_target();
    let mut keep_names: BTreeSet<String> =
        active_names.iter().map(|name| name.to_string()).collect();
    for src in &ctx.opts.sources {
        for name in list_named_children(&src.root.join("skills")).unwrap_or_default() {
            keep_names.insert(name);
        }
    }
    if ctx.has_runtime("codex") {
        for name in CONSULT_GOLEM_NAMES {
            keep_names.insert(format!("discuss-{name}"));
        }
    }
    for existing in list_named_children(&shared_skills).unwrap_or_default() {
        if keep_names.contains(&existing) {
            continue;
        }
        remove_gal_command_skill(
            &shared_skills,
            &existing,
            &ctx.opts.repo_root,
            &registry,
            ctx.opts.dry_run,
            report,
        )?;
    }

    registry.persist(ctx.opts.dry_run, report)?;
    Ok(())
}

/// Consult role keys read from the `executorRouting.planning` group for Codex native
/// subagent resolution. Kept local to projection (which does not depend on the dispatch
/// crate); the same set is `PLANNING_ROLES` in `crates/dispatch/src/routing.rs`.
const CONSULT_ROLE_KEYS: &[&str] = &["ARCHITECT", "ANALYST", "DESIGNER", "RELEASER"];

/// A retired-flat-shape diagnostic for the caller to surface, or `None` when the config
/// is not in the flat shape. Fires when `executorRouting` exists, its `planning` group is
/// absent (or not an object), and at least one top-level consult-role key is present —
/// i.e. the consult roles are still in the retired flat shape and would silently fall back
/// to the default model. Never silent: the caller pushes this into `report.warnings`.
fn retired_flat_planning_warning(routing_cfg: &Option<serde_json::Value>) -> Option<String> {
    let subtree = routing_cfg.as_ref().and_then(|v| v.get("executorRouting"))?;
    let obj = subtree.as_object()?;
    if obj.get("planning").and_then(|p| p.as_object()).is_some() {
        return None; // planning group present → not the flat shape
    }
    let stray: Vec<&str> = CONSULT_ROLE_KEYS
        .iter()
        .copied()
        .filter(|role| obj.contains_key(*role))
        .collect();
    if stray.is_empty() {
        return None;
    }
    Some(format!(
        "executor-routing: consult role(s) {stray:?} found at the top level of executorRouting but the 'planning' group is absent; these are retired flat entries — move them under executorRouting.planning.<ROLE>. Falling back to the default Codex model."
    ))
}

/// Resolve the Codex model and optional reasoning effort for `role` from the
/// `config.json#executorRouting.planning` group.
///
/// Falls back to `"gpt-5.4-mini"` with no effort when the role has no entry in the
/// `planning` group (including when the config still uses the retired flat shape — the
/// caller surfaces `retired_flat_planning_warning` in that case).
fn resolve_codex_routing(
    routing_cfg: &Option<serde_json::Value>,
    role: &str,
) -> (String, Option<String>) {
    // Routing lives under the `executorRouting` subtree of config.json; consult roles
    // live in the `planning` group (dispatch roles are in `pipeline`).
    let subtree = routing_cfg.as_ref().and_then(|v| v.get("executorRouting"));

    let entry = subtree
        .and_then(|s| s.get("planning"))
        .and_then(|p| p.get(role));
    let executor_defaults = subtree.and_then(|s| s.get("executors"));

    if let Some(entry) = entry {
        let model = entry
            .get("model")
            .and_then(|v| v.as_str())
            .map(str::to_owned);
        let effort = entry
            .get("effort")
            .and_then(|v| v.as_str())
            .map(str::to_owned);
        let executor = entry
            .get("executor")
            .and_then(|v| v.as_str())
            .unwrap_or("codex");

        let resolved_model = model
            .or_else(|| {
                executor_defaults
                    .and_then(|e| e.get(executor))
                    .and_then(|v| v.as_str())
                    .map(str::to_owned)
            })
            .unwrap_or_else(|| "gpt-5.4-mini".to_owned());

        (resolved_model, effort)
    } else {
        ("gpt-5.4-mini".to_owned(), None)
    }
}
