//! Skill projection backend for the R-03 adapters port.

use base::health::{DoctorFinding, HealthCheck};
use base::platform::{atomic_swap, create_dir_link, is_symlink_or_junction, remove_dir_link};
use base::render::create_temp_render_dir;
use std::ffi::OsStr;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use thiserror::Error;

const GAL_MANAGED_FILE_HEADER: &str = "# Generated by GAL Setup-Machine. Do not edit manually.";

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionWarning {
    pub message: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionReport {
    pub written_files: Vec<PathBuf>,
    pub removed_paths: Vec<PathBuf>,
    pub created_links: Vec<PathBuf>,
    pub warnings: Vec<ProjectionWarning>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillUpdateOptions {
    pub repo_root: PathBuf,
    pub source_root: PathBuf,
    pub user_home: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub dry_run: bool,
    pub replace: bool,
}

#[derive(Debug, Error)]
pub enum AdapterError {
    #[error("{0}")]
    Message(String),
    #[error("{0}")]
    Io(#[from] io::Error),
}

#[derive(Debug, Clone)]
struct SkillContext {
    opts: SkillUpdateOptions,
}

impl SkillContext {
    fn new(opts: SkillUpdateOptions) -> Self {
        Self { opts }
    }

    fn copilot_root(&self) -> PathBuf {
        self.opts.user_home.join(".copilot")
    }

    fn gemini_root(&self) -> PathBuf {
        self.opts.user_home.join(".gemini")
    }

    fn codex_root(&self) -> PathBuf {
        self.opts.user_home.join(".codex")
    }

    fn antigravity_root(&self) -> PathBuf {
        self.gemini_root().join("antigravity-cli")
    }

    fn gal_home(&self) -> PathBuf {
        self.opts.user_home.join(".gal")
    }

    fn gal_source_root(&self) -> PathBuf {
        self.gal_home().join("source")
    }

    fn agents_target(&self) -> PathBuf {
        self.copilot_root().join("agents")
    }

    fn opencode_root(&self) -> PathBuf {
        self.opts.user_home.join(".config").join("opencode")
    }
}

pub fn run_update_skills(opts: &SkillUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_skills(&ctx, &mut report)?;
    Ok(report)
}

fn update_skills(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    let skill_names = list_named_children(&ctx.opts.source_root.join("skills"))?;
    let agent_paths = list_files_with_extension(&ctx.opts.source_root.join("agents"), "agent.md")?;

    let shared_skills = ctx.opts.user_home.join(".agents").join("skills");
    let should_project_shared_skills = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "codex" || rt == "opencode");
    if should_project_shared_skills {
        ensure_dir(&shared_skills, ctx.opts.dry_run)?;
        for skill_name in &skill_names {
            let source = ctx.opts.source_root.join("skills").join(skill_name);
            let link = shared_skills.join(skill_name);
            ensure_dir_link(&source, &link, ctx.opts.replace, ctx.opts.dry_run, report)?;
        }
        prune_stale_links(
            &shared_skills,
            skill_names.iter().map(String::as_str),
            ctx.opts.dry_run,
            report,
        )?;
    } else {
        prune_stale_links(&shared_skills, std::iter::empty(), ctx.opts.dry_run, report)?;
    }

    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "copilot") {
        let gal_root = ctx.copilot_root().join("gal");
        ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
        ensure_dir_link(&ctx.gal_home(), &gal_root, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    let should_keep_source_link = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "gemini" || rt == "antigravity");
    if should_keep_source_link {
        ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
        ensure_dir_link(&ctx.opts.repo_root, &ctx.gal_source_root(), ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "gemini") {
        let gal_root = ctx.gemini_root().join("gal");
        ensure_dir_link(&ctx.gal_source_root(), &gal_root, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "antigravity") {
        let gal_root = ctx.antigravity_root().join("gal");
        ensure_dir_link(&ctx.gal_source_root(), &gal_root, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }

    let agents_target = ctx.agents_target();
    ensure_dir(&agents_target, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let link = agents_target.join(
            agent_path
                .file_name()
                .and_then(OsStr::to_str)
                .ok_or_else(|| AdapterError::Message("invalid agent file name".into()))?,
        );
        ensure_file_link(agent_path, &link, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    prune_stale_links(
        &agents_target,
        agent_paths
            .iter()
            .filter_map(|path| path.file_name().and_then(OsStr::to_str)),
        ctx.opts.dry_run,
        report,
    )?;

    if !ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
        return Ok(());
    }

    let opencode_agents = ctx.opencode_root().join("agents");
    let staged_agents = if ctx.opts.dry_run {
        None
    } else {
        let parent = opencode_agents
            .parent()
            .ok_or_else(|| AdapterError::Message("OpenCode agent root has no parent".into()))?;
        Some(create_temp_render_dir(parent)?)
    };
    let opencode_target_root = staged_agents
        .as_ref()
        .map(PathBuf::as_path)
        .unwrap_or(opencode_agents.as_path());
    ensure_dir(opencode_target_root, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let raw = fs::read_to_string(agent_path)?;
        let frontmatter = parse_frontmatter(&raw);
        let name = agent_path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or("agent")
            .trim_end_matches(".agent");
        let target = opencode_target_root.join(format!("{name}.md"));
        let content = render_opencode_agent(name, &frontmatter, &strip_frontmatter(&raw));
        write_text(&target, &content, ctx.opts.dry_run)?;
    }
    if let Some(staged_agents) = staged_agents {
        atomic_swap(&staged_agents, &opencode_agents)
            .map_err(|e| AdapterError::Message(format!("OpenCode agent swap failed: {e}")))?;
        report.written_files.push(opencode_agents.clone());
    }

    let legacy_paths = [
        ctx.copilot_root().join("skills"),
        ctx.gemini_root().join("skills"),
        ctx.codex_root().join("skills"),
        ctx.antigravity_root().join("skills"),
    ];
    for path in legacy_paths {
        remove_if_gal_owned_dir(&path, ctx.opts.dry_run, report)?;
    }

    Ok(())
}

pub struct SkillsProjectionHealthCheck {
    shared_skills_root: PathBuf,
}

impl SkillsProjectionHealthCheck {
    pub fn with_path(shared_skills_root: PathBuf) -> Self {
        Self { shared_skills_root }
    }
}

impl HealthCheck for SkillsProjectionHealthCheck {
    fn name(&self) -> &str {
        "skills-projection"
    }

    fn check(&self) -> Vec<DoctorFinding> {
        if !self.shared_skills_root.exists() {
            return vec![DoctorFinding::warning(format!(
                "shared skill projection not found: {} — run `gal update --machine-only`",
                self.shared_skills_root.display()
            ))];
        }
        if !self.shared_skills_root.is_dir() {
            return vec![DoctorFinding::error(
                format!(
                    "shared skill projection is not a directory: {}",
                    self.shared_skills_root.display()
                ),
                "remove the path and rerun `gal update --machine-only`",
            )];
        }
        vec![]
    }
}

#[derive(Debug, Clone, Default)]
struct Frontmatter {
    description: Option<String>,
    color: Option<String>,
    tools: Vec<String>,
}

fn parse_frontmatter(raw: &str) -> Frontmatter {
    let mut lines = raw.lines();
    if lines.next() != Some("---") {
        return Frontmatter::default();
    }

    let mut description = None;
    let mut color = None;
    let mut tools = Vec::new();
    for line in lines {
        if line.trim() == "---" {
            break;
        }
        if let Some((key, value)) = line.split_once(':') {
            let key = key.trim();
            let value = value.trim().trim_matches('"');
            if key == "description" {
                description = Some(value.to_string());
            } else if key == "color" {
                color = Some(value.to_string());
            } else if key == "tools" {
                tools = value
                    .trim_matches(['[', ']'])
                    .split(',')
                    .map(|part| part.trim().trim_matches('"').trim_matches('\''))
                    .filter(|part| !part.is_empty())
                    .map(str::to_string)
                    .collect();
            }
        }
    }

    Frontmatter {
        description,
        color,
        tools,
    }
}

fn strip_frontmatter(raw: &str) -> String {
    let mut lines = raw.lines();
    if lines.next() != Some("---") {
        return raw.trim().to_string();
    }

    let mut body = String::new();
    let mut in_frontmatter = true;
    for line in raw.lines().skip(1) {
        if in_frontmatter {
            if line.trim() == "---" {
                in_frontmatter = false;
            }
            continue;
        }
        body.push_str(line);
        body.push('\n');
    }
    body.trim().to_string()
}

fn render_opencode_agent(_name: &str, frontmatter: &Frontmatter, body: &str) -> String {
    let mut permissions = Vec::new();
    for tool in &frontmatter.tools {
        match tool.as_str() {
            "read" => {
                push_permission(&mut permissions, "read");
                push_permission(&mut permissions, "list");
            }
            "search" => {
                push_permission(&mut permissions, "read");
                push_permission(&mut permissions, "list");
                push_permission(&mut permissions, "grep");
                push_permission(&mut permissions, "glob");
            }
            "list" => {
                push_permission(&mut permissions, "list");
            }
            "edit" => {
                push_permission(&mut permissions, "edit");
            }
            "execute" => {
                push_permission(&mut permissions, "bash");
            }
            _ => {}
        }
    }

    if permissions.is_empty() {
        push_permission(&mut permissions, "read");
        push_permission(&mut permissions, "list");
    }

    let description = frontmatter
        .description
        .clone()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "GAL golem agent".into());

    let mut lines = vec![
        GAL_MANAGED_FILE_HEADER.to_string(),
        "---".into(),
        "description: |".into(),
    ];
    for line in description.lines() {
        lines.push(format!("  {line}"));
    }
    lines.push("mode: subagent".into());
    if let Some(color) = &frontmatter.color {
        lines.push(format!("color: {color}"));
    }
    lines.push("permission:".into());
    for permission in permissions {
        lines.push(format!("  {permission}: allow"));
    }
    lines.push("---".into());
    lines.push(String::new());
    lines.push(body.trim().to_string());
    lines.push(String::new());
    lines.join("\n")
}

fn push_permission(permissions: &mut Vec<&'static str>, value: &'static str) {
    if !permissions.contains(&value) {
        permissions.push(value);
    }
}

fn list_named_children(root: &Path) -> Result<Vec<String>, AdapterError> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut names = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if entry.file_type()?.is_dir() {
            names.push(entry.file_name().to_string_lossy().to_string());
        }
    }
    names.sort();
    Ok(names)
}

fn list_files_with_extension(root: &Path, suffix: &str) -> Result<Vec<PathBuf>, AdapterError> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut files = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if entry.file_type()?.is_file()
            && entry
                .path()
                .file_name()
                .and_then(OsStr::to_str)
                .map(|name| name.ends_with(suffix))
                .unwrap_or(false)
        {
            files.push(entry.path());
        }
    }
    files.sort();
    Ok(files)
}

fn prune_stale_links<'a>(
    root: &Path,
    keep_names: impl IntoIterator<Item = &'a str>,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !root.is_dir() {
        return Ok(());
    }

    let keep: Vec<&str> = keep_names.into_iter().collect();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        if keep.contains(&name) {
            continue;
        }

        let path = entry.path();
        if is_symlink_or_junction(&path) {
            if !dry_run {
                remove_link(&path)?;
            }
            report.removed_paths.push(path);
        }
    }
    Ok(())
}

fn ensure_dir(path: &Path, dry_run: bool) -> Result<(), AdapterError> {
    if dry_run || path.is_dir() {
        return Ok(());
    }
    fs::create_dir_all(path)?;
    Ok(())
}

fn write_text(
    path: &Path,
    content: &str,
    dry_run: bool,
) -> Result<(), AdapterError> {
    let normalized = format!("{}\n", content.trim_end());
    if !dry_run {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, normalized.as_bytes())?;
    }
    Ok(())
}

fn ensure_dir_link(
    target: &Path,
    link: &Path,
    replace: bool,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if same_path(link, target) {
        return Ok(());
    }
    if is_symlink_or_junction(link) {
        if dry_run {
            report.created_links.push(link.to_path_buf());
            return Ok(());
        }
        remove_dir_link(link)?;
    } else if link.exists() {
        if !replace {
            report.warnings.push(ProjectionWarning {
                message: format!("preserved user-owned path: {}", link.display()),
            });
            return Ok(());
        }
        let backup = backup_path(link);
        if !dry_run {
            if backup.exists() {
                if backup.is_dir() {
                    fs::remove_dir_all(&backup)?;
                } else {
                    fs::remove_file(&backup)?;
                }
            }
            fs::rename(link, &backup)?;
        }
        report.removed_paths.push(backup);
    }
    if !dry_run {
        if let Some(parent) = link.parent() {
            fs::create_dir_all(parent)?;
        }
        create_dir_link(target, link)?;
    }
    report.created_links.push(link.to_path_buf());
    Ok(())
}

fn ensure_file_link(
    target: &Path,
    link: &Path,
    replace: bool,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if same_path(link, target) {
        return Ok(());
    }
    if is_symlink_or_junction(link) {
        if dry_run {
            report.created_links.push(link.to_path_buf());
            return Ok(());
        }
        remove_link(link)?;
    } else if link.exists() {
        if !replace {
            report.warnings.push(ProjectionWarning {
                message: format!("preserved user-owned path: {}", link.display()),
            });
            return Ok(());
        }
        let backup = backup_path(link);
        if !dry_run {
            if backup.exists() {
                if backup.is_dir() {
                    fs::remove_dir_all(&backup)?;
                } else {
                    fs::remove_file(&backup)?;
                }
            }
            fs::rename(link, &backup)?;
        }
        report.removed_paths.push(backup);
    }
    if !dry_run {
        if let Some(parent) = link.parent() {
            fs::create_dir_all(parent)?;
        }
        create_file_link(target, link)?;
    }
    report.created_links.push(link.to_path_buf());
    Ok(())
}

fn same_path(left: &Path, right: &Path) -> bool {
    match (fs::canonicalize(left), fs::canonicalize(right)) {
        (Ok(a), Ok(b)) => a == b,
        _ => false,
    }
}

fn backup_path(path: &Path) -> PathBuf {
    let name = path
        .file_name()
        .and_then(OsStr::to_str)
        .map(|value| format!("{value}.bak"))
        .unwrap_or_else(|| "backup.bak".into());
    path.with_file_name(name)
}

fn create_file_link(target: &Path, link: &Path) -> io::Result<()> {
    #[cfg(windows)]
    {
        let output = std::process::Command::new("cmd")
            .args(["/C", "mklink", &link.to_string_lossy(), &target.to_string_lossy()])
            .output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(io::Error::new(io::ErrorKind::Other, stderr.into_owned()));
        }
        Ok(())
    }
    #[cfg(not(windows))]
    {
        std::os::unix::fs::symlink(target, link)
    }
}

fn remove_link(path: &Path) -> io::Result<()> {
    let metadata = path.symlink_metadata()?;
    if metadata.file_type().is_dir() {
        remove_dir_link(path)
    } else {
        fs::remove_file(path)
    }
}

fn remove_if_gal_owned_dir(path: &Path, dry_run: bool, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    if !path.exists() {
        return Ok(());
    }
    if is_symlink_or_junction(path) {
        if !dry_run {
            remove_dir_link(path)?;
        }
        report.removed_paths.push(path.to_path_buf());
        return Ok(());
    }
    if path.is_dir() {
        let marker = path.join(".gal-managed");
        if marker.exists() || path.file_name().and_then(OsStr::to_str) == Some("skills") {
            if !dry_run {
                fs::remove_dir_all(path)?;
            }
            report.removed_paths.push(path.to_path_buf());
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fixture_roots() -> (TempDir, PathBuf, PathBuf, PathBuf) {
        let temp = TempDir::new().unwrap();
        let repo_root = temp.path().join("repo");
        let source_root = repo_root.join("plugins").join("gal-core");
        let home = temp.path().join("home");
        fs::create_dir_all(source_root.join("skills").join("sample-skill")).unwrap();
        fs::create_dir_all(source_root.join("agents")).unwrap();
        (temp, repo_root, source_root, home)
    }

    #[test]
    fn update_skills_projects_links_and_agents() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        fs::write(source_root.join("skills").join("sample-skill").join("SKILL.md"), "# Skill").unwrap();
        fs::write(
            source_root.join("agents").join("helper.agent.md"),
            "---\ndescription: helper\ncolor: green\ntools: [read, edit, execute]\n---\nBody\n",
        )
        .unwrap();

        let report = run_update_skills(&SkillUpdateOptions {
            repo_root: repo_root.clone(),
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["copilot".into(), "gemini".into(), "antigravity".into(), "opencode".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(!report.created_links.is_empty());
        assert!(home.join(".agents").join("skills").join("sample-skill").exists());
        assert!(home.join(".copilot").join("agents").join("helper.agent.md").exists());
        assert!(home.join(".copilot").join("gal").exists());
        assert!(home.join(".gemini").join("gal").exists());
        assert!(home.join(".gemini").join("antigravity-cli").join("gal").exists());
        let rendered = fs::read_to_string(home.join(".config").join("opencode").join("agents").join("helper.md")).unwrap();
        assert!(rendered.starts_with(GAL_MANAGED_FILE_HEADER));
        assert!(rendered.contains("color: green"));
        assert!(rendered.contains("  read: allow"));
        assert!(rendered.contains("  list: allow"));
        assert!(rendered.contains("  edit: allow"));
        assert!(rendered.contains("  bash: allow"));
    }

    #[test]
    fn update_skills_skips_shared_projection_without_codex_or_opencode() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        fs::write(source_root.join("skills").join("sample-skill").join("SKILL.md"), "# Skill").unwrap();

        run_update_skills(&SkillUpdateOptions {
            repo_root,
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["copilot".into(), "gemini".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(!home.join(".agents").join("skills").join("sample-skill").exists());
    }

    #[test]
    fn healthcheck_warns_when_projection_missing() {
        let temp = TempDir::new().unwrap();
        let check = SkillsProjectionHealthCheck::with_path(temp.path().join("missing"));
        let findings = check.check();
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, base::health::Severity::Warning);
    }

    #[test]
    fn healthcheck_accepts_existing_directory() {
        let temp = TempDir::new().unwrap();
        let path = temp.path().join("skills");
        fs::create_dir_all(&path).unwrap();
        let check = SkillsProjectionHealthCheck::with_path(path);
        assert!(check.check().is_empty());
    }

    #[test]
    fn render_opencode_agent_matches_legacy_shape() {
        let rendered = render_opencode_agent(
            "helper",
            &Frontmatter {
                description: Some("helper line 1\nhelper line 2".into()),
                color: Some("green".into()),
                tools: Vec::new(),
            },
            "Body",
        );

        assert_eq!(
            rendered,
            "# Generated by GAL Setup-Machine. Do not edit manually.\n---\ndescription: |\n  helper line 1\n  helper line 2\nmode: subagent\ncolor: green\npermission:\n  read: allow\n  list: allow\n---\n\nBody\n"
        );
    }

    #[test]
    fn render_opencode_agent_expands_search_permissions() {
        let rendered = render_opencode_agent(
            "helper",
            &Frontmatter {
                description: Some("helper".into()),
                color: None,
                tools: vec!["search".into()],
            },
            "Body",
        );

        assert!(rendered.contains("  read: allow"));
        assert!(rendered.contains("  list: allow"));
        assert!(rendered.contains("  grep: allow"));
        assert!(rendered.contains("  glob: allow"));
    }
}
