//! Skill + command projection backends for the R-03 adapters port.

use base::config::GalConfig;
use base::health::{DoctorFinding, HealthCheck};
use base::json_util::read_json_map;
use base::platform::{atomic_swap, create_dir_link, is_symlink_or_junction, remove_dir_link};
use base::render::create_temp_render_dir;
use serde_json::{Map, Value};
use std::ffi::OsStr;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;
use thiserror::Error;

const GAL_MANAGED_FILE_HEADER: &str = "# Generated by GAL Setup-Machine. Do not edit manually.";

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionWarning {
    pub message: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionReport {
    pub written_files: Vec<PathBuf>,
    pub removed_paths: Vec<PathBuf>,
    pub created_links: Vec<PathBuf>,
    pub warnings: Vec<ProjectionWarning>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillUpdateOptions {
    pub repo_root: PathBuf,
    pub source_root: PathBuf,
    pub user_home: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub dry_run: bool,
    pub replace: bool,
}

pub type CommandUpdateOptions = SkillUpdateOptions;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PersonalizationUpdateOptions {
    pub repo_root: PathBuf,
    pub source_root: PathBuf,
    pub user_home: PathBuf,
    pub appdata_root: PathBuf,
    pub selected_runtimes: Vec<String>,
    pub dry_run: bool,
    pub replace: bool,
    pub uninstall: bool,
}

#[derive(Debug, Error)]
pub enum AdapterError {
    #[error("{0}")]
    Message(String),
    #[error("{0}")]
    Io(#[from] io::Error),
}

#[derive(Debug, Clone)]
struct SkillContext {
    opts: SkillUpdateOptions,
}

impl SkillContext {
    fn new(opts: SkillUpdateOptions) -> Self {
        Self { opts }
    }

    fn copilot_root(&self) -> PathBuf {
        self.opts.user_home.join(".copilot")
    }

    fn gemini_root(&self) -> PathBuf {
        self.opts.user_home.join(".gemini")
    }

    fn codex_root(&self) -> PathBuf {
        self.opts.user_home.join(".codex")
    }

    fn antigravity_root(&self) -> PathBuf {
        self.gemini_root().join("antigravity-cli")
    }

    fn gal_home(&self) -> PathBuf {
        self.opts.user_home.join(".gal")
    }

    fn gal_source_root(&self) -> PathBuf {
        self.gal_home().join("source")
    }

    fn agents_target(&self) -> PathBuf {
        self.copilot_root().join("agents")
    }

    fn copilot_skills_target(&self) -> PathBuf {
        self.copilot_root().join("skills")
    }

    fn codex_skills_target(&self) -> PathBuf {
        self.codex_root().join("skills")
    }

    fn gemini_commands_target(&self) -> PathBuf {
        self.gemini_root().join("commands")
    }

    fn gemini_skills_target(&self) -> PathBuf {
        self.gemini_root().join("skills")
    }

    fn claude_commands_target(&self) -> PathBuf {
        self.opts.user_home.join(".claude").join("commands")
    }

    fn workspace_skills_target(&self) -> PathBuf {
        self.opts.repo_root.join(".agents").join("skills")
    }

    fn shared_skills_target(&self) -> PathBuf {
        self.opts.user_home.join(".agents").join("skills")
    }

    fn opencode_root(&self) -> PathBuf {
        self.opts.user_home.join(".config").join("opencode")
    }

    fn opencode_commands_target(&self) -> PathBuf {
        self.opencode_root().join("commands")
    }
}

#[derive(Debug, Clone)]
struct PersonalizationContext {
    opts: PersonalizationUpdateOptions,
}

impl PersonalizationContext {
    fn new(opts: PersonalizationUpdateOptions) -> Self {
        Self { opts }
    }

    fn gal_home(&self) -> PathBuf {
        self.opts.user_home.join(".gal")
    }

    fn gal_config_root(&self) -> PathBuf {
        self.gal_home().join("config")
    }

    fn gemini_root(&self) -> PathBuf {
        self.opts.user_home.join(".gemini")
    }

    fn gemini_context_file(&self) -> PathBuf {
        self.gemini_root().join("gal-context.md")
    }

    fn gemini_settings_file(&self) -> PathBuf {
        self.gemini_root().join("settings.json")
    }

    fn antigravity_root(&self) -> PathBuf {
        self.gemini_root().join("antigravity-cli")
    }

    fn agy_plugin_install_target(&self) -> PathBuf {
        self.antigravity_root().join("plugins").join("gal")
    }

    fn workspace_agents_root(&self) -> PathBuf {
        self.opts.repo_root.join(".agents")
    }

    fn workspace_skills_target(&self) -> PathBuf {
        self.workspace_agents_root().join("skills")
    }

    fn workspace_rules_target(&self) -> PathBuf {
        self.workspace_agents_root().join("rules")
    }

    fn vscode_settings_file(&self) -> PathBuf {
        self.opts
            .appdata_root
            .join("Code")
            .join("User")
            .join("settings.json")
    }

    fn local_routing_target(&self) -> PathBuf {
        self.gal_config_root().join("executor-routing.json")
    }

    fn legacy_routing_target(&self) -> PathBuf {
        self.gal_config_root().join("executor-routing.ndjson")
    }

    fn example_routing_source(&self) -> PathBuf {
        self.opts
            .repo_root
            .join("plugins")
            .join("gal-core")
            .join("templates")
            .join("executor-routing.example.json")
    }

    fn config_file(&self) -> PathBuf {
        self.gal_config_root().join("config.json")
    }

    fn has_runtime(&self, runtime: &str) -> bool {
        self.opts.selected_runtimes.iter().any(|value| value == runtime)
    }
}

pub fn run_update_skills(opts: &SkillUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_skills(&ctx, &mut report)?;
    Ok(report)
}

pub fn run_update_commands(opts: &CommandUpdateOptions) -> Result<ProjectionReport, AdapterError> {
    let ctx = SkillContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_commands(&ctx, &mut report)?;
    Ok(report)
}

pub fn run_update_personalization(
    opts: &PersonalizationUpdateOptions,
) -> Result<ProjectionReport, AdapterError> {
    let ctx = PersonalizationContext::new(opts.clone());
    let mut report = ProjectionReport::default();
    update_personalization(&ctx, &mut report)?;
    Ok(report)
}

fn update_skills(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    let skill_names = list_named_children(&ctx.opts.source_root.join("skills"))?;
    let agent_paths = list_files_with_extension(&ctx.opts.source_root.join("agents"), "agent.md")?;

    let shared_skills = ctx.opts.user_home.join(".agents").join("skills");
    let should_project_shared_skills = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "codex" || rt == "opencode");
    if should_project_shared_skills {
        ensure_dir(&shared_skills, ctx.opts.dry_run)?;
        for skill_name in &skill_names {
            let source = ctx.opts.source_root.join("skills").join(skill_name);
            let link = shared_skills.join(skill_name);
            ensure_dir_link(&source, &link, ctx.opts.replace, ctx.opts.dry_run, report)?;
        }
        prune_stale_links(
            &shared_skills,
            skill_names.iter().map(String::as_str),
            ctx.opts.dry_run,
            report,
        )?;
    } else {
        prune_stale_links(&shared_skills, std::iter::empty(), ctx.opts.dry_run, report)?;
    }

    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "copilot") {
        let gal_root = ctx.copilot_root().join("gal");
        ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
        ensure_dir_link(&ctx.gal_home(), &gal_root, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    let should_keep_source_link = ctx
        .opts
        .selected_runtimes
        .iter()
        .any(|rt| rt == "gemini" || rt == "antigravity");
    if should_keep_source_link {
        ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
        ensure_dir_link(&ctx.opts.repo_root, &ctx.gal_source_root(), ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "gemini") {
        let gal_root = ctx.gemini_root().join("gal");
        ensure_dir_link(&ctx.gal_source_root(), &gal_root, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    if ctx.opts.selected_runtimes.iter().any(|rt| rt == "antigravity") {
        let gal_root = ctx.antigravity_root().join("gal");
        ensure_dir_link(&ctx.gal_source_root(), &gal_root, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }

    let agents_target = ctx.agents_target();
    ensure_dir(&agents_target, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let link = agents_target.join(
            agent_path
                .file_name()
                .and_then(OsStr::to_str)
                .ok_or_else(|| AdapterError::Message("invalid agent file name".into()))?,
        );
        ensure_file_link(agent_path, &link, ctx.opts.replace, ctx.opts.dry_run, report)?;
    }
    prune_stale_links(
        &agents_target,
        agent_paths
            .iter()
            .filter_map(|path| path.file_name().and_then(OsStr::to_str)),
        ctx.opts.dry_run,
        report,
    )?;

    if !ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
        return Ok(());
    }

    let opencode_agents = ctx.opencode_root().join("agents");
    let staged_agents = if ctx.opts.dry_run {
        None
    } else {
        let parent = opencode_agents
            .parent()
            .ok_or_else(|| AdapterError::Message("OpenCode agent root has no parent".into()))?;
        Some(create_temp_render_dir(parent)?)
    };
    let opencode_target_root = staged_agents
        .as_ref()
        .map(PathBuf::as_path)
        .unwrap_or(opencode_agents.as_path());
    ensure_dir(opencode_target_root, ctx.opts.dry_run)?;
    for agent_path in &agent_paths {
        let raw = fs::read_to_string(agent_path)?;
        let frontmatter = parse_frontmatter(&raw);
        let name = agent_path
            .file_stem()
            .and_then(OsStr::to_str)
            .unwrap_or("agent")
            .trim_end_matches(".agent");
        let target = opencode_target_root.join(format!("{name}.md"));
        let content = render_opencode_agent(name, &frontmatter, &strip_frontmatter(&raw));
        write_text(&target, &content, ctx.opts.dry_run)?;
    }
    if let Some(staged_agents) = staged_agents {
        atomic_swap(&staged_agents, &opencode_agents)
            .map_err(|e| AdapterError::Message(format!("OpenCode agent swap failed: {e}")))?;
        report.written_files.push(opencode_agents.clone());
    }

    let legacy_paths = [
        ctx.copilot_root().join("skills"),
        ctx.gemini_root().join("skills"),
        ctx.codex_root().join("skills"),
        ctx.antigravity_root().join("skills"),
    ];
    for path in legacy_paths {
        remove_if_gal_owned_dir(&path, ctx.opts.dry_run, report)?;
    }

    Ok(())
}

fn update_commands(ctx: &SkillContext, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    let commands_root = ctx.opts.source_root.join("commands");
    let command_dirs = list_command_dirs(&commands_root)?;
    if command_dirs.is_empty() {
        return Ok(());
    }

    ensure_dir(&ctx.gemini_commands_target(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.opencode_commands_target(), ctx.opts.dry_run)?;

    let active_names = command_dirs
        .iter()
        .filter_map(|dir| dir.file_name().and_then(OsStr::to_str))
        .collect::<Vec<_>>();

    for command_dir in &command_dirs {
        let name = command_dir
            .file_name()
            .and_then(OsStr::to_str)
            .ok_or_else(|| AdapterError::Message("invalid command directory name".into()))?;
        let template_path = command_dir.join("SKILL.template.md");
        if template_path.is_file() {
            let baked_source = bake_command_content(command_dir, &ctx.opts.repo_root)?;
            let baked_skill = command_dir.join("SKILL.md");
            write_text(&baked_skill, &baked_source, ctx.opts.dry_run)?;
        }

        let copilot_target = ctx.copilot_skills_target().join(name);
        remove_link_if_present(&copilot_target, ctx.opts.dry_run, report)?;

        let codex_target = ctx.codex_skills_target().join(name);
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "codex") {
            ensure_dir_link(command_dir, &codex_target, ctx.opts.replace, ctx.opts.dry_run, report)?;
        } else {
            remove_link_if_present(&codex_target, ctx.opts.dry_run, report)?;
        }

        remove_link_if_present(
            &ctx.antigravity_root().join("skills").join(name),
            ctx.opts.dry_run,
            report,
        )?;
        remove_link_if_present(
            &ctx.workspace_skills_target().join(name),
            ctx.opts.dry_run,
            report,
        )?;
        let shared_target = ctx.shared_skills_target().join(name);
        if is_gal_repo_link(&shared_target, &ctx.opts.repo_root) {
            remove_link_if_present(&shared_target, ctx.opts.dry_run, report)?;
        }

        let rendered_source = read_markdown_required(&resolve_command_skill_content_path(command_dir))?;
        let frontmatter = parse_frontmatter(&rendered_source);
        let body = strip_frontmatter(&rendered_source);

        let gemini_target = ctx.gemini_commands_target().join(format!("{name}.toml"));
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "gemini") {
            write_text(
                &gemini_target,
                &render_gemini_command(name, &frontmatter, &body),
                ctx.opts.dry_run,
            )?;
            report.written_files.push(gemini_target);
        } else {
            remove_managed_file_if_present(&gemini_target, ctx.opts.dry_run, report)?;
        }

        let claude_target = ctx.claude_commands_target().join(format!("{name}.md"));
        remove_managed_file_if_present(&claude_target, ctx.opts.dry_run, report)?;

        let opencode_target = ctx.opencode_commands_target().join(format!("{name}.md"));
        if ctx.opts.selected_runtimes.iter().any(|rt| rt == "opencode") {
            write_text(
                &opencode_target,
                &render_opencode_command(name, &frontmatter, &body),
                ctx.opts.dry_run,
            )?;
            report.written_files.push(opencode_target);
        } else {
            remove_managed_file_if_present(&opencode_target, ctx.opts.dry_run, report)?;
        }
    }

    let link_cleanup_roots = [
        ctx.copilot_skills_target(),
        ctx.gemini_skills_target(),
        ctx.antigravity_root().join("skills"),
        ctx.shared_skills_target(),
        ctx.codex_skills_target(),
    ];
    for root in link_cleanup_roots {
        prune_stale_command_links(&root, &active_names, ctx.opts.dry_run, report)?;
        prune_legacy_gal_prefixed_dirs(&root, &active_names, ctx.opts.dry_run, report)?;
    }
    prune_stale_managed_files(
        &ctx.gemini_commands_target(),
        "toml",
        &active_names,
        ctx.opts.dry_run,
        report,
    )?;
    prune_stale_managed_files(
        &ctx.claude_commands_target(),
        "md",
        &active_names,
        ctx.opts.dry_run,
        report,
    )?;
    prune_stale_managed_files(
        &ctx.opencode_commands_target(),
        "md",
        &active_names,
        ctx.opts.dry_run,
        report,
    )?;

    Ok(())
}

fn update_personalization(
    ctx: &PersonalizationContext,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    let skill_names = list_named_children(&ctx.opts.source_root.join("skills"))?;

    ensure_dir(&ctx.gal_home(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.gemini_root(), ctx.opts.dry_run)?;
    ensure_dir(&ctx.antigravity_root(), ctx.opts.dry_run)?;

    let gemini_context = ctx.gemini_context_file();
    if ctx.opts.uninstall || !ctx.has_runtime("gemini") {
        remove_file_if_present(&gemini_context, ctx.opts.dry_run, report)?;
    } else {
        let context_content = skill_names
            .iter()
            .map(|name| {
                format!(
                    "@{}",
                    ctx.opts
                        .source_root
                        .join("skills")
                        .join(name)
                        .join("SKILL.md")
                        .display()
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        write_text_with_report(&gemini_context, &context_content, ctx.opts.dry_run, report)?;
    }

    if !ctx.opts.uninstall && ctx.has_runtime("gemini") {
        if let Some(mut settings) = read_json_map_or_warn(&ctx.gemini_settings_file(), report)? {
            merge_context_file_names(&mut settings, &["AGENTS.md", "GEMINI.md"]);
            write_json_map_with_report(
                &ctx.gemini_settings_file(),
                &settings,
                ctx.opts.dry_run,
                report,
            )?;
        }
    }

    if load_install_mode(ctx) != "install" {
        if ctx.opts.uninstall || !ctx.has_runtime("antigravity") {
            remove_dir_if_present(&ctx.agy_plugin_install_target(), ctx.opts.dry_run, report)?;
        } else {
            build_agy_plugin(ctx, report)?;
        }
    }

    let workspace_rule_file = ctx.workspace_rules_target().join("gal.md");
    if workspace_rule_file.exists() {
        if !is_gal_managed_file(&workspace_rule_file) {
            report.warnings.push(ProjectionWarning {
                message: format!(
                    "preserved user-owned repo rule: {}",
                    workspace_rule_file.display()
                ),
            });
        } else {
            remove_file_if_present(&workspace_rule_file, ctx.opts.dry_run, report)?;
        }
    }
    for dir in [
        ctx.workspace_skills_target(),
        ctx.workspace_rules_target(),
        ctx.workspace_agents_root(),
    ] {
        remove_empty_dir_if_present(&dir, ctx.opts.dry_run, report)?;
    }

    if !ctx.opts.uninstall && ctx.has_runtime("copilot") {
        if let Some(mut settings) = read_json_map_or_warn(&ctx.vscode_settings_file(), report)? {
            set_vscode_skills_bridge(&mut settings);
            write_json_map_with_report(
                &ctx.vscode_settings_file(),
                &settings,
                ctx.opts.dry_run,
                report,
            )?;
        }
    }

    if ctx.opts.uninstall || ctx.opts.dry_run {
        return Ok(());
    }

    let primary_local_env = ctx.gal_config_root().join("config.local.env");
    let legacy_local_env = ctx.opts.repo_root.join("config.local.env");
    let local_env = if !primary_local_env.exists() && legacy_local_env.exists() {
        legacy_local_env
    } else {
        primary_local_env
    };

    let legacy_routing = ctx.legacy_routing_target();
    let local_routing = ctx.local_routing_target();
    if legacy_routing.exists() && !local_routing.exists() {
        report.warnings.push(ProjectionWarning {
            message: format!(
                "legacy executor-routing.ndjson requires manual migration: {} -> {}",
                legacy_routing.display(),
                local_routing.display()
            ),
        });
    }
    if !local_routing.exists() {
        let example_routing = ctx.example_routing_source();
        if example_routing.is_file() {
            copy_file_with_report(&example_routing, &local_routing, ctx.opts.dry_run, report)?;
        } else {
            report.warnings.push(ProjectionWarning {
                message: format!(
                    "missing executor-routing example template: {}",
                    example_routing.display()
                ),
            });
        }
    }

    configure_git(ctx, report)?;
    recheckout_filtered_files_if_needed(ctx, &local_env, report)?;
    Ok(())
}

pub struct SkillsProjectionHealthCheck {
    shared_skills_root: PathBuf,
}

impl SkillsProjectionHealthCheck {
    pub fn with_path(shared_skills_root: PathBuf) -> Self {
        Self { shared_skills_root }
    }
}

impl HealthCheck for SkillsProjectionHealthCheck {
    fn name(&self) -> &str {
        "skills-projection"
    }

    fn check(&self) -> Vec<DoctorFinding> {
        if !self.shared_skills_root.exists() {
            return vec![DoctorFinding::warning(format!(
                "shared skill projection not found: {} — run `gal update --machine-only`",
                self.shared_skills_root.display()
            ))];
        }
        if !self.shared_skills_root.is_dir() {
            return vec![DoctorFinding::error(
                format!(
                    "shared skill projection is not a directory: {}",
                    self.shared_skills_root.display()
                ),
                "remove the path and rerun `gal update --machine-only`",
            )];
        }
        vec![]
    }
}

#[derive(Debug, Clone, Default)]
struct Frontmatter {
    description: Option<String>,
    color: Option<String>,
    tools: Vec<String>,
}

fn parse_frontmatter(raw: &str) -> Frontmatter {
    let mut lines = raw.lines();
    if lines.next() != Some("---") {
        return Frontmatter::default();
    }

    let mut description = None;
    let mut color = None;
    let mut tools = Vec::new();
    for line in lines {
        if line.trim() == "---" {
            break;
        }
        if let Some((key, value)) = line.split_once(':') {
            let key = key.trim();
            let value = value.trim().trim_matches('"');
            if key == "description" {
                description = Some(value.to_string());
            } else if key == "color" {
                color = Some(value.to_string());
            } else if key == "tools" {
                tools = value
                    .trim_matches(['[', ']'])
                    .split(',')
                    .map(|part| part.trim().trim_matches('"').trim_matches('\''))
                    .filter(|part| !part.is_empty())
                    .map(str::to_string)
                    .collect();
            }
        }
    }

    Frontmatter {
        description,
        color,
        tools,
    }
}

fn strip_frontmatter(raw: &str) -> String {
    let mut lines = raw.lines();
    if lines.next() != Some("---") {
        return raw.trim().to_string();
    }

    let mut body = String::new();
    let mut in_frontmatter = true;
    for line in raw.lines().skip(1) {
        if in_frontmatter {
            if line.trim() == "---" {
                in_frontmatter = false;
            }
            continue;
        }
        body.push_str(line);
        body.push('\n');
    }
    body.trim().to_string()
}

fn render_opencode_agent(_name: &str, frontmatter: &Frontmatter, body: &str) -> String {
    let mut permissions = Vec::new();
    for tool in &frontmatter.tools {
        match tool.as_str() {
            "read" => {
                push_permission(&mut permissions, "read");
                push_permission(&mut permissions, "list");
            }
            "search" => {
                push_permission(&mut permissions, "read");
                push_permission(&mut permissions, "list");
                push_permission(&mut permissions, "grep");
                push_permission(&mut permissions, "glob");
            }
            "list" => {
                push_permission(&mut permissions, "list");
            }
            "edit" => {
                push_permission(&mut permissions, "edit");
            }
            "execute" => {
                push_permission(&mut permissions, "bash");
            }
            _ => {}
        }
    }

    if permissions.is_empty() {
        push_permission(&mut permissions, "read");
        push_permission(&mut permissions, "list");
    }

    let description = frontmatter
        .description
        .clone()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "GAL golem agent".into());

    let mut lines = vec![
        GAL_MANAGED_FILE_HEADER.to_string(),
        "---".into(),
        "description: |".into(),
    ];
    for line in description.lines() {
        lines.push(format!("  {line}"));
    }
    lines.push("mode: subagent".into());
    if let Some(color) = &frontmatter.color {
        lines.push(format!("color: {color}"));
    }
    lines.push("permission:".into());
    for permission in permissions {
        lines.push(format!("  {permission}: allow"));
    }
    lines.push("---".into());
    lines.push(String::new());
    lines.push(body.trim().to_string());
    lines.push(String::new());
    lines.join("\n")
}

fn render_gemini_command(_name: &str, frontmatter: &Frontmatter, body: &str) -> String {
    let description = frontmatter
        .description
        .clone()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "GAL command".into());
    let prompt = format!("User command arguments, if any: {{{{args}}}}\n\n{}", body.trim());
    format!(
        "{header}\ndescription = \"{description}\"\nprompt = '''\n{prompt}\n'''\n",
        header = GAL_MANAGED_FILE_HEADER,
        description = escape_toml_basic_string(&description),
        prompt = prompt.replace("'''", "\\'\\'\\'")
    )
}

fn render_opencode_command(name: &str, frontmatter: &Frontmatter, body: &str) -> String {
    let description = frontmatter
        .description
        .clone()
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "GAL command".into());
    let rendered_body = if name == "git-commit-msg" {
        "Use the baseline below for the type(scope) prefix (it is a no-hijack path/status classifier that never reads the diff body), then read the staged diff and write a subject describing what actually changed. Do not ship the generic baseline subject verbatim. Keep the type(scope) prefix unless the diff clearly contradicts it. Add up to three body bullets only for broader changes. Do not add explanations, markdown fences, reasoning tags, JSON, or any extra prose. If the baseline reports No changes staged for commit. or Not a git repository., return that text exactly. Apply extra instructions if provided: $ARGUMENTS\n\n!`gal commit-msg --print`".to_string()
    } else {
        body.trim().to_string()
    };

    let mut lines = vec![
        GAL_MANAGED_FILE_HEADER.to_string(),
        "---".into(),
        "description: |".into(),
    ];
    for line in description.lines() {
        lines.push(format!("  {line}"));
    }
    lines.push("---".into());
    lines.push(String::new());
    lines.push("User command arguments, if any: $ARGUMENTS".into());
    lines.push(String::new());
    lines.push(rendered_body);
    lines.push(String::new());
    lines.join("\n")
}

fn push_permission(permissions: &mut Vec<&'static str>, value: &'static str) {
    if !permissions.contains(&value) {
        permissions.push(value);
    }
}

fn list_named_children(root: &Path) -> Result<Vec<String>, AdapterError> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut names = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if entry.file_type()?.is_dir() {
            names.push(entry.file_name().to_string_lossy().to_string());
        }
    }
    names.sort();
    Ok(names)
}

fn list_files_with_extension(root: &Path, suffix: &str) -> Result<Vec<PathBuf>, AdapterError> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut files = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if entry.file_type()?.is_file()
            && entry
                .path()
                .file_name()
                .and_then(OsStr::to_str)
                .map(|name| name.ends_with(suffix))
                .unwrap_or(false)
        {
            files.push(entry.path());
        }
    }
    files.sort();
    Ok(files)
}

fn list_command_dirs(root: &Path) -> Result<Vec<PathBuf>, AdapterError> {
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut dirs = Vec::new();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let path = entry.path();
        if path.join("SKILL.md").is_file() || path.join("SKILL.template.md").is_file() {
            dirs.push(path);
        }
    }
    dirs.sort();
    Ok(dirs)
}

fn read_markdown_required(path: &Path) -> Result<String, AdapterError> {
    fs::read_to_string(path).map_err(AdapterError::from)
}

fn resolve_command_skill_content_path(command_dir: &Path) -> PathBuf {
    let baked = command_dir.join("SKILL.md");
    if baked.is_file() {
        return baked;
    }

    let template = command_dir.join("SKILL.template.md");
    if template.is_file() {
        return template;
    }

    baked
}

fn bake_command_content(command_dir: &Path, repo_root: &Path) -> Result<String, AdapterError> {
    let template = command_dir.join("SKILL.template.md");
    if !template.is_file() {
        return read_markdown_required(&command_dir.join("SKILL.md"));
    }

    let mut baked = read_markdown_required(&template)?;
    baked = baked.replace("{{GAL_ROOT}}", &repo_root.display().to_string());

    let local_override = command_dir.join("SKILL.local.md");
    if !local_override.is_file() {
        return Ok(baked);
    }

    let local = read_markdown_required(&local_override)?;
    if local.trim().is_empty() {
        return Ok(baked);
    }

    Ok(format!(
        "{}\n\n<!-- GAL LOCAL OVERRIDE START -->\n<!-- Source: SKILL.local.md (gitignored machine-local overlay) -->\n{}\n<!-- GAL LOCAL OVERRIDE END -->\n",
        baked.trim_end(),
        local.trim()
    ))
}

fn escape_toml_basic_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn prune_stale_links<'a>(
    root: &Path,
    keep_names: impl IntoIterator<Item = &'a str>,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !root.is_dir() {
        return Ok(());
    }

    let keep: Vec<&str> = keep_names.into_iter().collect();
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        if keep.contains(&name) {
            continue;
        }

        let path = entry.path();
        if is_symlink_or_junction(&path) {
            if !dry_run {
                remove_link(&path)?;
            }
            report.removed_paths.push(path);
        }
    }
    Ok(())
}

fn prune_stale_command_links(
    root: &Path,
    active_names: &[&str],
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !root.is_dir() {
        return Ok(());
    }

    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let path = entry.path();
        let Some(name) = path.file_name().and_then(OsStr::to_str) else {
            continue;
        };
        if active_names.contains(&name) || !is_gal_command_link(&path, &path_needle_for_commands()) {
            continue;
        }
        remove_link_if_present(&path, dry_run, report)?;
    }
    Ok(())
}

fn prune_legacy_gal_prefixed_dirs(
    root: &Path,
    active_names: &[&str],
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !root.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let path = entry.path();
        let Some(name) = path.file_name().and_then(OsStr::to_str) else {
            continue;
        };
        if !name.starts_with("gal-") || active_names.contains(&name) {
            continue;
        }
        if !dry_run {
            fs::remove_dir_all(&path)?;
        }
        report.removed_paths.push(path);
    }
    Ok(())
}

fn prune_stale_managed_files(
    root: &Path,
    extension: &str,
    active_names: &[&str],
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !root.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            continue;
        }
        let path = entry.path();
        let is_extension_match = path
            .extension()
            .and_then(OsStr::to_str)
            .map(|value| value.eq_ignore_ascii_case(extension))
            .unwrap_or(false);
        if !is_extension_match || !is_gal_managed_file(&path) {
            continue;
        }
        let Some(name) = path.file_stem().and_then(OsStr::to_str) else {
            continue;
        };
        if active_names.contains(&name) {
            continue;
        }
        remove_managed_file_if_present(&path, dry_run, report)?;
    }
    Ok(())
}

fn ensure_dir(path: &Path, dry_run: bool) -> Result<(), AdapterError> {
    if dry_run || path.is_dir() {
        return Ok(());
    }
    fs::create_dir_all(path)?;
    Ok(())
}

fn write_text(
    path: &Path,
    content: &str,
    dry_run: bool,
) -> Result<(), AdapterError> {
    let normalized = format!("{}\n", content.trim_end());
    if !dry_run {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, normalized.as_bytes())?;
    }
    Ok(())
}

fn remove_link_if_present(path: &Path, dry_run: bool, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    if !is_symlink_or_junction(path) {
        return Ok(());
    }
    if !dry_run {
        remove_link(path)?;
    }
    report.removed_paths.push(path.to_path_buf());
    Ok(())
}

fn remove_managed_file_if_present(path: &Path, dry_run: bool, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    if !is_gal_managed_file(path) {
        return Ok(());
    }
    if !dry_run {
        fs::remove_file(path)?;
    }
    report.removed_paths.push(path.to_path_buf());
    Ok(())
}

fn ensure_dir_link(
    target: &Path,
    link: &Path,
    replace: bool,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if same_path(link, target) {
        return Ok(());
    }
    if is_symlink_or_junction(link) {
        if dry_run {
            report.created_links.push(link.to_path_buf());
            return Ok(());
        }
        remove_dir_link(link)?;
    } else if link.exists() {
        if !replace {
            report.warnings.push(ProjectionWarning {
                message: format!("preserved user-owned path: {}", link.display()),
            });
            return Ok(());
        }
        let backup = backup_path(link);
        if !dry_run {
            if backup.exists() {
                if backup.is_dir() {
                    fs::remove_dir_all(&backup)?;
                } else {
                    fs::remove_file(&backup)?;
                }
            }
            fs::rename(link, &backup)?;
        }
        report.removed_paths.push(backup);
    }
    if !dry_run {
        if let Some(parent) = link.parent() {
            fs::create_dir_all(parent)?;
        }
        create_dir_link(target, link)?;
    }
    report.created_links.push(link.to_path_buf());
    Ok(())
}

fn ensure_file_link(
    target: &Path,
    link: &Path,
    replace: bool,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if same_path(link, target) {
        return Ok(());
    }
    if is_symlink_or_junction(link) {
        if dry_run {
            report.created_links.push(link.to_path_buf());
            return Ok(());
        }
        remove_link(link)?;
    } else if link.exists() {
        if !replace {
            report.warnings.push(ProjectionWarning {
                message: format!("preserved user-owned path: {}", link.display()),
            });
            return Ok(());
        }
        let backup = backup_path(link);
        if !dry_run {
            if backup.exists() {
                if backup.is_dir() {
                    fs::remove_dir_all(&backup)?;
                } else {
                    fs::remove_file(&backup)?;
                }
            }
            fs::rename(link, &backup)?;
        }
        report.removed_paths.push(backup);
    }
    if !dry_run {
        if let Some(parent) = link.parent() {
            fs::create_dir_all(parent)?;
        }
        create_file_link(target, link)?;
    }
    report.created_links.push(link.to_path_buf());
    Ok(())
}

fn same_path(left: &Path, right: &Path) -> bool {
    match (fs::canonicalize(left), fs::canonicalize(right)) {
        (Ok(a), Ok(b)) => a == b,
        _ => false,
    }
}

fn backup_path(path: &Path) -> PathBuf {
    let name = path
        .file_name()
        .and_then(OsStr::to_str)
        .map(|value| format!("{value}.bak"))
        .unwrap_or_else(|| "backup.bak".into());
    path.with_file_name(name)
}

fn is_gal_managed_file(path: &Path) -> bool {
    fs::read_to_string(path)
        .ok()
        .and_then(|content| content.lines().next().map(str::to_string))
        .map(|first| first == GAL_MANAGED_FILE_HEADER)
        .unwrap_or(false)
}

fn is_gal_repo_link(path: &Path, repo_root: &Path) -> bool {
    if !is_symlink_or_junction(path) {
        return false;
    }
    match (fs::canonicalize(path), fs::canonicalize(repo_root)) {
        (Ok(target), Ok(root)) => target.starts_with(root),
        _ => false,
    }
}

fn path_needle_for_commands() -> String {
    format!("{}commands{}", std::path::MAIN_SEPARATOR, std::path::MAIN_SEPARATOR)
}

fn is_gal_command_link(path: &Path, repo_root_fragment: &str) -> bool {
    if !is_symlink_or_junction(path) {
        return false;
    }
    fs::canonicalize(path)
        .ok()
        .and_then(|target| target.to_str().map(str::to_string))
        .map(|target| target.contains(repo_root_fragment))
        .unwrap_or(false)
}

fn create_file_link(target: &Path, link: &Path) -> io::Result<()> {
    #[cfg(windows)]
    {
        let output = std::process::Command::new("cmd")
            .args(["/C", "mklink", &link.to_string_lossy(), &target.to_string_lossy()])
            .output()?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(io::Error::new(io::ErrorKind::Other, stderr.into_owned()));
        }
        Ok(())
    }
    #[cfg(not(windows))]
    {
        std::os::unix::fs::symlink(target, link)
    }
}

fn remove_link(path: &Path) -> io::Result<()> {
    let metadata = path.symlink_metadata()?;
    if metadata.file_type().is_dir() {
        remove_dir_link(path)
    } else {
        fs::remove_file(path)
    }
}

fn remove_if_gal_owned_dir(path: &Path, dry_run: bool, report: &mut ProjectionReport) -> Result<(), AdapterError> {
    if !path.exists() {
        return Ok(());
    }
    if is_symlink_or_junction(path) {
        if !dry_run {
            remove_dir_link(path)?;
        }
        report.removed_paths.push(path.to_path_buf());
        return Ok(());
    }
    if path.is_dir() {
        let marker = path.join(".gal-managed");
        if marker.exists() || path.file_name().and_then(OsStr::to_str) == Some("skills") {
            if !dry_run {
                fs::remove_dir_all(path)?;
            }
            report.removed_paths.push(path.to_path_buf());
        }
    }
    Ok(())
}

fn read_json_map_or_warn(
    path: &Path,
    report: &mut ProjectionReport,
) -> Result<Option<Map<String, Value>>, AdapterError> {
    match read_json_map(path) {
        Ok(map) => Ok(Some(map)),
        Err(err) if path.exists() => {
            report.warnings.push(ProjectionWarning {
                message: format!("could not parse JSON file, skipped bridge update: {} ({err})", path.display()),
            });
            Ok(None)
        }
        Err(err) => Err(AdapterError::from(err)),
    }
}

fn merge_context_file_names(settings: &mut Map<String, Value>, required: &[&str]) {
    let context = settings
        .entry("context")
        .or_insert_with(|| Value::Object(Map::new()));
    if !context.is_object() {
        *context = Value::Object(Map::new());
    }
    let context_obj = context.as_object_mut().expect("context object");
    let file_name = context_obj
        .entry("fileName")
        .or_insert_with(|| Value::Array(Vec::new()));
    let mut values = match file_name {
        Value::Array(existing) => existing
            .iter()
            .filter_map(Value::as_str)
            .map(str::to_string)
            .collect::<Vec<_>>(),
        Value::String(existing) => vec![existing.clone()],
        _ => Vec::new(),
    };
    for value in required {
        if !values.iter().any(|existing| existing == value) {
            values.push((*value).to_string());
        }
    }
    *file_name = Value::Array(values.into_iter().map(Value::String).collect());
}

fn set_vscode_skills_bridge(settings: &mut Map<String, Value>) {
    let locations = settings
        .entry("chat.agentSkillsLocations".to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    if !locations.is_object() {
        *locations = Value::Object(Map::new());
    }
    locations
        .as_object_mut()
        .expect("locations object")
        .insert("~/.agents/skills".into(), Value::Bool(false));
}

fn write_text_with_report(
    path: &Path,
    content: &str,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    write_text(path, content, dry_run)?;
    report.written_files.push(path.to_path_buf());
    Ok(())
}

fn write_json_map_with_report(
    path: &Path,
    data: &Map<String, Value>,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    let rendered = serde_json::to_string_pretty(&Value::Object(data.clone()))
        .map_err(|err| AdapterError::Message(err.to_string()))?;
    write_text_with_report(path, &rendered, dry_run, report)
}

fn copy_file_with_report(
    source: &Path,
    target: &Path,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    let content = fs::read_to_string(source)?;
    write_text_with_report(target, &content, dry_run, report)
}

fn remove_file_if_present(
    path: &Path,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !path.is_file() {
        return Ok(());
    }
    if !dry_run {
        fs::remove_file(path)?;
    }
    report.removed_paths.push(path.to_path_buf());
    Ok(())
}

fn remove_dir_if_present(
    path: &Path,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !path.exists() {
        return Ok(());
    }
    if !dry_run {
        if is_symlink_or_junction(path) {
            remove_dir_link(path)?;
        } else {
            fs::remove_dir_all(path)?;
        }
    }
    report.removed_paths.push(path.to_path_buf());
    Ok(())
}

fn remove_empty_dir_if_present(
    path: &Path,
    dry_run: bool,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !path.is_dir() {
        return Ok(());
    }
    if fs::read_dir(path)?.next().is_some() {
        return Ok(());
    }
    if !dry_run {
        fs::remove_dir(path)?;
    }
    report.removed_paths.push(path.to_path_buf());
    Ok(())
}

fn load_install_mode(ctx: &PersonalizationContext) -> &'static str {
    let config = GalConfig::load_from_path(&ctx.config_file());
    if config.is_dev_mode() {
        "source"
    } else {
        "install"
    }
}

fn build_agy_plugin(
    ctx: &PersonalizationContext,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    let script = if cfg!(windows) {
        ctx.opts.repo_root.join("scripts").join("Build-CorePlugin.ps1")
    } else {
        ctx.opts.repo_root.join("scripts").join("build-core-plugin.sh")
    };
    if !script.is_file() {
        report.warnings.push(ProjectionWarning {
            message: format!("missing AGY build script: {}", script.display()),
        });
        return Ok(());
    }
    if ctx.opts.dry_run {
        report.written_files.push(ctx.agy_plugin_install_target());
        return Ok(());
    }
    let mut command = if cfg!(windows) {
        let mut cmd = Command::new("powershell");
        cmd.args([
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            script.to_string_lossy().as_ref(),
            "-RepoRoot",
            ctx.opts.repo_root.to_string_lossy().as_ref(),
            "-InstallMode",
            load_install_mode(ctx),
            "-Force",
            "-Install",
        ]);
        cmd
    } else {
        let mut cmd = Command::new("bash");
        cmd.args([script.to_string_lossy().as_ref(), "--force", "--install"]);
        cmd
    };
    command.current_dir(&ctx.opts.repo_root);
    let output = command.output()?;
    if !output.status.success() {
        return Err(AdapterError::Message(format!(
            "AGY plugin build failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    report.written_files.push(ctx.agy_plugin_install_target());
    Ok(())
}

fn configure_git(
    ctx: &PersonalizationContext,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    for (key, value) in [
        ("filter.gal-config.smudge", "bash scripts/gal-smudge.sh"),
        ("filter.gal-config.clean", "bash scripts/gal-clean.sh"),
        ("filter.gal-config.required", "true"),
        ("core.hooksPath", "plugins/gal-core/hooks"),
    ] {
        let output = Command::new("git")
            .current_dir(&ctx.opts.repo_root)
            .args(["config", key, value])
            .output()?;
        if !output.status.success() {
            return Err(AdapterError::Message(format!(
                "git config {key} failed: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            )));
        }
    }
    report.written_files.push(ctx.opts.repo_root.join(".git").join("config"));
    Ok(())
}

fn recheckout_filtered_files_if_needed(
    ctx: &PersonalizationContext,
    local_env: &Path,
    report: &mut ProjectionReport,
) -> Result<(), AdapterError> {
    if !local_env.is_file() {
        return Ok(());
    }
    let repo_local_env = ctx.opts.repo_root.join("config.local.env");
    if local_env != repo_local_env {
        return Ok(());
    }
    let has_values = fs::read_to_string(local_env)?
        .lines()
        .any(|line| match line.split_once('=') {
            Some((left, right)) => !left.trim().is_empty() && !left.trim_start().starts_with('#') && !right.trim().is_empty(),
            None => false,
        });
    if !has_values {
        return Ok(());
    }
    let tracked = Command::new("git")
        .current_dir(&ctx.opts.repo_root)
        .args(["ls-files", "--error-unmatch", "config.local.env"])
        .output()?;
    if !tracked.status.success() {
        return Ok(());
    }
    let checkout = Command::new("git")
        .current_dir(&ctx.opts.repo_root)
        .args(["checkout", "--", "config.local.env"])
        .output()?;
    if !checkout.status.success() {
        return Err(AdapterError::Message(format!(
            "git checkout -- config.local.env failed: {}",
            String::from_utf8_lossy(&checkout.stderr).trim()
        )));
    }
    report.written_files.push(ctx.opts.repo_root.join("config.local.env"));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fixture_roots() -> (TempDir, PathBuf, PathBuf, PathBuf) {
        let temp = TempDir::new().unwrap();
        let repo_root = temp.path().join("repo");
        let source_root = repo_root.join("plugins").join("gal-core");
        let home = temp.path().join("home");
        fs::create_dir_all(source_root.join("skills").join("sample-skill")).unwrap();
        fs::create_dir_all(source_root.join("agents")).unwrap();
        fs::create_dir_all(source_root.join("commands")).unwrap();
        (temp, repo_root, source_root, home)
    }

    fn fixture_roots_with_appdata() -> (TempDir, PathBuf, PathBuf, PathBuf, PathBuf) {
        let (temp, repo_root, source_root, home) = fixture_roots();
        let appdata = temp.path().join("appdata");
        fs::create_dir_all(&appdata).unwrap();
        Command::new("git")
            .args(["init", "-q"])
            .current_dir(&repo_root)
            .output()
            .unwrap();
        (temp, repo_root, source_root, home, appdata)
    }

    fn write_skill_fixture(source_root: &Path, name: &str) {
        let skill_root = source_root.join("skills").join(name);
        fs::create_dir_all(&skill_root).unwrap();
        fs::write(skill_root.join("SKILL.md"), format!("# {name}\n")).unwrap();
    }

    fn write_command_fixture(source_root: &Path, name: &str) {
        let command_root = source_root.join("commands").join(name);
        fs::create_dir_all(&command_root).unwrap();
        fs::write(
            command_root.join("SKILL.template.md"),
            "---\ndescription: sample command\n---\nUse {{GAL_ROOT}}\n",
        )
        .unwrap();
        fs::write(command_root.join("SKILL.local.md"), "Local note\n").unwrap();
    }

    #[test]
    fn update_skills_projects_links_and_agents() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        fs::write(source_root.join("skills").join("sample-skill").join("SKILL.md"), "# Skill").unwrap();
        fs::write(
            source_root.join("agents").join("helper.agent.md"),
            "---\ndescription: helper\ncolor: green\ntools: [read, edit, execute]\n---\nBody\n",
        )
        .unwrap();

        let report = run_update_skills(&SkillUpdateOptions {
            repo_root: repo_root.clone(),
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["copilot".into(), "gemini".into(), "antigravity".into(), "opencode".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(!report.created_links.is_empty());
        assert!(home.join(".agents").join("skills").join("sample-skill").exists());
        assert!(home.join(".copilot").join("agents").join("helper.agent.md").exists());
        assert!(home.join(".copilot").join("gal").exists());
        assert!(home.join(".gemini").join("gal").exists());
        assert!(home.join(".gemini").join("antigravity-cli").join("gal").exists());
        let rendered = fs::read_to_string(home.join(".config").join("opencode").join("agents").join("helper.md")).unwrap();
        assert!(rendered.starts_with(GAL_MANAGED_FILE_HEADER));
        assert!(rendered.contains("color: green"));
        assert!(rendered.contains("  read: allow"));
        assert!(rendered.contains("  list: allow"));
        assert!(rendered.contains("  edit: allow"));
        assert!(rendered.contains("  bash: allow"));
    }

    #[test]
    fn update_skills_skips_shared_projection_without_codex_or_opencode() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        fs::write(source_root.join("skills").join("sample-skill").join("SKILL.md"), "# Skill").unwrap();

        run_update_skills(&SkillUpdateOptions {
            repo_root,
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["copilot".into(), "gemini".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(!home.join(".agents").join("skills").join("sample-skill").exists());
    }

    #[test]
    fn healthcheck_warns_when_projection_missing() {
        let temp = TempDir::new().unwrap();
        let check = SkillsProjectionHealthCheck::with_path(temp.path().join("missing"));
        let findings = check.check();
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, base::health::Severity::Warning);
    }

    #[test]
    fn healthcheck_accepts_existing_directory() {
        let temp = TempDir::new().unwrap();
        let path = temp.path().join("skills");
        fs::create_dir_all(&path).unwrap();
        let check = SkillsProjectionHealthCheck::with_path(path);
        assert!(check.check().is_empty());
    }

    #[test]
    fn render_opencode_agent_matches_legacy_shape() {
        let rendered = render_opencode_agent(
            "helper",
            &Frontmatter {
                description: Some("helper line 1\nhelper line 2".into()),
                color: Some("green".into()),
                tools: Vec::new(),
            },
            "Body",
        );

        assert_eq!(
            rendered,
            "# Generated by GAL Setup-Machine. Do not edit manually.\n---\ndescription: |\n  helper line 1\n  helper line 2\nmode: subagent\ncolor: green\npermission:\n  read: allow\n  list: allow\n---\n\nBody\n"
        );
    }

    #[test]
    fn render_opencode_agent_expands_search_permissions() {
        let rendered = render_opencode_agent(
            "helper",
            &Frontmatter {
                description: Some("helper".into()),
                color: None,
                tools: vec!["search".into()],
            },
            "Body",
        );

        assert!(rendered.contains("  read: allow"));
        assert!(rendered.contains("  list: allow"));
        assert!(rendered.contains("  grep: allow"));
        assert!(rendered.contains("  glob: allow"));
    }

    #[test]
    fn update_commands_bakes_and_projects_outputs() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        write_command_fixture(&source_root, "sample-command");

        let report = run_update_commands(&CommandUpdateOptions {
            repo_root: repo_root.clone(),
            source_root: source_root.clone(),
            user_home: home.clone(),
            selected_runtimes: vec!["gemini".into(), "codex".into(), "opencode".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        let baked = fs::read_to_string(
            source_root.join("commands").join("sample-command").join("SKILL.md"),
        )
        .unwrap();
        assert!(baked.contains(&repo_root.display().to_string()));
        assert!(baked.contains("GAL LOCAL OVERRIDE START"));
        assert!(home.join(".codex").join("skills").join("sample-command").exists());

        let gemini = fs::read_to_string(
            home.join(".gemini").join("commands").join("sample-command.toml"),
        )
        .unwrap();
        assert!(gemini.starts_with(GAL_MANAGED_FILE_HEADER));
        assert!(gemini.contains("User command arguments, if any: {{args}}"));

        let opencode = fs::read_to_string(
            home.join(".config").join("opencode").join("commands").join("sample-command.md"),
        )
        .unwrap();
        assert!(opencode.starts_with(GAL_MANAGED_FILE_HEADER));
        assert!(opencode.contains("User command arguments, if any: $ARGUMENTS"));
        assert!(!report.written_files.is_empty());
    }

    #[test]
    fn update_commands_removes_managed_outputs_for_unselected_runtimes() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        write_command_fixture(&source_root, "sample-command");

        let gemini_target = home.join(".gemini").join("commands").join("sample-command.toml");
        let opencode_target = home.join(".config").join("opencode").join("commands").join("sample-command.md");
        let claude_target = home.join(".claude").join("commands").join("sample-command.md");
        fs::create_dir_all(gemini_target.parent().unwrap()).unwrap();
        fs::create_dir_all(opencode_target.parent().unwrap()).unwrap();
        fs::create_dir_all(claude_target.parent().unwrap()).unwrap();
        fs::write(&gemini_target, format!("{GAL_MANAGED_FILE_HEADER}\nold\n")).unwrap();
        fs::write(&opencode_target, format!("{GAL_MANAGED_FILE_HEADER}\nold\n")).unwrap();
        fs::write(&claude_target, format!("{GAL_MANAGED_FILE_HEADER}\nold\n")).unwrap();

        run_update_commands(&CommandUpdateOptions {
            repo_root,
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["copilot".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(!gemini_target.exists());
        assert!(!opencode_target.exists());
        assert!(!claude_target.exists());
    }

    #[test]
    fn update_commands_prunes_obsolete_managed_files() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        write_command_fixture(&source_root, "sample-command");

        let gemini_commands = home.join(".gemini").join("commands");
        let opencode_commands = home.join(".config").join("opencode").join("commands");
        fs::create_dir_all(&gemini_commands).unwrap();
        fs::create_dir_all(&opencode_commands).unwrap();
        fs::write(
            gemini_commands.join("old-command.toml"),
            format!("{GAL_MANAGED_FILE_HEADER}\nold\n"),
        )
        .unwrap();
        fs::write(
            opencode_commands.join("old-command.md"),
            format!("{GAL_MANAGED_FILE_HEADER}\nold\n"),
        )
        .unwrap();

        run_update_commands(&CommandUpdateOptions {
            repo_root,
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["gemini".into(), "opencode".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(!gemini_commands.join("old-command.toml").exists());
        assert!(!opencode_commands.join("old-command.md").exists());
        assert!(gemini_commands.join("sample-command.toml").exists());
        assert!(opencode_commands.join("sample-command.md").exists());
    }

    #[test]
    fn update_commands_preserves_user_owned_shared_skill_link() {
        let (_temp, repo_root, source_root, home) = fixture_roots();
        write_command_fixture(&source_root, "sample-command");

        let external_target = home.join("external-command");
        fs::create_dir_all(&external_target).unwrap();
        let shared_target = home.join(".agents").join("skills").join("sample-command");
        fs::create_dir_all(shared_target.parent().unwrap()).unwrap();
        create_dir_link(&external_target, &shared_target).unwrap();

        run_update_commands(&CommandUpdateOptions {
            repo_root,
            source_root,
            user_home: home.clone(),
            selected_runtimes: vec!["gemini".into()],
            dry_run: false,
            replace: true,
        })
        .unwrap();

        assert!(shared_target.exists());
        assert_eq!(fs::canonicalize(&shared_target).unwrap(), fs::canonicalize(&external_target).unwrap());
    }

    #[test]
    fn update_personalization_writes_context_bridges_and_routing() {
        let (_temp, repo_root, source_root, home, appdata) = fixture_roots_with_appdata();
        write_skill_fixture(&source_root, "sample-skill");
        fs::create_dir_all(repo_root.join("plugins").join("gal-core").join("templates")).unwrap();
        fs::write(
            repo_root
                .join("plugins")
                .join("gal-core")
                .join("templates")
                .join("executor-routing.example.json"),
            "{\n  \"coder\": \"gpt-5.4\"\n}\n",
        )
        .unwrap();
        fs::create_dir_all(home.join(".gal").join("config")).unwrap();
        fs::write(
            home.join(".gal").join("config").join("config.json"),
            "{\n  \"devMode\": true\n}\n",
        )
        .unwrap();
        fs::create_dir_all(home.join(".gemini")).unwrap();
        fs::write(
            home.join(".gemini").join("settings.json"),
            "{\n  \"context\": {\"fileName\": [\"README.md\"]}\n}\n",
        )
        .unwrap();
        fs::create_dir_all(appdata.join("Code").join("User")).unwrap();

        run_update_personalization(&PersonalizationUpdateOptions {
            repo_root: repo_root.clone(),
            source_root: source_root.clone(),
            user_home: home.clone(),
            appdata_root: appdata.clone(),
            selected_runtimes: vec!["copilot".into(), "gemini".into()],
            dry_run: false,
            replace: true,
            uninstall: false,
        })
        .unwrap();

        let context = fs::read_to_string(home.join(".gemini").join("gal-context.md")).unwrap();
        assert!(context.contains(
            &format!(
                "@{}",
                source_root.join("skills").join("sample-skill").join("SKILL.md").display()
            )
        ));

        let settings: Value =
            serde_json::from_str(&fs::read_to_string(home.join(".gemini").join("settings.json")).unwrap())
                .unwrap();
        let file_names = settings["context"]["fileName"].as_array().unwrap();
        assert!(file_names.iter().any(|value| value == "README.md"));
        assert!(file_names.iter().any(|value| value == "AGENTS.md"));
        assert!(file_names.iter().any(|value| value == "GEMINI.md"));

        let vscode: Value = serde_json::from_str(
            &fs::read_to_string(appdata.join("Code").join("User").join("settings.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(
            vscode["chat.agentSkillsLocations"]["~/.agents/skills"],
            Value::Bool(false)
        );

        assert!(home
            .join(".gal")
            .join("config")
            .join("executor-routing.json")
            .exists());

        let git_config = fs::read_to_string(repo_root.join(".git").join("config")).unwrap();
        assert!(git_config.contains("[filter \"gal-config\"]"));
        assert!(git_config.contains("smudge = bash scripts/gal-smudge.sh"));
        assert!(git_config.contains("clean = bash scripts/gal-clean.sh"));
        assert!(git_config.contains("required = true"));
        assert!(git_config.contains("hooksPath = plugins/gal-core/hooks"));
    }

    #[test]
    fn update_personalization_uninstall_removes_gemini_context_and_gy_plugin() {
        let (_temp, repo_root, source_root, home, appdata) = fixture_roots_with_appdata();
        write_skill_fixture(&source_root, "sample-skill");
        fs::create_dir_all(home.join(".gemini").join("antigravity-cli").join("plugins")).unwrap();
        fs::create_dir_all(home.join(".gal").join("config")).unwrap();
        fs::write(
            home.join(".gal").join("config").join("config.json"),
            "{\n  \"devMode\": true\n}\n",
        )
        .unwrap();
        fs::create_dir_all(home.join(".gemini")).unwrap();
        fs::write(home.join(".gemini").join("gal-context.md"), "old\n").unwrap();
        fs::create_dir_all(home.join(".gemini").join("antigravity-cli").join("plugins").join("gal")).unwrap();

        run_update_personalization(&PersonalizationUpdateOptions {
            repo_root,
            source_root,
            user_home: home.clone(),
            appdata_root: appdata,
            selected_runtimes: vec!["gemini".into(), "antigravity".into()],
            dry_run: false,
            replace: true,
            uninstall: true,
        })
        .unwrap();

        assert!(!home.join(".gemini").join("gal-context.md").exists());
        assert!(!home
            .join(".gemini")
            .join("antigravity-cli")
            .join("plugins")
            .join("gal")
            .exists());
    }

    #[test]
    fn update_personalization_preserves_existing_vscode_skill_locations() {
        let (_temp, repo_root, source_root, home, appdata) = fixture_roots_with_appdata();
        write_skill_fixture(&source_root, "sample-skill");
        fs::create_dir_all(appdata.join("Code").join("User")).unwrap();
        fs::write(
            appdata.join("Code").join("User").join("settings.json"),
            "{\n  \"chat.agentSkillsLocations\": {\n    \"/custom/path\": true\n  }\n}\n",
        )
        .unwrap();

        run_update_personalization(&PersonalizationUpdateOptions {
            repo_root,
            source_root,
            user_home: home,
            appdata_root: appdata.clone(),
            selected_runtimes: vec!["copilot".into()],
            dry_run: false,
            replace: true,
            uninstall: false,
        })
        .unwrap();

        let vscode: Value = serde_json::from_str(
            &fs::read_to_string(appdata.join("Code").join("User").join("settings.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(
            vscode["chat.agentSkillsLocations"]["/custom/path"],
            Value::Bool(true)
        );
        assert_eq!(
            vscode["chat.agentSkillsLocations"]["~/.agents/skills"],
            Value::Bool(false)
        );
    }

    #[test]
    fn update_personalization_dry_run_does_not_invoke_agy_build() {
        let (_temp, repo_root, source_root, home, appdata) = fixture_roots_with_appdata();
        write_skill_fixture(&source_root, "sample-skill");
        fs::create_dir_all(home.join(".gal").join("config")).unwrap();
        fs::write(
            home.join(".gal").join("config").join("config.json"),
            "{\n  \"devMode\": true\n}\n",
        )
        .unwrap();
        let scripts_dir = repo_root.join("scripts");
        fs::create_dir_all(&scripts_dir).unwrap();
        let sentinel = repo_root.join("agy-build-sentinel.txt");
        #[cfg(windows)]
        fs::write(
            scripts_dir.join("Build-CorePlugin.ps1"),
            format!("New-Item -ItemType File -Path '{}' -Force | Out-Null\n", sentinel.display()),
        )
        .unwrap();
        #[cfg(not(windows))]
        {
            use std::os::unix::fs::PermissionsExt;
            let script_path = scripts_dir.join("build-core-plugin.sh");
            fs::write(
                &script_path,
                format!("#!/usr/bin/env bash\ntouch '{}'\n", sentinel.display()),
            )
            .unwrap();
            let mut perms = fs::metadata(&script_path).unwrap().permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&script_path, perms).unwrap();
        }

        run_update_personalization(&PersonalizationUpdateOptions {
            repo_root,
            source_root,
            user_home: home,
            appdata_root: appdata,
            selected_runtimes: vec!["antigravity".into()],
            dry_run: true,
            replace: true,
            uninstall: false,
        })
        .unwrap();

        assert!(!sentinel.exists());
    }
}
